"""Macro events and information flow themed deck cards (shop deck)."""

MACRO_EVENTS_CARDS = [
    {
        "card_id": "MEV_E_001",
        "type": "education",
        "title": "CPI Release Mechanics",
        "body": "Consumer Price Index tracks inflation in a basket of goods and services. Surprise CPI prints can quickly reprice rate expectations.",
        "emoji": "📊",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "inflation_data"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.42,
        "diagnostic_power": 0.8,
        "base_priority": 1.08,
        "cooldown": 6,
        "left_choice": "Ignore CPI volatility",
        "right_choice": "Track inflation trend",
        "left_lesson": "Fun fact: Inflation surprises often shift both bond yields and equity multiples on the same day.",
        "right_lesson": "Fun fact: Markets respond more to inflation direction and persistence than one isolated print.",
        "card_band_color": "steel_blue",
        "alpha": 0.9,
        "weights": {"sentiment": 0.02, "inflation": 0.35, "greed": 0.0, "volatility": 0.12, "fundamentals": 0.1},
    },
    {
        "card_id": "MEV_E_002",
        "type": "education",
        "title": "Core vs Headline Inflation",
        "body": "Headline inflation includes food and energy volatility, while core inflation strips them out to reveal underlying trend.",
        "emoji": "🌡️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "inflation_data"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Use one headline number",
        "right_choice": "Compare core and headline",
        "left_lesson": "Fun fact: Energy shocks can distort headline inflation without changing core trend immediately.",
        "right_lesson": "Fun fact: Central banks typically focus on persistent components when setting policy.",
        "card_band_color": "amber",
        "alpha": 0.9,
        "weights": {"sentiment": 0.0, "inflation": 0.3, "greed": 0.0, "volatility": 0.1, "fundamentals": 0.12},
    },
    {
        "card_id": "MEV_E_003",
        "type": "education",
        "title": "Jobs Report Signal",
        "body": "Payroll growth, unemployment, and wage trends influence recession odds and central-bank policy paths.",
        "emoji": "👷",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "labor_market"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.43,
        "diagnostic_power": 0.79,
        "base_priority": 1.06,
        "cooldown": 6,
        "left_choice": "Watch headline payroll only",
        "right_choice": "Read full labor detail",
        "left_lesson": "Fun fact: Wage and participation trends can contradict payroll headlines.",
        "right_lesson": "Fun fact: Labor cooling without collapse is often treated as a constructive macro setup.",
        "card_band_color": "green",
        "alpha": 0.88,
        "weights": {"sentiment": 0.08, "inflation": 0.08, "greed": 0.02, "volatility": 0.08, "fundamentals": 0.2},
    },
    {
        "card_id": "MEV_E_004",
        "type": "education",
        "title": "PMI as Activity Gauge",
        "body": "Purchasing Managers' Index readings above 50 imply expansion; below 50 suggests contraction in surveyed sectors.",
        "emoji": "🏭",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "growth_data"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.4,
        "diagnostic_power": 0.76,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Treat PMI as lagging",
        "right_choice": "Use PMI momentum",
        "left_lesson": "Fun fact: PMI turns often lead earnings revisions by several months.",
        "right_lesson": "Fun fact: Breadth in new orders and employment components adds context to headline PMI.",
        "card_band_color": "steel_blue",
        "alpha": 0.86,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": 0.03, "volatility": 0.06, "fundamentals": 0.21},
    },
    {
        "card_id": "MEV_E_005",
        "type": "education",
        "title": "Yield Curve Meaning",
        "body": "The slope between short and long maturities reflects growth and policy expectations. Inversions can signal tighter conditions.",
        "emoji": "📉",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "rates"],
        "linked_traits": ["loss_aversion", "overconfidence"],
        "difficulty": 0.5,
        "diagnostic_power": 0.83,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "Ignore curve shape",
        "right_choice": "Monitor slope shifts",
        "left_lesson": "Fun fact: Deep inversions often tighten credit and risk appetite over time.",
        "right_lesson": "Fun fact: Curve re-steepening can mean either recovery or stress depending on the driver.",
        "card_band_color": "amber",
        "alpha": 0.97,
        "weights": {"sentiment": -0.04, "inflation": -0.05, "greed": -0.03, "volatility": 0.14, "fundamentals": 0.18},
    },
    {
        "card_id": "MEV_E_006",
        "type": "education",
        "title": "Real Rates and Valuation",
        "body": "Real rate equals nominal yield minus inflation. Higher real rates tend to pressure long-duration equity valuations.",
        "emoji": "📐",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "rates"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.52,
        "diagnostic_power": 0.84,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "Focus on nominal yields",
        "right_choice": "Use real-rate lens",
        "left_lesson": "Fun fact: Growth assets are usually most sensitive to real-rate re-pricing.",
        "right_lesson": "Fun fact: Falling inflation with stable yields can lift real rates unexpectedly.",
        "card_band_color": "red",
        "alpha": 0.98,
        "weights": {"sentiment": -0.06, "inflation": -0.1, "greed": -0.04, "volatility": 0.16, "fundamentals": 0.12},
    },
    {
        "card_id": "MEV_E_007",
        "type": "education",
        "title": "Central Bank Forward Guidance",
        "body": "Forward guidance shapes expectations about future policy and can move markets even without immediate rate changes.",
        "emoji": "🏦",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "central_bank"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.46,
        "diagnostic_power": 0.8,
        "base_priority": 1.07,
        "cooldown": 6,
        "left_choice": "Only rate decisions matter",
        "right_choice": "Guidance can reprice",
        "left_lesson": "Fun fact: Language changes in statements can shift entire curve pricing in minutes.",
        "right_lesson": "Fun fact: Market reaction often depends on expectations versus tone, not just the absolute message.",
        "card_band_color": "steel_blue",
        "alpha": 0.91,
        "weights": {"sentiment": 0.05, "inflation": 0.05, "greed": 0.03, "volatility": 0.1, "fundamentals": 0.14},
    },
    {
        "card_id": "MEV_E_008",
        "type": "education",
        "title": "Quantitative Tightening Effects",
        "body": "Reducing central-bank balance sheets can remove liquidity support and influence term premiums and risk assets.",
        "emoji": "🧊",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "liquidity"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.53,
        "diagnostic_power": 0.84,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "QT impact is negligible",
        "right_choice": "Liquidity regime matters",
        "left_lesson": "Fun fact: Liquidity withdrawal can amplify volatility during earnings or macro shocks.",
        "right_lesson": "Fun fact: Balance-sheet policy interacts with fiscal issuance and private demand.",
        "card_band_color": "red",
        "alpha": 1.0,
        "weights": {"sentiment": -0.08, "inflation": -0.02, "greed": -0.05, "volatility": 0.2, "fundamentals": 0.05},
    },
    {
        "card_id": "MEV_E_009",
        "type": "education",
        "title": "Fiscal Deficit Pulse",
        "body": "Government deficits can support demand short term, but also affect issuance, rates, and long-run debt sustainability.",
        "emoji": "🏛️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "fiscal_policy"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.82,
        "base_priority": 1.08,
        "cooldown": 7,
        "left_choice": "Deficits are always bullish",
        "right_choice": "Assess horizon and cost",
        "left_lesson": "Fun fact: Fiscal impulse and debt-servicing burden can move in opposite directions over time.",
        "right_lesson": "Fun fact: Market impact depends on growth, inflation, and funding conditions together.",
        "card_band_color": "amber",
        "alpha": 0.97,
        "weights": {"sentiment": 0.06, "inflation": 0.14, "greed": 0.04, "volatility": 0.09, "fundamentals": 0.1},
    },
    {
        "card_id": "MEV_E_010",
        "type": "education",
        "title": "Geopolitical Risk Premium",
        "body": "Conflict and sanctions can affect commodities, shipping, and confidence, raising uncertainty premiums across markets.",
        "emoji": "🌍",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "geopolitics"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.45,
        "diagnostic_power": 0.78,
        "base_priority": 1.06,
        "cooldown": 6,
        "left_choice": "Treat as short headline",
        "right_choice": "Map second-order effects",
        "left_lesson": "Fun fact: Energy and transport channels often transmit geopolitical shocks into inflation.",
        "right_lesson": "Fun fact: Second-order impacts can outlast initial headlines by quarters.",
        "card_band_color": "red",
        "alpha": 0.94,
        "weights": {"sentiment": -0.14, "inflation": 0.2, "greed": -0.03, "volatility": 0.22, "fundamentals": -0.05},
    },
    {
        "card_id": "MEV_E_011",
        "type": "education",
        "title": "Oil Price Transmission",
        "body": "Oil shocks can pass through to transport, manufacturing, and consumer inflation, altering policy expectations.",
        "emoji": "🛢️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "commodities"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.44,
        "diagnostic_power": 0.77,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Oil affects energy only",
        "right_choice": "Watch broad pass-through",
        "left_lesson": "Fun fact: Commodity shocks can affect inflation expectations faster than realized CPI.",
        "right_lesson": "Fun fact: Energy-sensitive sectors may diverge sharply during oil volatility.",
        "card_band_color": "amber",
        "alpha": 0.91,
        "weights": {"sentiment": -0.04, "inflation": 0.28, "greed": 0.02, "volatility": 0.14, "fundamentals": 0.04},
    },
    {
        "card_id": "MEV_E_012",
        "type": "education",
        "title": "Credit Spread Thermometer",
        "body": "Widening corporate credit spreads usually signal rising default risk and tighter financial conditions.",
        "emoji": "🌡️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "credit"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.83,
        "base_priority": 1.09,
        "cooldown": 7,
        "left_choice": "Ignore credit markets",
        "right_choice": "Use spread signals",
        "left_lesson": "Fun fact: Credit often weakens before equity indexes fully price recession risk.",
        "right_lesson": "Fun fact: Spread tightening can confirm risk-on rebounds after panic phases.",
        "card_band_color": "red",
        "alpha": 0.98,
        "weights": {"sentiment": -0.08, "inflation": 0.0, "greed": -0.06, "volatility": 0.19, "fundamentals": 0.08},
    },
    {
        "card_id": "MEV_E_013",
        "type": "education",
        "title": "Earnings Revision Cycle",
        "body": "Analyst earnings revisions often follow macro momentum. Direction and breadth of revisions influence market leadership.",
        "emoji": "✍️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "information_flow"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.43,
        "diagnostic_power": 0.76,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Use static estimates",
        "right_choice": "Track revision breadth",
        "left_lesson": "Fun fact: Multi-sector downward revisions can pressure index returns even with stable rates.",
        "right_lesson": "Fun fact: Positive revision breadth tends to support cyclical outperformance.",
        "card_band_color": "steel_blue",
        "alpha": 0.89,
        "weights": {"sentiment": 0.09, "inflation": 0.0, "greed": 0.03, "volatility": 0.06, "fundamentals": 0.2},
    },
    {
        "card_id": "MEV_E_014",
        "type": "education",
        "title": "Nowcasting Limitations",
        "body": "High-frequency nowcasting models update quickly but can overreact to noisy data and revisions.",
        "emoji": "📡",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "information_flow"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.48,
        "diagnostic_power": 0.79,
        "base_priority": 1.04,
        "cooldown": 6,
        "left_choice": "Trust single nowcast",
        "right_choice": "Blend multiple signals",
        "left_lesson": "Fun fact: Economic data revisions can materially change initial growth readings.",
        "right_lesson": "Fun fact: Combining survey and hard data often improves robustness.",
        "card_band_color": "purple",
        "alpha": 0.9,
        "weights": {"sentiment": 0.02, "inflation": 0.0, "greed": -0.02, "volatility": 0.08, "fundamentals": 0.15},
    },
    {
        "card_id": "MEV_V_001",
        "type": "event",
        "title": "Hot CPI Print",
        "body": "Monthly CPI prints {value}% above consensus and core services remain sticky.",
        "emoji": "🔥",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "inflation_data"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.54,
        "diagnostic_power": 0.85,
        "base_priority": 1.14,
        "cooldown": 5,
        "left_choice": "Treat as one-month blip",
        "right_choice": "Reprice rates path",
        "left_lesson": "Fun fact: Sticky inflation can shift terminal-rate expectations abruptly.",
        "right_lesson": "Fun fact: Inflation surprises often hit long-duration assets hardest.",
        "card_band_color": "red",
        "value_min": 0.1,
        "value_max": 1.0,
        "value_step": 0.1,
        "alpha": 1.08,
        "weights": {"sentiment": -0.2, "inflation": 0.45, "greed": -0.08, "volatility": 0.3, "fundamentals": -0.06},
    },
    {
        "card_id": "MEV_V_002",
        "type": "event",
        "title": "Cool CPI Surprise",
        "body": "CPI comes in {value}% below consensus, improving odds of policy easing later in the year.",
        "emoji": "🧊",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "inflation_data"],
        "linked_traits": ["risk_appetite", "fomo_sensitivity"],
        "difficulty": 0.5,
        "diagnostic_power": 0.82,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Assume instant pivot",
        "right_choice": "Wait for trend confirmation",
        "left_lesson": "Fun fact: One soft print rarely determines policy without broader confirmation.",
        "right_lesson": "Fun fact: Disinflation trends can still support risk assets if growth holds.",
        "card_band_color": "green",
        "value_min": 0.1,
        "value_max": 1.0,
        "value_step": 0.1,
        "alpha": 1.03,
        "weights": {"sentiment": 0.2, "inflation": -0.35, "greed": 0.08, "volatility": -0.08, "fundamentals": 0.08},
    },
    {
        "card_id": "MEV_V_003",
        "type": "event",
        "title": "Payroll Shock",
        "body": "Non-farm payrolls miss by {value}k and prior months are revised lower.",
        "emoji": "👷",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "labor_market"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.51,
        "diagnostic_power": 0.82,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Ignore revisions",
        "right_choice": "Update growth scenario",
        "left_lesson": "Fun fact: Revisions can materially change the labor narrative after initial release.",
        "right_lesson": "Fun fact: Labor deterioration can lead earnings downgrades if persistent.",
        "card_band_color": "amber",
        "value_min": 50.0,
        "value_max": 400.0,
        "value_step": 50.0,
        "alpha": 1.04,
        "weights": {"sentiment": -0.14, "inflation": -0.04, "greed": -0.06, "volatility": 0.22, "fundamentals": -0.12},
    },
    {
        "card_id": "MEV_V_004",
        "type": "event",
        "title": "PMI Drops Below 50",
        "body": "Manufacturing PMI prints {value}, signaling contraction territory for the first time this cycle.",
        "emoji": "🏭",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "growth_data"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.49,
        "diagnostic_power": 0.79,
        "base_priority": 1.07,
        "cooldown": 5,
        "left_choice": "Assume full recession now",
        "right_choice": "Track breadth and duration",
        "left_lesson": "Fun fact: One sub-50 print can be noisy; persistence matters for regime calls.",
        "right_lesson": "Fun fact: Cross-checking with services and orders improves interpretation.",
        "card_band_color": "red",
        "value_min": 45.0,
        "value_max": 49.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.12, "inflation": -0.02, "greed": -0.04, "volatility": 0.18, "fundamentals": -0.1},
    },
    {
        "card_id": "MEV_V_005",
        "type": "event",
        "title": "Policy Rate Hike",
        "body": "Central bank raises rates by {value} bps and signals data dependence going forward.",
        "emoji": "⬆️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "central_bank"],
        "linked_traits": ["fomo_sensitivity", "loss_aversion"],
        "difficulty": 0.52,
        "diagnostic_power": 0.83,
        "base_priority": 1.12,
        "cooldown": 5,
        "left_choice": "Buy risk aggressively",
        "right_choice": "Respect tighter policy",
        "left_lesson": "Fun fact: Tightening cycles can pressure valuations before earnings reflect slower demand.",
        "right_lesson": "Fun fact: Financial conditions often tighten beyond the policy rate itself.",
        "card_band_color": "red",
        "value_min": 25.0,
        "value_max": 100.0,
        "value_step": 25.0,
        "alpha": 1.08,
        "weights": {"sentiment": -0.16, "inflation": -0.15, "greed": -0.08, "volatility": 0.24, "fundamentals": -0.05},
    },
    {
        "card_id": "MEV_V_006",
        "type": "event",
        "title": "Dovish Pivot Hint",
        "body": "Chair remarks suggest cuts are possible within {value} meetings if disinflation continues.",
        "emoji": "🕊️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "central_bank"],
        "linked_traits": ["risk_appetite", "fomo_sensitivity"],
        "difficulty": 0.5,
        "diagnostic_power": 0.81,
        "base_priority": 1.09,
        "cooldown": 5,
        "left_choice": "Assume guaranteed cuts",
        "right_choice": "Price conditional path",
        "left_lesson": "Fun fact: Conditional guidance can reverse quickly if data changes.",
        "right_lesson": "Fun fact: Policy expectations trade as probabilities, not certainties.",
        "card_band_color": "green",
        "value_min": 1.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 1.01,
        "weights": {"sentiment": 0.18, "inflation": -0.08, "greed": 0.1, "volatility": -0.04, "fundamentals": 0.08},
    },
    {
        "card_id": "MEV_V_007",
        "type": "event",
        "title": "Yield Curve Steepening",
        "body": "2s10s spread steepens by {value} bps in a week as growth expectations rebound.",
        "emoji": "📈",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "rates"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.49,
        "diagnostic_power": 0.79,
        "base_priority": 1.05,
        "cooldown": 5,
        "left_choice": "Assume risk-off signal",
        "right_choice": "Identify steepening driver",
        "left_lesson": "Fun fact: Steepening can be bullish or bearish depending on long-end vs short-end move.",
        "right_lesson": "Fun fact: Driver analysis matters more than direction alone.",
        "card_band_color": "steel_blue",
        "value_min": 10.0,
        "value_max": 80.0,
        "value_step": 10.0,
        "alpha": 0.97,
        "weights": {"sentiment": 0.08, "inflation": 0.02, "greed": 0.04, "volatility": 0.08, "fundamentals": 0.12},
    },
    {
        "card_id": "MEV_V_008",
        "type": "event",
        "title": "Credit Spreads Blow Out",
        "body": "High-yield spreads widen by {value} bps after weaker corporate guidance and liquidity concerns.",
        "emoji": "💥",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "credit"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.14,
        "cooldown": 5,
        "left_choice": "Ignore credit warning",
        "right_choice": "Reduce risk exposure",
        "left_lesson": "Fun fact: Sharp spread widening often precedes equity volatility spikes.",
        "right_lesson": "Fun fact: Credit conditions are a key transmission channel to real activity.",
        "card_band_color": "red",
        "value_min": 50.0,
        "value_max": 400.0,
        "value_step": 50.0,
        "alpha": 1.1,
        "weights": {"sentiment": -0.22, "inflation": 0.0, "greed": -0.08, "volatility": 0.32, "fundamentals": -0.12},
    },
    {
        "card_id": "MEV_V_009",
        "type": "event",
        "title": "Oil Shock",
        "body": "Brent crude jumps {value}% after supply disruption headlines in a major exporting region.",
        "emoji": "🛢️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "commodities"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.52,
        "diagnostic_power": 0.82,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Chase commodity spike",
        "right_choice": "Reassess inflation risk",
        "left_lesson": "Fun fact: Commodity spikes can reverse quickly when supply normalizes.",
        "right_lesson": "Fun fact: Persistent energy shocks can delay policy easing cycles.",
        "card_band_color": "amber",
        "value_min": 5.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 1.06,
        "weights": {"sentiment": -0.08, "inflation": 0.32, "greed": 0.05, "volatility": 0.24, "fundamentals": -0.02},
    },
    {
        "card_id": "MEV_V_010",
        "type": "event",
        "title": "Budget Deficit Surprise",
        "body": "Fiscal update projects deficit {value}% larger than expected, lifting long-end issuance needs.",
        "emoji": "🧮",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "fiscal_policy"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.07,
        "cooldown": 5,
        "left_choice": "Ignore issuance pressure",
        "right_choice": "Adjust duration assumptions",
        "left_lesson": "Fun fact: Supply-demand imbalances can move term premium even without policy changes.",
        "right_lesson": "Fun fact: Deficit trajectories influence both rates and currency expectations.",
        "card_band_color": "amber",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 1.02,
        "weights": {"sentiment": -0.05, "inflation": 0.12, "greed": 0.03, "volatility": 0.14, "fundamentals": -0.03},
    },
    {
        "card_id": "MEV_V_011",
        "type": "event",
        "title": "Sanctions Escalation",
        "body": "New sanctions package targets key export channels, increasing trade frictions and shipping delays.",
        "emoji": "🚢",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "geopolitics"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.08,
        "cooldown": 5,
        "left_choice": "Dismiss as local event",
        "right_choice": "Model supply-chain spillover",
        "left_lesson": "Fun fact: Trade restrictions can affect inflation and growth channels simultaneously.",
        "right_lesson": "Fun fact: Sector-level impacts can diverge sharply under geopolitical stress.",
        "card_band_color": "red",
        "alpha": 1.03,
        "weights": {"sentiment": -0.14, "inflation": 0.18, "greed": -0.02, "volatility": 0.25, "fundamentals": -0.06},
    },
    {
        "card_id": "MEV_V_012",
        "type": "event",
        "title": "Nowcast Growth Downgrade",
        "body": "Composite nowcast for quarterly GDP is cut by {value} percentage points after weak hard data.",
        "emoji": "📉",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "growth_data"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.48,
        "diagnostic_power": 0.78,
        "base_priority": 1.04,
        "cooldown": 5,
        "left_choice": "Ignore model downgrade",
        "right_choice": "Reduce cyclical exposure",
        "left_lesson": "Fun fact: Growth downgrades can trigger rapid sector rotation before broad index moves.",
        "right_lesson": "Fun fact: Incremental de-risking can be more effective than all-or-nothing shifts.",
        "card_band_color": "amber",
        "value_min": 0.2,
        "value_max": 2.0,
        "value_step": 0.2,
        "alpha": 0.98,
        "weights": {"sentiment": -0.1, "inflation": -0.03, "greed": -0.03, "volatility": 0.16, "fundamentals": -0.1},
    },
    {
        "card_id": "MEV_V_013",
        "type": "event",
        "title": "Earnings Revision Diffusion Falls",
        "body": "Revision breadth index drops to {value}, showing downgrades are broadening across sectors.",
        "emoji": "📚",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "information_flow"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.47,
        "diagnostic_power": 0.77,
        "base_priority": 1.03,
        "cooldown": 5,
        "left_choice": "Follow price momentum only",
        "right_choice": "Respect revision breadth",
        "left_lesson": "Fun fact: Weak revision breadth often narrows leadership and raises fragility.",
        "right_lesson": "Fun fact: Positive breadth turn can help validate risk re-entry.",
        "card_band_color": "purple",
        "value_min": 20.0,
        "value_max": 50.0,
        "value_step": 5.0,
        "alpha": 0.95,
        "weights": {"sentiment": -0.06, "inflation": 0.0, "greed": -0.02, "volatility": 0.12, "fundamentals": -0.06},
    },
    {
        "card_id": "MEV_A_001",
        "type": "action",
        "title": "Create a Macro Calendar",
        "body": "Build a recurring calendar for CPI, payrolls, PMI, and policy meetings for the next {value} months.",
        "emoji": "🗓️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "process"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.38,
        "diagnostic_power": 0.73,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "React ad hoc to news",
        "right_choice": "Prepare event schedule",
        "left_lesson": "Fun fact: Ad hoc monitoring increases surprise-driven decisions.",
        "right_lesson": "Fun fact: Structured calendars reduce emotional trading around high-volatility releases.",
        "card_band_color": "green",
        "value_min": 3.0,
        "value_max": 12.0,
        "value_step": 1.0,
        "alpha": 0.84,
        "weights": {"sentiment": 0.01, "inflation": 0.0, "greed": -0.08, "volatility": -0.08, "fundamentals": 0.1},
    },
    {
        "card_id": "MEV_A_002",
        "type": "action",
        "title": "Define Data Surprise Threshold",
        "body": "Only rebalance when major macro data misses or beats by more than {value} standard deviations.",
        "emoji": "📏",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "information_flow"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.07,
        "cooldown": 6,
        "left_choice": "Trade every data print",
        "right_choice": "Use surprise filter",
        "left_lesson": "Fun fact: Overreacting to noise increases turnover and slippage.",
        "right_lesson": "Fun fact: Threshold rules can improve signal-to-noise in macro-driven strategies.",
        "card_band_color": "steel_blue",
        "value_min": 0.5,
        "value_max": 2.0,
        "value_step": 0.5,
        "alpha": 0.93,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.09, "volatility": -0.05, "fundamentals": 0.14},
    },
    {
        "card_id": "MEV_A_003",
        "type": "action",
        "title": "Shorten Duration on Sticky Inflation",
        "body": "Reduce long-duration bond exposure by {value}% when core inflation exceeds your target band.",
        "emoji": "✂️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "rates"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.53,
        "diagnostic_power": 0.83,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Keep long duration unchanged",
        "right_choice": "Trim duration risk",
        "left_lesson": "Fun fact: Duration risk can dominate returns during inflation uncertainty.",
        "right_lesson": "Fun fact: Active duration management can reduce macro drawdowns.",
        "card_band_color": "amber",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 0.99,
        "weights": {"sentiment": -0.02, "inflation": -0.06, "greed": -0.03, "volatility": -0.06, "fundamentals": 0.12},
    },
    {
        "card_id": "MEV_A_004",
        "type": "action",
        "title": "Add Defensive Tilt",
        "body": "Increase defensive-sector weight by {value}% when growth momentum and revision breadth both weaken.",
        "emoji": "🛡️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "growth_data"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.47,
        "diagnostic_power": 0.78,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Stay fully cyclical",
        "right_choice": "Rotate toward defensives",
        "left_lesson": "Fun fact: Defensive tilts can soften drawdowns during earnings downgrades.",
        "right_lesson": "Fun fact: Rotation rules work best when tied to objective indicators.",
        "card_band_color": "green",
        "value_min": 5.0,
        "value_max": 25.0,
        "value_step": 5.0,
        "alpha": 0.91,
        "weights": {"sentiment": -0.01, "inflation": 0.0, "greed": -0.05, "volatility": -0.08, "fundamentals": 0.1},
    },
    {
        "card_id": "MEV_A_005",
        "type": "action",
        "title": "Cap Event-Day Risk",
        "body": "On major release days, cut gross risk by {value}% until post-data volatility normalizes.",
        "emoji": "🚦",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "risk_management"],
        "linked_traits": ["fomo_sensitivity", "loss_aversion"],
        "difficulty": 0.44,
        "diagnostic_power": 0.74,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "Keep full risk through release",
        "right_choice": "Use event-day limits",
        "left_lesson": "Fun fact: Slippage and spread widening can spike during data-release windows.",
        "right_lesson": "Fun fact: Event-specific sizing rules can reduce tail losses.",
        "card_band_color": "amber",
        "value_min": 5.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 0.88,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.08, "volatility": -0.1, "fundamentals": 0.08},
    },
    {
        "card_id": "MEV_A_006",
        "type": "action",
        "title": "Cross-Asset Confirmation Rule",
        "body": "Require confirmation from at least {value} asset classes before treating a macro move as durable.",
        "emoji": "🔍",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "information_flow"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.81,
        "base_priority": 1.06,
        "cooldown": 6,
        "left_choice": "Trade single-market signal",
        "right_choice": "Wait for confirmation",
        "left_lesson": "Fun fact: Single-asset moves can reflect positioning squeezes rather than macro shifts.",
        "right_lesson": "Fun fact: Cross-asset confirmation often reduces false-positive signals.",
        "card_band_color": "steel_blue",
        "value_min": 2.0,
        "value_max": 4.0,
        "value_step": 1.0,
        "alpha": 0.94,
        "weights": {"sentiment": 0.01, "inflation": 0.0, "greed": -0.05, "volatility": -0.06, "fundamentals": 0.13},
    },
    {
        "card_id": "MEV_A_007",
        "type": "action",
        "title": "Set Inflation Breakeven Trigger",
        "body": "If 5y5y inflation breakeven rises above {value}%, reduce exposure to inflation-sensitive duration assets.",
        "emoji": "📍",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "inflation_data"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.51,
        "diagnostic_power": 0.82,
        "base_priority": 1.07,
        "cooldown": 5,
        "left_choice": "Ignore breakeven signals",
        "right_choice": "Use inflation trigger",
        "left_lesson": "Fun fact: Inflation expectations can move valuations before realized inflation changes.",
        "right_lesson": "Fun fact: Trigger-based rules reduce discretionary hesitation.",
        "card_band_color": "red",
        "value_min": 2.0,
        "value_max": 4.0,
        "value_step": 0.5,
        "alpha": 0.97,
        "weights": {"sentiment": -0.02, "inflation": -0.04, "greed": -0.02, "volatility": -0.05, "fundamentals": 0.12},
    },
    {
        "card_id": "MEV_A_008",
        "type": "action",
        "title": "Hedge Commodity Exposure",
        "body": "When energy volatility exceeds your limit, hedge {value}% of commodity-sensitive holdings.",
        "emoji": "🧯",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "commodities"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.52,
        "diagnostic_power": 0.8,
        "base_priority": 1.05,
        "cooldown": 5,
        "left_choice": "Stay unhedged",
        "right_choice": "Hedge systematic risk",
        "left_lesson": "Fun fact: Commodity shocks can transmit quickly through margins and inflation expectations.",
        "right_lesson": "Fun fact: Partial hedging can lower variance without fully muting upside.",
        "card_band_color": "amber",
        "value_min": 10.0,
        "value_max": 60.0,
        "value_step": 10.0,
        "alpha": 0.96,
        "weights": {"sentiment": -0.01, "inflation": -0.03, "greed": -0.02, "volatility": -0.08, "fundamentals": 0.1},
    },
    {
        "card_id": "MEV_A_009",
        "type": "action",
        "title": "Pause After Major Geopolitical Shock",
        "body": "Freeze new directional risk for {value} trading days after a major geopolitical escalation.",
        "emoji": "⏸️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "geopolitics"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.76,
        "base_priority": 1.02,
        "cooldown": 6,
        "left_choice": "Trade immediately on headlines",
        "right_choice": "Wait for price discovery",
        "left_lesson": "Fun fact: Initial shock moves often include liquidity gaps and exaggerated spreads.",
        "right_lesson": "Fun fact: Waiting briefly can improve execution and information quality.",
        "card_band_color": "red",
        "value_min": 1.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 0.9,
        "weights": {"sentiment": -0.03, "inflation": 0.0, "greed": -0.08, "volatility": -0.09, "fundamentals": 0.07},
    },
    {
        "card_id": "MEV_A_010",
        "type": "action",
        "title": "Use Revision Breadth Dashboard",
        "body": "Allocate risk by earnings revision breadth percentile, adding when above {value}th percentile.",
        "emoji": "📚",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "information_flow"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.46,
        "diagnostic_power": 0.77,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Ignore revision breadth",
        "right_choice": "Tie risk to breadth",
        "left_lesson": "Fun fact: Breadth-aware allocation can reduce concentration in fragile rallies.",
        "right_lesson": "Fun fact: Diffusion-based rules capture participation, not just index level.",
        "card_band_color": "green",
        "value_min": 50.0,
        "value_max": 80.0,
        "value_step": 5.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.04, "inflation": 0.0, "greed": -0.02, "volatility": -0.07, "fundamentals": 0.11},
    },
    {
        "card_id": "MEV_A_011",
        "type": "action",
        "title": "Set Maximum Policy-Meeting Exposure",
        "body": "Limit gross exposure to {value}% of normal size into central-bank decision hours.",
        "emoji": "🎛️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "central_bank"],
        "linked_traits": ["fomo_sensitivity", "loss_aversion"],
        "difficulty": 0.44,
        "diagnostic_power": 0.74,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "Run full size into event",
        "right_choice": "Scale risk before decision",
        "left_lesson": "Fun fact: Policy-day whipsaws can trigger avoidable stop-outs.",
        "right_lesson": "Fun fact: Pre-event sizing discipline improves survival through uncertainty spikes.",
        "card_band_color": "amber",
        "value_min": 30.0,
        "value_max": 90.0,
        "value_step": 10.0,
        "alpha": 0.87,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.07, "volatility": -0.1, "fundamentals": 0.06},
    },
    {
        "card_id": "MEV_A_012",
        "type": "action",
        "title": "Rebalance by Regime Score",
        "body": "Use a composite macro regime score and rebalance when it shifts by at least {value} points.",
        "emoji": "🔄",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["macro_events", "process"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.52,
        "diagnostic_power": 0.82,
        "base_priority": 1.08,
        "cooldown": 5,
        "left_choice": "Use discretionary gut feel",
        "right_choice": "Use regime trigger",
        "left_lesson": "Fun fact: Regime frameworks reduce narrative drift in portfolio decisions.",
        "right_lesson": "Fun fact: Trigger-based rebalancing can align risk with changing macro conditions.",
        "card_band_color": "steel_blue",
        "value_min": 10.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.01, "inflation": 0.0, "greed": -0.05, "volatility": -0.06, "fundamentals": 0.14},
    },
    {
        "card_id": "MEV_A_013",
        "type": "action",
        "title": "Weekly Macro Debrief",
        "body": "Run a weekly debrief and grade each macro thesis for confidence and risk asymmetry on a {value}-point scale.",
        "emoji": "📝",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["macro_events", "process"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.4,
        "diagnostic_power": 0.72,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "Skip structured review",
        "right_choice": "Maintain weekly discipline",
        "left_lesson": "Fun fact: Memory-based decision logs are often distorted by recency bias.",
        "right_lesson": "Fun fact: Regular review loops improve calibration over time.",
        "card_band_color": "green",
        "value_min": 5.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 0.85,
        "weights": {"sentiment": 0.02, "inflation": 0.0, "greed": -0.06, "volatility": -0.08, "fundamentals": 0.1},
    },
]
