"""50 seed cards across all 5 stages and 3 card types."""

SEED_CARDS = [
    # ─── EDUCATION CARDS (15) ─────────────────────────────────────────────────
    {
        "type": "education",
        "title": "What Is Compound Interest?",
        "body": "Your money can earn returns, and those returns can earn returns. Over decades, this creates exponential growth — the foundation of all long-term investing.",
        "emoji": "📈",
        "stage_min": 1, "stage_max": 2,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["patience"],
        "difficulty": 0.2, "diagnostic_power": 0.6,
        "base_priority": 1.2, "cooldown": 8,
        "left_choice": "Skip — I know this",
        "right_choice": "Show me an example",
        "left_lesson": "Compound interest underpins every long-term investment strategy. Even if you know the concept, revisiting it keeps you grounded.",
        "right_lesson": "$10,000 at 7% annually becomes $76,000 in 30 years — without adding a single dollar. Time is your greatest asset.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "education",
        "title": "Risk vs. Return",
        "body": "Higher potential returns almost always come with higher risk. Understanding this trade-off is the first principle every investor must internalize.",
        "emoji": "⚖️",
        "stage_min": 1, "stage_max": 2,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["risk_appetite"],
        "difficulty": 0.25, "diagnostic_power": 0.75,
        "base_priority": 1.3, "cooldown": 8,
        "left_choice": "I prefer low risk",
        "right_choice": "I want high returns",
        "left_lesson": "Conservative investing protects capital. Treasury bonds yield 4-5% with near-zero default risk. Slow and steady wins for many.",
        "right_lesson": "Equities historically return ~10%/year, but can drop 30-50% in crashes. High returns demand emotional resilience.",
        "card_band_color": "amber",
    },
    {
        "type": "education",
        "title": "What Is Diversification?",
        "body": "Spreading investments across asset classes, sectors, and geographies reduces the impact of any single loss on your total portfolio.",
        "emoji": "🧩",
        "stage_min": 1, "stage_max": 3,
        "topics": ["stocks", "bonds", "real_estate"],
        "linked_traits": ["diversification_bias"],
        "difficulty": 0.3, "diagnostic_power": 0.7,
        "base_priority": 1.1, "cooldown": 6,
        "left_choice": "Concentrate in winners",
        "right_choice": "Spread across assets",
        "left_lesson": "Concentration amplifies both gains and losses. When you're right, you win big — but the downside can be catastrophic.",
        "right_lesson": "A diversified portfolio reduces volatility without proportionally reducing returns. Correlation matters as much as allocation.",
        "card_band_color": "green",
    },
    {
        "type": "education",
        "title": "The Power of Dollar-Cost Averaging",
        "body": "Investing a fixed amount at regular intervals — regardless of price — smooths out the impact of volatility and removes the pressure to time the market.",
        "emoji": "🔄",
        "stage_min": 1, "stage_max": 3,
        "topics": ["stocks"],
        "linked_traits": ["patience", "fomo_sensitivity"],
        "difficulty": 0.3, "diagnostic_power": 0.65,
        "base_priority": 1.0, "cooldown": 7,
        "left_choice": "Wait for the dip",
        "right_choice": "Invest consistently",
        "left_lesson": "Market timing studies show even professional investors fail consistently. Waiting for 'the dip' often means missing the rally.",
        "right_lesson": "DCA investors bought at every point in the 2008 crash — and came out ahead by 2012. Consistency beats precision.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "education",
        "title": "Understanding P/E Ratios",
        "body": "The Price-to-Earnings ratio tells you how much investors pay per dollar of earnings. A high P/E suggests growth expectations; a low P/E suggests undervaluation or risk.",
        "emoji": "🔢",
        "stage_min": 2, "stage_max": 4,
        "topics": ["stocks"],
        "linked_traits": ["overconfidence", "risk_appetite"],
        "difficulty": 0.5, "diagnostic_power": 0.7,
        "base_priority": 1.0, "cooldown": 6,
        "left_choice": "Low P/E is always better",
        "right_choice": "P/E depends on context",
        "left_lesson": "Low P/E can signal a value trap — a company cheap for good reason. Always investigate why before buying.",
        "right_lesson": "Tesla traded at 1000x P/E at its peak. Valuation depends on growth trajectory, sector norms, and interest rates.",
        "card_band_color": "amber",
    },
    {
        "type": "education",
        "title": "Bonds vs. Equities",
        "body": "Bonds offer fixed income with lower volatility. Equities offer growth potential with higher risk. Most portfolios hold both in a ratio reflecting their risk tolerance.",
        "emoji": "📊",
        "stage_min": 2, "stage_max": 4,
        "topics": ["bonds", "stocks"],
        "linked_traits": ["risk_appetite", "diversification_bias"],
        "difficulty": 0.45, "diagnostic_power": 0.65,
        "base_priority": 1.0, "cooldown": 6,
        "left_choice": "100% bonds — safety first",
        "right_choice": "60/40 balanced portfolio",
        "left_lesson": "A 100% bond portfolio often underperforms inflation over 30 years. Safety has an opportunity cost.",
        "right_lesson": "The classic 60/40 portfolio returned ~8.5% annually for decades. Balance is a proven strategy, not a compromise.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "education",
        "title": "What Are Index Funds?",
        "body": "An index fund tracks a market index like the S&P 500. Low fees, instant diversification, and consistent market-rate returns make them the default recommendation for most investors.",
        "emoji": "📦",
        "stage_min": 1, "stage_max": 3,
        "topics": ["stocks"],
        "linked_traits": ["patience", "diversification_bias"],
        "difficulty": 0.25, "diagnostic_power": 0.6,
        "base_priority": 1.1, "cooldown": 7,
        "left_choice": "I'll pick individual stocks",
        "right_choice": "Index funds work for me",
        "left_lesson": "Research shows 80%+ of active fund managers underperform the S&P 500 index over 15 years after fees.",
        "right_lesson": "Vanguard's S&P 500 index fund charges 0.03% annually. That's $3 per $10,000 invested — nearly all returns stay with you.",
        "card_band_color": "green",
    },
    {
        "type": "education",
        "title": "Understanding Options",
        "body": "Options give you the right — not the obligation — to buy or sell an asset at a set price before a date. Powerful for hedging or speculation, but can expire worthless.",
        "emoji": "🎯",
        "stage_min": 3, "stage_max": 5,
        "topics": ["derivatives"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.75, "diagnostic_power": 0.8,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Too complex, skip options",
        "right_choice": "I want to learn options",
        "left_lesson": "Most retail options traders lose money. Until you understand Greeks, volatility surfaces, and time decay, caution is wise.",
        "right_lesson": "A covered call strategy can generate 1-3% monthly income on stocks you already own — low-risk options usage.",
        "card_band_color": "red",
    },
    {
        "type": "education",
        "title": "Inflation and Real Returns",
        "body": "Nominal returns look good on paper, but inflation erodes purchasing power. A 7% return during 4% inflation is really a 3% real gain.",
        "emoji": "💸",
        "stage_min": 2, "stage_max": 4,
        "topics": ["bonds", "real_estate"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.4, "diagnostic_power": 0.65,
        "base_priority": 1.0, "cooldown": 6,
        "left_choice": "Nominal returns are fine",
        "right_choice": "Always adjust for inflation",
        "left_lesson": "Investors who ignore inflation often discover their 'savings' buy less over time. Cash in a savings account loses real value annually.",
        "right_lesson": "TIPS (Treasury Inflation-Protected Securities) and real estate historically preserve purchasing power better than nominal bonds.",
        "card_band_color": "amber",
    },
    {
        "type": "education",
        "title": "Tax-Advantaged Accounts",
        "body": "401(k)s and IRAs defer or eliminate taxes on investment gains. Using them maximally before taxable accounts can add hundreds of thousands in retirement wealth.",
        "emoji": "🏦",
        "stage_min": 1, "stage_max": 3,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["patience"],
        "difficulty": 0.35, "diagnostic_power": 0.6,
        "base_priority": 1.1, "cooldown": 7,
        "left_choice": "Invest in taxable account",
        "right_choice": "Max out tax-advantaged first",
        "left_lesson": "Taxable accounts offer flexibility but every dividend and capital gain is a taxable event. The drag compounds over decades.",
        "right_lesson": "A $6,000 IRA contribution growing at 7% for 30 years tax-free creates ~$45,000. The tax savings alone are worth thousands.",
        "card_band_color": "green",
    },
    {
        "type": "education",
        "title": "Short Selling Explained",
        "body": "Short selling means borrowing shares to sell now, hoping to buy them back cheaper later. It can profit from declines but carries unlimited loss potential.",
        "emoji": "📉",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks", "derivatives"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.7, "diagnostic_power": 0.75,
        "base_priority": 0.9, "cooldown": 5,
        "left_choice": "Never short — too risky",
        "right_choice": "Shorting is a valid strategy",
        "left_lesson": "The 2021 GameStop squeeze destroyed many short sellers. A stock can rise 1000%+ before you can cover — losses are truly unlimited.",
        "right_lesson": "Institutional short sellers provide price discovery and can identify fraudulent companies early. It's a tool, not just speculation.",
        "card_band_color": "red",
    },
    {
        "type": "education",
        "title": "Crypto as an Asset Class",
        "body": "Cryptocurrencies offer high potential returns but extreme volatility. Bitcoin has dropped 80%+ multiple times. Allocation should reflect risk tolerance, not FOMO.",
        "emoji": "₿",
        "stage_min": 2, "stage_max": 5,
        "topics": ["crypto"],
        "linked_traits": ["risk_appetite", "fomo_sensitivity", "overconfidence"],
        "difficulty": 0.55, "diagnostic_power": 0.8,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Crypto is speculative noise",
        "right_choice": "5% allocation makes sense",
        "left_lesson": "Critics who dismissed Bitcoin at $100 may regret it. Even skeptics acknowledge blockchain as a structural shift in finance.",
        "right_lesson": "Kelly criterion suggests no more than 1-5% in highly volatile assets. FOMO-driven crypto allocations frequently destroy portfolios.",
        "card_band_color": "purple",
    },
    {
        "type": "education",
        "title": "The Efficient Market Hypothesis",
        "body": "EMH claims stock prices reflect all available information, making consistent alpha-generation impossible. Evidence is mixed — markets are mostly efficient, except when they're not.",
        "emoji": "🔬",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.65, "diagnostic_power": 0.7,
        "base_priority": 0.9, "cooldown": 6,
        "left_choice": "I can beat the market",
        "right_choice": "Accept market returns",
        "left_lesson": "Survivorship bias inflates success stories. For every Buffett, thousands of equally skilled analysts earned market returns or less.",
        "right_lesson": "Even Buffett advises most investors: buy S&P 500 index funds. Accepting market returns is a decision, not a defeat.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "education",
        "title": "Real Estate as Investment",
        "body": "Real estate provides income through rent and appreciation through property value increases. Leverage amplifies both gains and losses — a mortgage is a risk multiplier.",
        "emoji": "🏠",
        "stage_min": 2, "stage_max": 4,
        "topics": ["real_estate"],
        "linked_traits": ["diversification_bias", "loss_aversion"],
        "difficulty": 0.5, "diagnostic_power": 0.65,
        "base_priority": 1.0, "cooldown": 6,
        "left_choice": "Stocks are more liquid",
        "right_choice": "Real estate has unique advantages",
        "left_lesson": "Illiquidity in real estate can trap capital. During 2008-2012, many leveraged real estate investors couldn't sell without massive losses.",
        "right_lesson": "Cap rates of 5-8% plus appreciation create compelling risk-adjusted returns. REITs offer real estate exposure without the illiquidity.",
        "card_band_color": "green",
    },
    {
        "type": "education",
        "title": "Behavioral Finance: Cognitive Biases",
        "body": "Confirmation bias, loss aversion, and overconfidence systematically impair investment decisions. Understanding your psychological tendencies is as important as understanding markets.",
        "emoji": "🧠",
        "stage_min": 4, "stage_max": 5,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["loss_aversion", "overconfidence", "fomo_sensitivity"],
        "difficulty": 0.6, "diagnostic_power": 0.85,
        "base_priority": 1.1, "cooldown": 5,
        "left_choice": "I'm rational, not biased",
        "right_choice": "I study my own patterns",
        "left_lesson": "Every human has cognitive biases — believing you're immune is itself the Dunning-Kruger effect. Awareness is the first step.",
        "right_lesson": "Keeping a trade journal and reviewing past decisions with fresh eyes is one of the most effective tools in behavioral finance.",
        "card_band_color": "purple",
    },

    # ─── EVENT CARDS (20) ─────────────────────────────────────────────────────
    {
        "type": "event",
        "title": "Market Crash -35%",
        "body": "A global recession fear triggers a sudden 35% market decline. Your portfolio is down significantly. Panic or opportunity?",
        "emoji": "🔻",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.6, "diagnostic_power": 0.9,
        "base_priority": 1.2, "cooldown": 4,
        "left_choice": "Sell — cut losses now",
        "right_choice": "Hold — ride it out",
        "left_lesson": "Selling in a crash locks in losses permanently. The S&P 500 has recovered from every historical crash — patience is rewarded.",
        "right_lesson": "Every major crash in history became a buying opportunity in hindsight. Holding requires conviction but rarely punishes long-term investors.",
        "card_band_color": "red",
    },
    {
        "type": "event",
        "title": "Tech Sector Rally +20%",
        "body": "AI breakthroughs fuel a 20% surge in tech stocks. Your underweighted tech allocation missed the run. What do you do now?",
        "emoji": "🚀",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.5, "diagnostic_power": 0.85,
        "base_priority": 1.1, "cooldown": 4,
        "left_choice": "Chase the rally — buy in",
        "right_choice": "Stick to your allocation plan",
        "left_lesson": "Buying after a 20% run often means buying the top. FOMO-driven investing systematically buys high and sells low.",
        "right_lesson": "Missing a rally is painful but disciplined rebalancing — not chasing — is what compounds wealth over decades.",
        "card_band_color": "green",
    },
    {
        "type": "event",
        "title": "Fed Rate Hike Surprise",
        "body": "The Federal Reserve raises rates by 0.75% — higher than expected. Bond prices drop, growth stocks fall. How do you rebalance?",
        "emoji": "🏛️",
        "stage_min": 2, "stage_max": 5,
        "topics": ["bonds", "stocks"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.55, "diagnostic_power": 0.75,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Move to cash temporarily",
        "right_choice": "Rebalance toward value stocks",
        "left_lesson": "Moving to cash after a rate hike often means missing the subsequent recovery rally. Timing rate cycles is notoriously difficult.",
        "right_lesson": "Rate hike cycles historically favor value stocks and financials over growth. Tactical rebalancing — not panic — is the correct response.",
        "card_band_color": "amber",
    },
    {
        "type": "event",
        "title": "Inflation Surges to 8%",
        "body": "Inflation spikes to 8% — a 40-year high. Your fixed income holdings are losing real value every month. Adapt or hold?",
        "emoji": "🔥",
        "stage_min": 2, "stage_max": 5,
        "topics": ["bonds", "real_estate"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.55, "diagnostic_power": 0.7,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Keep bonds — stability matters",
        "right_choice": "Shift to inflation hedges",
        "left_lesson": "Holding nominal bonds during high inflation guarantees real losses. The 2022 bond market was one of the worst years in history.",
        "right_lesson": "TIPS, commodities, and real estate are classic inflation hedges. Adapting your allocation to macro conditions is sophisticated portfolio management.",
        "card_band_color": "red",
    },
    {
        "type": "event",
        "title": "Your Crypto Holding -60%",
        "body": "A major exchange collapse triggers a crypto winter. Your crypto position is down 60% in 3 weeks. Is this a crisis or a test?",
        "emoji": "❄️",
        "stage_min": 3, "stage_max": 5,
        "topics": ["crypto"],
        "linked_traits": ["loss_aversion", "risk_appetite", "fomo_sensitivity"],
        "difficulty": 0.7, "diagnostic_power": 0.9,
        "base_priority": 1.1, "cooldown": 4,
        "left_choice": "Sell — too much risk",
        "right_choice": "Hold or add if you believe",
        "left_lesson": "Cutting crypto losses at -60% may be rational if it was over-allocated. Position sizing rules exist precisely for this scenario.",
        "right_lesson": "Bitcoin recovered from -80% drawdowns multiple times. Conviction investing in high-risk assets requires pre-defined exit rules, not panic.",
        "card_band_color": "purple",
    },
    {
        "type": "event",
        "title": "Dream Job Offer — Relocate?",
        "body": "A top company offers you a role with 40% higher salary but requires relocating internationally. Your current investments and financial plan would need adjustment.",
        "emoji": "✈️",
        "stage_min": 2, "stage_max": 5,
        "topics": ["real_estate"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.45, "diagnostic_power": 0.6,
        "base_priority": 0.9, "cooldown": 6,
        "left_choice": "Stay — stability is valuable",
        "right_choice": "Take the opportunity",
        "left_lesson": "Human capital is your largest asset in early career. A 40% salary increase compounds your savings rate enormously over time.",
        "right_lesson": "International relocation introduces currency risk, tax complexity, and retirement account complications. Plan carefully before acting.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "event",
        "title": "IPO Frenzy: Hot New Startup",
        "body": "A tech unicorn you've followed for years just IPO'd. Shares are up 80% on day one. Your allocation policy says no individual stocks. Do you break the rules?",
        "emoji": "🦄",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["fomo_sensitivity", "overconfidence", "risk_appetite"],
        "difficulty": 0.6, "diagnostic_power": 0.85,
        "base_priority": 1.0, "cooldown": 4,
        "left_choice": "Buy — exceptional opportunity",
        "right_choice": "Skip — trust your system",
        "left_lesson": "IPO day pops often reverse within months. Over 60% of IPOs underperform market averages in the first year.",
        "right_lesson": "Your investment policy statement exists for exactly this moment. Emotion-driven exceptions compound into a broken system.",
        "card_band_color": "green",
    },
    {
        "type": "event",
        "title": "Emergency Fund Depleted",
        "body": "A medical emergency drains your 3-month emergency fund. Your portfolio is intact but you have no cash buffer. Rebuild cash or stay invested?",
        "emoji": "🏥",
        "stage_min": 1, "stage_max": 4,
        "topics": ["bonds"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.35, "diagnostic_power": 0.65,
        "base_priority": 1.0, "cooldown": 6,
        "left_choice": "Rebuild emergency fund first",
        "right_choice": "Stay invested, use credit if needed",
        "left_lesson": "Without an emergency fund, any unexpected expense forces you to sell investments at potentially bad times. Liquidity is a foundational priority.",
        "right_lesson": "While rebuilding your fund, a high-yield savings account or short-term bonds bridges the gap without disrupting your long-term allocation.",
        "card_band_color": "amber",
    },
    {
        "type": "event",
        "title": "Geopolitical Conflict: Oil Spike",
        "body": "A regional conflict sends oil prices up 40%. Energy stocks soar while consumer discretionary plummets. Markets are volatile.",
        "emoji": "⛽",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks", "real_estate"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.65, "diagnostic_power": 0.7,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Sell and wait out volatility",
        "right_choice": "Rebalance toward energy/commodities",
        "left_lesson": "Geopolitical events create short-term volatility but rarely change long-term fundamentals. Selling based on news is reactive, not strategic.",
        "right_lesson": "Tactical commodity exposure during supply shocks has historically generated alpha. Macro-aware investing isn't speculation — it's positioning.",
        "card_band_color": "red",
    },
    {
        "type": "event",
        "title": "Real Estate Boom in Your City",
        "body": "Property values in your city jumped 25% last year. A friend urges you to buy rental property using maximum leverage. Do you join the boom?",
        "emoji": "🏘️",
        "stage_min": 3, "stage_max": 5,
        "topics": ["real_estate"],
        "linked_traits": ["fomo_sensitivity", "overconfidence", "loss_aversion"],
        "difficulty": 0.6, "diagnostic_power": 0.75,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Buy now — prices keep rising",
        "right_choice": "Evaluate fundamentals first",
        "left_lesson": "Leveraged real estate at peak valuations magnifies losses dramatically. The 2007-2009 US housing crisis destroyed leveraged buyers.",
        "right_lesson": "Cap rates below mortgage rates create negative cash flow from day one. Evaluate rent yield, not just appreciation potential.",
        "card_band_color": "amber",
    },
    {
        "type": "event",
        "title": "Bear Market: Month 14",
        "body": "The bear market has now lasted 14 months. Analysts are split — some say capitulation is near, others predict another leg down. You're -28% from peak.",
        "emoji": "🐻",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["loss_aversion", "patience", "risk_appetite"],
        "difficulty": 0.7, "diagnostic_power": 0.9,
        "base_priority": 1.2, "cooldown": 4,
        "left_choice": "Reduce equity exposure now",
        "right_choice": "Continue regular contributions",
        "left_lesson": "Reducing equity at -28% locks in a large portion of losses. Bear markets create wealth for investors who stay the course.",
        "right_lesson": "Continuing DCA in a prolonged bear market means buying at progressively lower prices. Recovery makes these contributions disproportionately valuable.",
        "card_band_color": "red",
    },
    {
        "type": "event",
        "title": "Inheritance: Lump Sum Decision",
        "body": "You inherit $50,000 unexpectedly. Investing it all at once vs. dollar-cost averaging over 12 months is the classic debate. Studies are surprisingly clear.",
        "emoji": "💰",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["fomo_sensitivity", "loss_aversion", "patience"],
        "difficulty": 0.5, "diagnostic_power": 0.7,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "DCA over 12 months",
        "right_choice": "Invest lump sum immediately",
        "left_lesson": "DCA wins psychologically — smaller regret if markets drop. But statistically, it underperforms lump sum investing ~70% of the time.",
        "right_lesson": "Markets trend upward. Vanguard research shows lump sum beats DCA ~67% of the time over 10-year periods. But both beat not investing.",
        "card_band_color": "green",
    },
    {
        "type": "event",
        "title": "Startup Funding: Your Side Project",
        "body": "An angel investor offers to fund your side project, but wants 30% equity. Your financial advisor calls it 'unfavorable.' Your gut says take it.",
        "emoji": "💡",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.65, "diagnostic_power": 0.7,
        "base_priority": 0.9, "cooldown": 6,
        "left_choice": "Decline — 30% is too much to give",
        "right_choice": "Accept — momentum matters",
        "left_lesson": "Negotiating with leverage is important. Many successful founders gave away too much equity early and regretted it during acquisition.",
        "right_lesson": "Speed and validation often outweigh optimal terms. 70% of something growing is better than 100% of nothing.",
        "card_band_color": "purple",
    },
    {
        "type": "event",
        "title": "Social Media Trading Tip",
        "body": "A financial influencer with 2M followers is pumping a small-cap stock. It's already up 45% today. Comments are flooded with testimonials.",
        "emoji": "📱",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.5, "diagnostic_power": 0.85,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Join the momentum trade",
        "right_choice": "This is a pump-and-dump",
        "left_lesson": "Retail investors who buy in after a 45% same-day spike are typically the exit liquidity for early movers. Social media tips are rarely alpha.",
        "right_lesson": "Pump-and-dump schemes are illegal but common in small caps. The SEC has prosecuted hundreds of influencer-driven market manipulation cases.",
        "card_band_color": "red",
    },
    {
        "type": "event",
        "title": "Interest Rates Hit Zero",
        "body": "The Fed cuts rates to near zero to stimulate the economy. Your bonds yield almost nothing. Cash in savings earns 0.01%. How do you adapt?",
        "emoji": "0️⃣",
        "stage_min": 3, "stage_max": 5,
        "topics": ["bonds", "stocks", "real_estate"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.55, "diagnostic_power": 0.7,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Keep bonds — rates will normalize",
        "right_choice": "Shift toward dividend stocks/REITs",
        "left_lesson": "Waiting for rate normalization while earning 0.01% incurs massive opportunity cost. Japan's 30-year zero-rate period shows this can persist.",
        "right_lesson": "TINA ('There Is No Alternative') to equities during zero-rate periods. Dividend stocks and REITs fill the income void bonds previously provided.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "event",
        "title": "Currency Devaluation: 20% Loss",
        "body": "A country where you hold foreign investments devalues its currency by 20% overnight. Your investment returns in local currency are strong, but USD value collapsed.",
        "emoji": "💱",
        "stage_min": 4, "stage_max": 5,
        "topics": ["bonds", "stocks"],
        "linked_traits": ["risk_appetite", "loss_aversion", "diversification_bias"],
        "difficulty": 0.75, "diagnostic_power": 0.8,
        "base_priority": 0.9, "cooldown": 4,
        "left_choice": "Exit foreign positions entirely",
        "right_choice": "Hedge currency exposure with forwards",
        "left_lesson": "Exiting after a devaluation locks in losses. Currency risk is a known factor in international investing that should be priced in beforehand.",
        "right_lesson": "Currency-hedged ETFs and forward contracts can eliminate forex risk. Sophisticated international investors always factor currency exposure into risk.",
        "card_band_color": "purple",
    },
    {
        "type": "event",
        "title": "Market All-Time High",
        "body": "Markets just hit all-time highs. Friends say 'the market always goes up' and are going all-in on leveraged ETFs. You're cautious but feeling left behind.",
        "emoji": "🏔️",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["fomo_sensitivity", "overconfidence", "loss_aversion"],
        "difficulty": 0.55, "diagnostic_power": 0.8,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "All-in — momentum is real",
        "right_choice": "Rebalance to target allocation",
        "left_lesson": "Leveraged ETFs experience volatility decay — a 2x ETF going up 10% then down 10% returns less than zero. They're not long-term holds.",
        "right_lesson": "All-time highs are not tops. Markets make new ATHs frequently. Rebalancing at ATHs locks in gains and maintains risk alignment — it's disciplined, not timid.",
        "card_band_color": "green",
    },
    {
        "type": "event",
        "title": "Your Mentor's Hot Tip",
        "body": "Your successful investor mentor shares a stock tip based on 'inside knowledge' from a friend. The opportunity sounds compelling. But something feels off.",
        "emoji": "🤫",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.6, "diagnostic_power": 0.85,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Act on the tip — trust your mentor",
        "right_choice": "Decline — this sounds like insider trading",
        "left_lesson": "Trading on material non-public information is illegal insider trading regardless of the source. Penalties include prison time and disgorgement of profits.",
        "right_lesson": "Legitimate edges come from better analysis of public information, not access to private data. Edge from legality is no edge at all.",
        "card_band_color": "red",
    },
    {
        "type": "event",
        "title": "Pension Fund Announcement",
        "body": "Your employer announces a pension freeze — future accruals stop. You must now self-manage more retirement savings. An uncomfortable but clarifying moment.",
        "emoji": "📋",
        "stage_min": 2, "stage_max": 4,
        "topics": ["bonds", "stocks"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.45, "diagnostic_power": 0.65,
        "base_priority": 1.0, "cooldown": 6,
        "left_choice": "Panic — my retirement is at risk",
        "right_choice": "Increase 401k contributions now",
        "left_lesson": "Defined benefit pensions were always a fragile promise. Workers who also maintained personal investment accounts were protected when pensions failed.",
        "right_lesson": "Pension freeze = freedom. You now control your retirement destiny. Increasing 401k contributions by even 2% can add $100,000+ over 20 years.",
        "card_band_color": "amber",
    },
    {
        "type": "event",
        "title": "Economic Recession Confirmed",
        "body": "GDP contracts for two consecutive quarters. Unemployment rises, consumer spending falls. Your diversified portfolio is down 18%. Economic winter has arrived.",
        "emoji": "🌨️",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks", "bonds", "real_estate"],
        "linked_traits": ["loss_aversion", "patience", "risk_appetite"],
        "difficulty": 0.65, "diagnostic_power": 0.85,
        "base_priority": 1.1, "cooldown": 4,
        "left_choice": "Defensive positioning — cash and bonds",
        "right_choice": "Gradual rebalance into equities",
        "left_lesson": "Moving to full defensive posture during recessions means you'll likely miss the early recovery — which historically provides the strongest returns.",
        "right_lesson": "Recessions are part of the economic cycle. Investors who gradually increased equity exposure during the 2008-2009 recession captured enormous value.",
        "card_band_color": "steel_blue",
    },

    # ─── ACTION CARDS (15) ────────────────────────────────────────────────────
    {
        "type": "action",
        "title": "Rebalance Your Portfolio",
        "body": "After strong stock performance, equities now represent 75% of your portfolio vs. your 60% target. Time to rebalance — but taxes and transaction costs apply.",
        "emoji": "🔧",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["patience", "diversification_bias"],
        "difficulty": 0.45, "diagnostic_power": 0.7,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Let it ride — stocks are working",
        "right_choice": "Rebalance to 60/40 target",
        "left_lesson": "Allowing drift means your actual risk profile no longer matches your stated one. In a crash, your true equity exposure will shock you.",
        "right_lesson": "Tax-loss harvesting in the bond side can offset rebalancing gains. Systematic rebalancing is a risk management tool, not market timing.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "action",
        "title": "Buy Individual Stock?",
        "body": "You've done 10 hours of research on a company. You believe it's undervalued by 40%. Your rules say no individual stocks — but this feels different.",
        "emoji": "🎲",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["overconfidence", "risk_appetite"],
        "difficulty": 0.55, "diagnostic_power": 0.8,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Buy — high conviction play",
        "right_choice": "Maintain index fund allocation",
        "left_lesson": "Professional analysts with full-time research teams still underperform indices. 10 hours of research does not provide institutional-grade edge.",
        "right_lesson": "If you must invest in individual stocks, cap it at 5-10% of portfolio. Never let a single conviction bet risk your financial plan.",
        "card_band_color": "amber",
    },
    {
        "type": "action",
        "title": "Take Profits or Let Run?",
        "body": "A position you entered 18 months ago is up 180%. It now represents 15% of your portfolio. Trim and rebalance, or hold for more?",
        "emoji": "💹",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["loss_aversion", "overconfidence", "patience"],
        "difficulty": 0.55, "diagnostic_power": 0.8,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Hold — momentum continues",
        "right_choice": "Trim 50% to rebalance",
        "left_lesson": "Momentum is real but reversals are sudden. A 180% gain can retrace 50% quickly. Discipline means not waiting for the top.",
        "right_lesson": "Trimming 50% of a 180% winner locks in substantial profit while maintaining upside exposure. The art is knowing when 'good enough' is optimal.",
        "card_band_color": "green",
    },
    {
        "type": "action",
        "title": "Margin Loan Decision",
        "body": "Your broker offers 2:1 leverage on your portfolio. Markets have been strong for 14 months. Doubling your exposure would double your gains.",
        "emoji": "🏦",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks", "derivatives"],
        "linked_traits": ["risk_appetite", "overconfidence", "loss_aversion"],
        "difficulty": 0.7, "diagnostic_power": 0.9,
        "base_priority": 1.0, "cooldown": 4,
        "left_choice": "Take the margin — momentum is real",
        "right_choice": "Never use margin — avoid forced selling risk",
        "left_lesson": "Margin amplifies losses too. A 50% market decline on 2:1 leverage wipes out 100% of your equity. Margin calls force selling at the worst time.",
        "right_lesson": "Margin is a professional tool requiring risk management expertise most retail investors lack. The emotional resilience required is underestimated.",
        "card_band_color": "red",
    },
    {
        "type": "action",
        "title": "Sell Your Home?",
        "body": "Your home has appreciated 60% over 5 years. You could sell, capture the tax-free $250K gain, and invest in diversified assets. But you love your neighborhood.",
        "emoji": "🔑",
        "stage_min": 3, "stage_max": 5,
        "topics": ["real_estate"],
        "linked_traits": ["loss_aversion", "diversification_bias"],
        "difficulty": 0.6, "diagnostic_power": 0.65,
        "base_priority": 0.9, "cooldown": 6,
        "left_choice": "Stay — home is more than investment",
        "right_choice": "Sell and diversify",
        "left_lesson": "Primary residence provides housing utility, community, and stability that has real financial value beyond the investment return.",
        "right_lesson": "Capturing $250K tax-free gain and investing in diversified assets mathematically outperforms in most scenarios. But life quality matters too.",
        "card_band_color": "amber",
    },
    {
        "type": "action",
        "title": "Open a Roth IRA",
        "body": "You qualify for a Roth IRA this year. Contributing $7,000 now means tax-free growth forever. The opportunity has an income limit — next year you may not qualify.",
        "emoji": "🌱",
        "stage_min": 1, "stage_max": 3,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["patience"],
        "difficulty": 0.3, "diagnostic_power": 0.6,
        "base_priority": 1.1, "cooldown": 7,
        "left_choice": "Skip — need the cash now",
        "right_choice": "Max out the Roth IRA",
        "left_lesson": "Missing a Roth IRA contribution year is permanent — you can't go back. The tax-free compounding on even a single year's contribution is enormous.",
        "right_lesson": "$7,000 in a Roth at 25 growing at 7% = $106,000 tax-free by 65. The IRS gives you this opportunity; use it every eligible year.",
        "card_band_color": "green",
    },
    {
        "type": "action",
        "title": "Pay Off Debt vs. Invest?",
        "body": "You have $10,000. Student loans at 5.5% APR vs. investing in S&P 500 historically returning 10%. The math seems clear, but risk matters too.",
        "emoji": "🤔",
        "stage_min": 1, "stage_max": 3,
        "topics": ["bonds", "stocks"],
        "linked_traits": ["loss_aversion", "patience", "risk_appetite"],
        "difficulty": 0.4, "diagnostic_power": 0.7,
        "base_priority": 1.0, "cooldown": 6,
        "left_choice": "Pay off debt first",
        "right_choice": "Invest — expected return beats debt rate",
        "left_lesson": "Paying off 5.5% debt is a guaranteed 5.5% return. In a low-return environment, this can outperform markets net of tax.",
        "right_lesson": "Expected market returns of 10% historically exceed 5.5% debt cost. Invest while making minimum payments — then clear debt once wealth builds.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "action",
        "title": "Buy a Bond Ladder",
        "body": "With rates at 5%, you could build a bond ladder: 20% each in 1, 2, 3, 4, and 5-year Treasuries. Predictable income, minimal risk, and rate exposure managed.",
        "emoji": "🪜",
        "stage_min": 3, "stage_max": 5,
        "topics": ["bonds"],
        "linked_traits": ["patience", "diversification_bias", "loss_aversion"],
        "difficulty": 0.55, "diagnostic_power": 0.65,
        "base_priority": 0.9, "cooldown": 6,
        "left_choice": "Too conservative — I want growth",
        "right_choice": "Build the bond ladder",
        "left_lesson": "Shunning bonds entirely at high rate environments foregoes guaranteed 5% returns. In retirement, predictable cash flow has immense value.",
        "right_lesson": "Bond ladders eliminate reinvestment risk by spreading maturities. When rates fluctuate, you always have bonds maturing to reinvest at current rates.",
        "card_band_color": "steel_blue",
    },
    {
        "type": "action",
        "title": "Hire a Financial Advisor?",
        "body": "A fiduciary financial advisor charges 1% AUM per year. On $500,000, that's $5,000 annually. Studies show advisor guidance typically adds ~3% annual value. Worth it?",
        "emoji": "👔",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.5, "diagnostic_power": 0.6,
        "base_priority": 0.9, "cooldown": 7,
        "left_choice": "I'll self-manage — 1% is too much",
        "right_choice": "Fiduciary advisors deliver net value",
        "left_lesson": "Self-managing is rational if you have the knowledge, discipline, and emotional resilience. Most investors who think they do, don't.",
        "right_lesson": "Vanguard's 'Advisor Alpha' research suggests advisors add ~3% annually via behavioral coaching alone. The 1% fee buys a lot of protection.",
        "card_band_color": "amber",
    },
    {
        "type": "action",
        "title": "Dollar-Cost Average Into Correction",
        "body": "Markets are down 20% — officially a correction. You have $5,000 in cash set aside for exactly this moment. Deploy all at once or spread over 3 months?",
        "emoji": "📅",
        "stage_min": 2, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity", "patience"],
        "difficulty": 0.5, "diagnostic_power": 0.75,
        "base_priority": 1.0, "cooldown": 5,
        "left_choice": "Wait — might fall further",
        "right_choice": "Deploy now at -20% discount",
        "left_lesson": "Waiting for 'the bottom' is impossible. Markets can fall another 20% or recover 30% before you buy. -20% is already a significant discount.",
        "right_lesson": "Buying at -20% from ATH means historically strong 3-year forward returns. Corrections are one of the few times retail investors have an actual advantage.",
        "card_band_color": "green",
    },
    {
        "type": "action",
        "title": "Exercise Stock Options",
        "body": "Your company stock options vest next month. The stock is at $80, your strike price is $40. You can exercise and sell immediately or hold for more upside.",
        "emoji": "📜",
        "stage_min": 3, "stage_max": 5,
        "topics": ["stocks", "derivatives"],
        "linked_traits": ["loss_aversion", "overconfidence", "risk_appetite"],
        "difficulty": 0.65, "diagnostic_power": 0.75,
        "base_priority": 0.9, "cooldown": 5,
        "left_choice": "Hold for more upside",
        "right_choice": "Exercise and diversify",
        "left_lesson": "Concentrated company stock risk is among the most dangerous in personal finance. Employees have both human capital AND equity concentrated in one company.",
        "right_lesson": "The mathematical case for immediate exercise and diversification is almost always overwhelming. Don't let loyalty or optimism create dangerous concentration.",
        "card_band_color": "purple",
    },
    {
        "type": "action",
        "title": "Automate Your Savings",
        "body": "Setting up automatic transfers to investment accounts removes willpower from the equation. You can't spend what you never see. The decision takes 10 minutes.",
        "emoji": "⚙️",
        "stage_min": 1, "stage_max": 3,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["patience"],
        "difficulty": 0.2, "diagnostic_power": 0.65,
        "base_priority": 1.1, "cooldown": 8,
        "left_choice": "I prefer manual control",
        "right_choice": "Automate everything possible",
        "left_lesson": "Manual investing requires consistent decisions under variable emotional states. Automation removes human psychology from the most important financial habit.",
        "right_lesson": "Automated investors consistently outperform manual investors not through better picks, but through never missing a contribution during market fear.",
        "card_band_color": "green",
    },
    {
        "type": "action",
        "title": "Invest in a Private Deal",
        "body": "A friend's startup needs $25,000 and offers you 2% equity. The business has revenue but needs capital. You can afford to lose the entire amount.",
        "emoji": "🤝",
        "stage_min": 4, "stage_max": 5,
        "topics": ["stocks"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.7, "diagnostic_power": 0.7,
        "base_priority": 0.8, "cooldown": 6,
        "left_choice": "Too risky — private equity is illiquid",
        "right_choice": "Angel investing has asymmetric upside",
        "left_lesson": "90% of startups fail. Illiquidity means you can't exit for 5-10 years. Private deals should represent a tiny portion of any portfolio.",
        "right_lesson": "Angel investing at the right entry creates asymmetric returns impossible in public markets. The 10% that succeed can return 10x-100x.",
        "card_band_color": "purple",
    },
    {
        "type": "action",
        "title": "Short a Sector ETF",
        "body": "You believe commercial real estate is overvalued and will crash within 12 months. You can short a commercial REIT ETF. High conviction, significant risk.",
        "emoji": "🏢",
        "stage_min": 4, "stage_max": 5,
        "topics": ["real_estate", "derivatives"],
        "linked_traits": ["overconfidence", "risk_appetite"],
        "difficulty": 0.8, "diagnostic_power": 0.85,
        "base_priority": 0.8, "cooldown": 4,
        "left_choice": "Short it — I'm confident",
        "right_choice": "Avoid shorting sectors",
        "left_lesson": "Even correct macro calls can be early by 3+ years. Shorting at 2020-level valuations and paying borrow costs while prices rise can ruin you before you're right.",
        "right_lesson": "A small short position (2-3% of portfolio) as a hedge differs from a speculative directional bet. Size determines whether this is risk management or gambling.",
        "card_band_color": "red",
    },
    {
        "type": "action",
        "title": "Spend on Financial Education",
        "body": "A rigorous financial modeling course costs $2,000. It would take 60 hours to complete. The ROI is unclear but the knowledge is permanent.",
        "emoji": "📚",
        "stage_min": 1, "stage_max": 3,
        "topics": ["stocks", "bonds"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.3, "diagnostic_power": 0.6,
        "base_priority": 1.0, "cooldown": 8,
        "left_choice": "Skip — free resources exist",
        "right_choice": "Invest in your financial literacy",
        "left_lesson": "Free resources exist but structured learning with accountability accelerates mastery. The YouTube rabbit hole rarely creates systematic knowledge.",
        "right_lesson": "Financial literacy is the highest-return investment available to young investors. $2,000 in knowledge can save or earn $200,000+ over a lifetime.",
        "card_band_color": "steel_blue",
    },
]
