"""Market psychology themed deck cards (progression-unlocked deck)."""

MARKET_PSYCHOLOGY_CARDS = [
    {
        "card_id": "MPY_E_001",
        "type": "education",
        "title": "Loss Aversion Bias",
        "body": "Most investors feel losses about twice as strongly as gains. That imbalance can trigger bad exits during normal volatility.",
        "emoji": "🧠",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["panic_selling", "volatility"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.82,
        "base_priority": 1.12,
        "cooldown": 6,
        "left_choice": "Pain means sell now",
        "right_choice": "Discomfort is not signal",
        "left_lesson": "Fun fact: Emotional pain spikes most near bottoms, where expected long-run returns usually improve.",
        "right_lesson": "Fun fact: Separating emotion from process is one of the strongest predictors of investor durability.",
        "card_band_color": "red",
        "alpha": 0.92,
        "weights": {"sentiment": -0.12, "inflation": 0.0, "greed": -0.08, "volatility": 0.18, "fundamentals": 0.08},
    },
    {
        "card_id": "MPY_E_002",
        "type": "education",
        "title": "Recency Trap",
        "body": "Recent outcomes feel more important than long history. After sharp rallies or crashes, investors often project the latest move too far.",
        "emoji": "🔁",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["market_timing", "consistency"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.46,
        "diagnostic_power": 0.8,
        "base_priority": 1.08,
        "cooldown": 6,
        "left_choice": "Recent trend is destiny",
        "right_choice": "Use full-cycle context",
        "left_lesson": "Fun fact: Recency bias contributes to buying high after rallies and selling low after drawdowns.",
        "right_lesson": "Fun fact: Process discipline can outperform prediction by reducing reaction errors.",
        "card_band_color": "amber",
        "alpha": 0.9,
        "weights": {"sentiment": 0.03, "inflation": 0.0, "greed": 0.06, "volatility": 0.1, "fundamentals": 0.1},
    },
    {
        "card_id": "MPY_E_003",
        "type": "education",
        "title": "Overconfidence Loop",
        "body": "A few lucky wins can look like skill. Overconfidence often increases trade frequency just before performance weakens.",
        "emoji": "🎯",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["overtrading", "consistency"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.48,
        "diagnostic_power": 0.82,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Wins prove permanent edge",
        "right_choice": "Check base-rate reality",
        "left_lesson": "Fun fact: Turnover-heavy portfolios often underperform net of slippage, fees, and timing errors.",
        "right_lesson": "Fun fact: A trade journal can expose whether results came from process or luck.",
        "card_band_color": "purple",
        "alpha": 0.92,
        "weights": {"sentiment": 0.04, "inflation": 0.0, "greed": 0.2, "volatility": 0.14, "fundamentals": -0.04},
    },
    {
        "card_id": "MPY_E_004",
        "type": "education",
        "title": "FOMO Momentum Chasing",
        "body": "Fear of missing out pushes entries after big moves, usually when risk-reward has worsened.",
        "emoji": "🚀",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["fomo", "market_timing"],
        "linked_traits": ["fomo_sensitivity", "loss_aversion"],
        "difficulty": 0.47,
        "diagnostic_power": 0.81,
        "base_priority": 1.09,
        "cooldown": 6,
        "left_choice": "Late entry is safer",
        "right_choice": "Chasing raises downside",
        "left_lesson": "Fun fact: Socially crowded trades can unwind quickly when marginal buyers run out.",
        "right_lesson": "Fun fact: Position-sizing and entry rules protect against impulsive chase behavior.",
        "card_band_color": "purple",
        "alpha": 0.91,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": 0.28, "volatility": 0.18, "fundamentals": -0.06},
    },
    {
        "card_id": "MPY_E_005",
        "type": "education",
        "title": "Panic Selling Cascade",
        "body": "In fast drawdowns, fear compresses decision quality. Selling to remove stress can lock in permanent losses.",
        "emoji": "😰",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["panic_selling", "volatility"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.86,
        "base_priority": 1.14,
        "cooldown": 5,
        "left_choice": "Sell to stop pain",
        "right_choice": "Follow pre-set plan",
        "left_lesson": "Fun fact: Drawdown exits usually require perfect re-entry timing, which is rare in practice.",
        "right_lesson": "Fun fact: Pre-committed rules lower panic decisions during regime stress.",
        "card_band_color": "red",
        "alpha": 0.98,
        "weights": {"sentiment": -0.2, "inflation": 0.0, "greed": -0.1, "volatility": 0.24, "fundamentals": 0.06},
    },
    {
        "card_id": "MPY_E_006",
        "type": "education",
        "title": "Confirmation Bias",
        "body": "Investors naturally seek information that supports existing positions and ignore disconfirming evidence.",
        "emoji": "🔎",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["consistency", "overtrading"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.49,
        "diagnostic_power": 0.82,
        "base_priority": 1.07,
        "cooldown": 6,
        "left_choice": "Only read bullish case",
        "right_choice": "Track thesis killers",
        "left_lesson": "Fun fact: Missing contradictory evidence can extend losing positions unnecessarily.",
        "right_lesson": "Fun fact: Explicit disconfirming checklists improve decision calibration.",
        "card_band_color": "steel_blue",
        "alpha": 0.9,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": 0.08, "volatility": 0.1, "fundamentals": 0.1},
    },
    {
        "card_id": "MPY_E_007",
        "type": "education",
        "title": "Anchoring on Purchase Price",
        "body": "Entry price is not a fair-value estimate. Anchoring to cost basis can distort sell discipline.",
        "emoji": "⚓",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["market_timing", "consistency"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.46,
        "diagnostic_power": 0.79,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "I must get back to even",
        "right_choice": "Revalue from today",
        "left_lesson": "Fun fact: Cost-basis anchoring can prevent rational exits when thesis quality deteriorates.",
        "right_lesson": "Fun fact: Forward-looking valuation is usually superior to backward-looking anchor points.",
        "card_band_color": "amber",
        "alpha": 0.88,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": 0.04, "volatility": 0.08, "fundamentals": 0.11},
    },
    {
        "card_id": "MPY_E_008",
        "type": "education",
        "title": "Process Beats Prediction",
        "body": "Most alpha for individuals comes from avoiding behavioral errors, not forecasting every macro move.",
        "emoji": "🧭",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["consistency", "market_timing"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.44,
        "diagnostic_power": 0.78,
        "base_priority": 1.04,
        "cooldown": 6,
        "left_choice": "Need perfect calls",
        "right_choice": "Need repeatable process",
        "left_lesson": "Fun fact: Consistent mistakes can erase occasional brilliant calls.",
        "right_lesson": "Fun fact: Strong process quality usually compounds better than tactical brilliance.",
        "card_band_color": "green",
        "alpha": 0.86,
        "weights": {"sentiment": 0.06, "inflation": 0.0, "greed": -0.04, "volatility": -0.02, "fundamentals": 0.14},
    },
    {
        "card_id": "MPY_V_001",
        "type": "event",
        "title": "Flash Drop Stress",
        "body": "Index futures swing {value}% intraday and social feeds predict a systemic collapse.",
        "emoji": "📉",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["panic_selling", "volatility"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.58,
        "diagnostic_power": 0.88,
        "base_priority": 1.18,
        "cooldown": 5,
        "left_choice": "Dump risk immediately",
        "right_choice": "Follow crash protocol",
        "left_lesson": "Fun fact: Liquidity vacuums can reverse quickly, punishing reactive exits.",
        "right_lesson": "Fun fact: Predefined crash rules reduce error variance under stress.",
        "card_band_color": "red",
        "value_min": 4.0,
        "value_max": 15.0,
        "value_step": 1.0,
        "alpha": 1.08,
        "weights": {"sentiment": -0.35, "inflation": 0.0, "greed": -0.1, "volatility": 0.42, "fundamentals": -0.06},
    },
    {
        "card_id": "MPY_V_002",
        "type": "event",
        "title": "Viral Trading Frenzy",
        "body": "A meme basket rallies {value}% in two sessions and your peers boast outsized gains.",
        "emoji": "📱",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["fomo", "overtrading"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.14,
        "cooldown": 5,
        "left_choice": "Chase momentum now",
        "right_choice": "Keep allocation limits",
        "left_lesson": "Fun fact: Crowded retail surges often reverse fastest when attention fades.",
        "right_lesson": "Fun fact: Hard risk limits protect against social-proof driven position creep.",
        "card_band_color": "purple",
        "value_min": 20.0,
        "value_max": 120.0,
        "value_step": 10.0,
        "alpha": 1.04,
        "weights": {"sentiment": 0.22, "inflation": 0.0, "greed": 0.4, "volatility": 0.35, "fundamentals": -0.12},
    },
    {
        "card_id": "MPY_V_003",
        "type": "event",
        "title": "Whipsaw Week",
        "body": "Market swings alternate direction by about {value}% per day, triggering emotional overreactions.",
        "emoji": "🌪️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["overtrading", "volatility"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.56,
        "diagnostic_power": 0.84,
        "base_priority": 1.13,
        "cooldown": 5,
        "left_choice": "Trade every swing",
        "right_choice": "Reduce turnover sharply",
        "left_lesson": "Fun fact: Whipsaw regimes often convert tactical trading into slippage and tax drag.",
        "right_lesson": "Fun fact: Turnover control can materially improve realized net return in noisy markets.",
        "card_band_color": "amber",
        "value_min": 1.0,
        "value_max": 4.0,
        "value_step": 1.0,
        "alpha": 1.02,
        "weights": {"sentiment": -0.08, "inflation": 0.0, "greed": 0.06, "volatility": 0.38, "fundamentals": -0.04},
    },
    {
        "card_id": "MPY_V_004",
        "type": "event",
        "title": "Bear-Market Rally",
        "body": "After heavy declines, the index rebounds {value}% in ten days, reviving confidence prematurely.",
        "emoji": "🐻",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["market_timing", "fomo"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.54,
        "diagnostic_power": 0.83,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Assume new bull market",
        "right_choice": "Demand trend confirmation",
        "left_lesson": "Fun fact: Bear rallies can be large, fast, and misleading without breadth confirmation.",
        "right_lesson": "Fun fact: Multi-signal confirmation reduces false regime shifts.",
        "card_band_color": "steel_blue",
        "value_min": 6.0,
        "value_max": 20.0,
        "value_step": 2.0,
        "alpha": 1.0,
        "weights": {"sentiment": 0.12, "inflation": 0.0, "greed": 0.18, "volatility": 0.2, "fundamentals": -0.02},
    },
    {
        "card_id": "MPY_V_005",
        "type": "event",
        "title": "Headline Overload",
        "body": "You consume about {value} market headlines before noon and feel pressure to act despite no thesis change.",
        "emoji": "📰",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["consistency", "overtrading"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.07,
        "cooldown": 5,
        "left_choice": "More headlines, more edge",
        "right_choice": "Filter inputs aggressively",
        "left_lesson": "Fun fact: Information overload can increase confidence while decreasing actual decision quality.",
        "right_lesson": "Fun fact: Narrowing input channels improves focus on signal over noise.",
        "card_band_color": "purple",
        "value_min": 10.0,
        "value_max": 60.0,
        "value_step": 10.0,
        "alpha": 0.98,
        "weights": {"sentiment": 0.02, "inflation": 0.0, "greed": 0.12, "volatility": 0.16, "fundamentals": 0.02},
    },
    {
        "card_id": "MPY_V_006",
        "type": "event",
        "title": "Stop-Loss Chain Reaction",
        "body": "A liquidity gap hits and cascaded stop orders extend the move by another {value}%.",
        "emoji": "⛔",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["panic_selling", "market_timing"],
        "linked_traits": ["loss_aversion", "overconfidence"],
        "difficulty": 0.57,
        "diagnostic_power": 0.86,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Market order out now",
        "right_choice": "Use staged execution",
        "left_lesson": "Fun fact: Market orders in thin liquidity can materially worsen realized exit prices.",
        "right_lesson": "Fun fact: Staged execution reduces impact cost during stressed tape conditions.",
        "card_band_color": "red",
        "value_min": 1.0,
        "value_max": 8.0,
        "value_step": 1.0,
        "alpha": 1.06,
        "weights": {"sentiment": -0.22, "inflation": 0.0, "greed": -0.08, "volatility": 0.34, "fundamentals": -0.04},
    },
    {
        "card_id": "MPY_A_001",
        "type": "action",
        "title": "Write a Panic Protocol",
        "body": "Define a crash-day checklist and require {value} conditions before any forced de-risking.",
        "emoji": "🛡️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["panic_selling", "consistency"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.46,
        "diagnostic_power": 0.82,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Decide in the moment",
        "right_choice": "Use protocol triggers",
        "left_lesson": "Fun fact: Real-time improvisation during stress is usually dominated by emotion.",
        "right_lesson": "Fun fact: Structured crisis protocols improve consistency across market regimes.",
        "card_band_color": "green",
        "value_min": 2.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.02, "inflation": 0.0, "greed": -0.08, "volatility": -0.1, "fundamentals": 0.12},
    },
    {
        "card_id": "MPY_A_002",
        "type": "action",
        "title": "Daily Trade Cap",
        "body": "Set a hard maximum of {value} discretionary trades per day to curb impulse churn.",
        "emoji": "🧮",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["overtrading", "consistency"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.44,
        "diagnostic_power": 0.78,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "No cap needed",
        "right_choice": "Enforce turnover limit",
        "left_lesson": "Fun fact: Unlimited discretion increases probability of low-quality reactive trades.",
        "right_lesson": "Fun fact: Trading caps help separate conviction from compulsion.",
        "card_band_color": "amber",
        "value_min": 1.0,
        "value_max": 8.0,
        "value_step": 1.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.06, "volatility": -0.08, "fundamentals": 0.1},
    },
    {
        "card_id": "MPY_A_003",
        "type": "action",
        "title": "FOMO Cooldown Rule",
        "body": "After any asset rises more than {value}% in a day, require a 24-hour cooldown before new entries.",
        "emoji": "❄️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["fomo", "market_timing"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Buy the breakout instantly",
        "right_choice": "Respect cooldown rule",
        "left_lesson": "Fun fact: Immediate chase entries are often made at local liquidity extremes.",
        "right_lesson": "Fun fact: Cooldown windows improve entry quality by reducing emotional urgency.",
        "card_band_color": "green",
        "value_min": 6.0,
        "value_max": 20.0,
        "value_step": 2.0,
        "alpha": 0.92,
        "weights": {"sentiment": 0.03, "inflation": 0.0, "greed": -0.08, "volatility": -0.07, "fundamentals": 0.09},
    },
    {
        "card_id": "MPY_A_004",
        "type": "action",
        "title": "Position-Size by Volatility",
        "body": "Cut position size by {value}% when realized volatility exceeds your normal risk regime.",
        "emoji": "📏",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["volatility", "consistency"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.5,
        "diagnostic_power": 0.82,
        "base_priority": 1.09,
        "cooldown": 5,
        "left_choice": "Keep size unchanged",
        "right_choice": "Scale to volatility",
        "left_lesson": "Fun fact: Constant size in variable volatility can create hidden leverage.",
        "right_lesson": "Fun fact: Vol-adjusted sizing helps stabilize drawdowns across regimes.",
        "card_band_color": "steel_blue",
        "value_min": 10.0,
        "value_max": 50.0,
        "value_step": 10.0,
        "alpha": 0.98,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.05, "volatility": -0.12, "fundamentals": 0.12},
    },
    {
        "card_id": "MPY_A_005",
        "type": "action",
        "title": "Thesis-Only Exit Rule",
        "body": "Allow exits only on thesis break, risk-limit breach, or after {value} scheduled review periods.",
        "emoji": "📋",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["market_timing", "consistency"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.49,
        "diagnostic_power": 0.81,
        "base_priority": 1.08,
        "cooldown": 6,
        "left_choice": "Exit on price discomfort",
        "right_choice": "Exit on predefined logic",
        "left_lesson": "Fun fact: Price-only exits often convert noise into unnecessary turnover.",
        "right_lesson": "Fun fact: Rule-based exits improve comparability and post-trade learning.",
        "card_band_color": "green",
        "value_min": 1.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.01, "inflation": 0.0, "greed": -0.06, "volatility": -0.09, "fundamentals": 0.11},
    },
    {
        "card_id": "MPY_A_006",
        "type": "action",
        "title": "Weekly Reflection Log",
        "body": "Log top mistakes and best decisions each week on a {value}-point confidence scale.",
        "emoji": "📝",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["consistency", "overtrading"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.42,
        "diagnostic_power": 0.76,
        "base_priority": 1.02,
        "cooldown": 6,
        "left_choice": "Skip reflection routine",
        "right_choice": "Keep behavior log",
        "left_lesson": "Fun fact: Unlogged behavior errors repeat because memory rewrites outcomes.",
        "right_lesson": "Fun fact: Reflection logs improve calibration and reduce repeated bias patterns.",
        "card_band_color": "steel_blue",
        "value_min": 5.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 0.88,
        "weights": {"sentiment": 0.02, "inflation": 0.0, "greed": -0.05, "volatility": -0.07, "fundamentals": 0.1},
    },
]
