"""Great Depression themed deck cards (shop deck)."""

GREAT_DEPRESSION_CARDS = [
    {
        "card_id": "GDP_E_001",
        "type": "education",
        "title": "The Roaring Twenties Boom",
        "body": "In the late 1920s, US stocks surged and easy credit made speculation feel normal. Booms often hide fragile debt underneath.",
        "emoji": "\ud83c\udf1f",
        "stage_min": 1,
        "stage_max": 2,
        "topics": ["great_depression", "market_growth"],
        "linked_traits": ["overconfidence", "fomo_sensitivity"],
        "difficulty": 0.25,
        "diagnostic_power": 0.65,
        "base_priority": 1.2,
        "cooldown": 8,
        "left_choice": "Booms justify any valuation",
        "right_choice": "Debt-fueled booms can unwind fast",
        "left_lesson": "Fun fact: By 1929, many investors bought stocks on margin with just 10% cash.",
        "right_lesson": "Fun fact: Credit conditions, not just optimism, powered much of the 1920s rally.",
        "card_band_color": "amber",
        "alpha": 0.35,
        "weights": {"sentiment": 0.35, "inflation": 0.0, "greed": 0.45, "volatility": 0.2, "fundamentals": 0.1},
    },
    {
        "card_id": "GDP_E_002",
        "type": "education",
        "title": "Buying on Margin",
        "body": "Margin lets you borrow to buy stocks. Gains get amplified, but losses can trigger forced selling and wipeouts.",
        "emoji": "\ud83e\uddfe",
        "stage_min": 1,
        "stage_max": 2,
        "topics": ["great_depression", "risk_return"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.3,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 8,
        "left_choice": "Leverage is fine in all markets",
        "right_choice": "Leverage can force bad exits",
        "left_lesson": "Fun fact: Brokers issued margin calls quickly as prices fell in 1929.",
        "right_lesson": "Fun fact: Forced liquidations from margin calls can accelerate crashes.",
        "card_band_color": "red",
        "alpha": 0.4,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": 0.55, "volatility": 0.4, "fundamentals": -0.05},
    },
    {
        "card_id": "GDP_E_003",
        "type": "education",
        "title": "Black Thursday to Black Tuesday",
        "body": "Panic selling spread over several days in October 1929. Crashes are often a process, not a single moment.",
        "emoji": "\ud83d\udcc9",
        "stage_min": 1,
        "stage_max": 2,
        "topics": ["great_depression", "panic_selling"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.25,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 7,
        "left_choice": "It was one bad day only",
        "right_choice": "Liquidity stress can cascade",
        "left_lesson": "Fun fact: Trading volume records were shattered during the crash week.",
        "right_lesson": "Fun fact: Recovery attempts during crashes can fail when confidence remains broken.",
        "card_band_color": "red",
        "alpha": 0.45,
        "weights": {"sentiment": -0.5, "inflation": -0.1, "greed": -0.3, "volatility": 0.7, "fundamentals": -0.2},
    },
    {
        "card_id": "GDP_E_004",
        "type": "education",
        "title": "Bank Runs Explained",
        "body": "Banks can fail when too many depositors withdraw at once, even if long-term assets are still valuable.",
        "emoji": "\ud83c\udfe6",
        "stage_min": 1,
        "stage_max": 3,
        "topics": ["great_depression", "saving_vs_investing"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.35,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 8,
        "left_choice": "Cash at home is always safest",
        "right_choice": "System stability matters most",
        "left_lesson": "Fun fact: Before FDIC insurance, losing deposits in a bank failure was common.",
        "right_lesson": "Fun fact: Deposit insurance was introduced in 1933 to reduce bank run panic.",
        "card_band_color": "steel_blue",
        "alpha": 0.45,
        "weights": {"sentiment": -0.35, "inflation": -0.2, "greed": -0.25, "volatility": 0.5, "fundamentals": -0.2},
    },
    {
        "card_id": "GDP_E_005",
        "type": "education",
        "title": "Deflation Trap",
        "body": "When prices keep falling, people delay spending and debt burdens rise in real terms, slowing recovery.",
        "emoji": "\u2744\ufe0f",
        "stage_min": 2,
        "stage_max": 3,
        "topics": ["great_depression", "inflation"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.4,
        "diagnostic_power": 0.8,
        "base_priority": 1.2,
        "cooldown": 7,
        "left_choice": "Falling prices always help",
        "right_choice": "Deflation can damage demand",
        "left_lesson": "Fun fact: US consumer prices dropped sharply in the early 1930s.",
        "right_lesson": "Fun fact: Deflation increases real debt, which pressures households and firms.",
        "card_band_color": "amber",
        "alpha": 0.5,
        "weights": {"sentiment": -0.25, "inflation": -0.7, "greed": -0.2, "volatility": 0.25, "fundamentals": -0.35},
    },
    {
        "card_id": "GDP_E_006",
        "type": "education",
        "title": "Smoot-Hawley Tariff",
        "body": "The US raised tariffs in 1930. Retaliation reduced global trade and worsened economic contraction.",
        "emoji": "\ud83d\udce6",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "opportunity_cost"],
        "linked_traits": ["overconfidence", "diversification_bias"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 8,
        "left_choice": "Protectionism has no downside",
        "right_choice": "Trade retaliation can hurt all",
        "left_lesson": "Fun fact: World trade fell dramatically in the early 1930s.",
        "right_lesson": "Fun fact: Trade policy errors can amplify financial shocks into global recessions.",
        "card_band_color": "purple",
        "alpha": 0.55,
        "weights": {"sentiment": -0.25, "inflation": -0.15, "greed": -0.05, "volatility": 0.3, "fundamentals": -0.45},
    },
    {
        "card_id": "GDP_E_007",
        "type": "education",
        "title": "Unemployment Shock",
        "body": "Mass layoffs destroy demand and confidence. Job losses can deepen downturns and delay market recovery.",
        "emoji": "\ud83e\udde9",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "market_growth"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.35,
        "diagnostic_power": 0.75,
        "base_priority": 1.15,
        "cooldown": 7,
        "left_choice": "Markets ignore labor pain",
        "right_choice": "Jobs and markets are linked",
        "left_lesson": "Fun fact: US unemployment reached roughly one in four workers at the peak.",
        "right_lesson": "Fun fact: Household income collapse reduced consumption and business profits.",
        "card_band_color": "red",
        "alpha": 0.5,
        "weights": {"sentiment": -0.45, "inflation": -0.2, "greed": -0.15, "volatility": 0.45, "fundamentals": -0.4},
    },
    {
        "card_id": "GDP_E_008",
        "type": "education",
        "title": "New Deal Programs",
        "body": "Public works and social programs aimed to stabilize demand and support households during collapse.",
        "emoji": "\ud83c\udfd7\ufe0f",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "consistency"],
        "linked_traits": ["patience", "diversification_bias"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "Policy cannot help demand",
        "right_choice": "Policy can cushion collapse",
        "left_lesson": "Fun fact: Programs like WPA and CCC put millions to work.",
        "right_lesson": "Fun fact: Relief spending softened hardship even while recovery remained uneven.",
        "card_band_color": "green",
        "alpha": 0.45,
        "weights": {"sentiment": 0.15, "inflation": 0.05, "greed": -0.1, "volatility": -0.1, "fundamentals": 0.2},
    },
    {
        "card_id": "GDP_E_009",
        "type": "education",
        "title": "Gold Standard Constraints",
        "body": "Fixed exchange-rate commitments limited policy flexibility. Countries leaving gold often recovered sooner.",
        "emoji": "\ud83e\ude99",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "market_timing"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 8,
        "left_choice": "Rigid pegs are always best",
        "right_choice": "Flexibility can aid recovery",
        "left_lesson": "Fun fact: Britain left gold in 1931, the US in 1933.",
        "right_lesson": "Fun fact: Monetary flexibility helped countries fight deflation pressure.",
        "card_band_color": "steel_blue",
        "alpha": 0.55,
        "weights": {"sentiment": 0.0, "inflation": -0.25, "greed": -0.05, "volatility": 0.25, "fundamentals": 0.1},
    },
    {
        "card_id": "GDP_E_010",
        "type": "education",
        "title": "Global Contagion",
        "body": "The crisis spread through finance and trade to Europe and Latin America, proving markets are deeply connected.",
        "emoji": "\ud83c\udf10",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "diversification"],
        "linked_traits": ["diversification_bias", "overconfidence"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "Only US assets were affected",
        "right_choice": "Shocks cross borders quickly",
        "left_lesson": "Fun fact: Banking crises hit Austria and Germany in 1931.",
        "right_lesson": "Fun fact: Diversification helps, but global recessions can still correlate losses.",
        "card_band_color": "purple",
        "alpha": 0.5,
        "weights": {"sentiment": -0.2, "inflation": -0.2, "greed": -0.1, "volatility": 0.35, "fundamentals": -0.25},
    },

    {
        "card_id": "GDP_V_001",
        "type": "event",
        "title": "Margin Call Wave",
        "body": "Brokers demand extra collateral after a {value}% drop. You must act before forced liquidation.",
        "emoji": "\u26a0\ufe0f",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "overtrading"],
        "linked_traits": ["loss_aversion", "overconfidence"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.25,
        "cooldown": 5,
        "left_choice": "Add leverage to recover faster",
        "right_choice": "Deleverage and protect capital",
        "left_lesson": "Fun fact: Leverage can turn temporary drawdowns into permanent losses.",
        "right_lesson": "Fun fact: Survival decisions often beat heroic rebound bets.",
        "card_band_color": "red",
        "value_min": 10.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 1.1,
        "weights": {"sentiment": -0.4, "inflation": -0.1, "greed": 0.2, "volatility": 0.8, "fundamentals": -0.2},
    },
    {
        "card_id": "GDP_V_002",
        "type": "event",
        "title": "Neighborhood Bank Run",
        "body": "Rumors spread and depositors line up. Your local bank limits withdrawals after {value} hours.",
        "emoji": "\ud83c\udfe6",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "saving_vs_investing"],
        "linked_traits": ["loss_aversion", "panic_selling"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Pull all funds immediately",
        "right_choice": "Use a measured withdrawal plan",
        "left_lesson": "Fun fact: Panic withdrawals can destabilize even solvent banks in the short run.",
        "right_lesson": "Fun fact: During crises, liquidity planning matters as much as return targets.",
        "card_band_color": "amber",
        "value_min": 2.0,
        "value_max": 12.0,
        "value_step": 2.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.5, "inflation": -0.2, "greed": -0.2, "volatility": 0.7, "fundamentals": -0.35},
    },
    {
        "card_id": "GDP_V_003",
        "type": "event",
        "title": "Dust Bowl Losses",
        "body": "Crop failures cut rural incomes and loan repayments. Agricultural regions face {value}% income shock.",
        "emoji": "\ud83c\udf2b\ufe0f",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "volatility"],
        "linked_traits": ["diversification_bias", "loss_aversion"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Ignore sector concentration",
        "right_choice": "Reduce concentration risk",
        "left_lesson": "Fun fact: Climate shocks and debt pressure compounded financial stress in farm regions.",
        "right_lesson": "Fun fact: Diversification across sectors can buffer region-specific disasters.",
        "card_band_color": "red",
        "value_min": 10.0,
        "value_max": 35.0,
        "value_step": 5.0,
        "alpha": 0.9,
        "weights": {"sentiment": -0.3, "inflation": -0.1, "greed": -0.1, "volatility": 0.55, "fundamentals": -0.3},
    },
    {
        "card_id": "GDP_V_004",
        "type": "event",
        "title": "Trade Retaliation Escalates",
        "body": "After new tariffs, exports fall {value}% and industrial profits weaken.",
        "emoji": "\ud83d\udea2",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "opportunity_cost"],
        "linked_traits": ["overconfidence", "diversification_bias"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 6,
        "left_choice": "Double down on exporters",
        "right_choice": "Shift toward domestic resilience",
        "left_lesson": "Fun fact: Trade contraction worsened the global downturn during the 1930s.",
        "right_lesson": "Fun fact: Policy shocks can create long drawdowns in exposed sectors.",
        "card_band_color": "purple",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 0.95,
        "weights": {"sentiment": -0.25, "inflation": -0.1, "greed": -0.05, "volatility": 0.45, "fundamentals": -0.35},
    },
    {
        "card_id": "GDP_V_005",
        "type": "event",
        "title": "Deflation Deepens",
        "body": "Consumer prices fall another {value}% this year while debt payments stay fixed.",
        "emoji": "\ud83e\uddf2",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "inflation"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Borrow more to maintain lifestyle",
        "right_choice": "Reduce debt and conserve cash",
        "left_lesson": "Fun fact: Deflation increases the real value of existing debt burdens.",
        "right_lesson": "Fun fact: In deflationary shocks, balance sheet strength becomes a core edge.",
        "card_band_color": "amber",
        "value_min": 2.0,
        "value_max": 12.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.3, "inflation": -0.8, "greed": -0.15, "volatility": 0.35, "fundamentals": -0.35},
    },
    {
        "card_id": "GDP_V_006",
        "type": "event",
        "title": "Factory Closures",
        "body": "Major factories close and your city loses {value} jobs in one quarter.",
        "emoji": "\ud83c\udfed",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "market_growth"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Assume quick V-shaped rebound",
        "right_choice": "Prepare for a slow recovery",
        "left_lesson": "Fun fact: Industrial production fell heavily in the early Depression years.",
        "right_lesson": "Fun fact: Labor market recovery often lags market bottoms by years.",
        "card_band_color": "red",
        "value_min": 5000.0,
        "value_max": 50000.0,
        "value_step": 5000.0,
        "alpha": 0.9,
        "weights": {"sentiment": -0.35, "inflation": -0.1, "greed": -0.1, "volatility": 0.4, "fundamentals": -0.4},
    },
    {
        "card_id": "GDP_V_007",
        "type": "event",
        "title": "Emergency Banking Holiday",
        "body": "Authorities temporarily close banks for {value} days to stop panic withdrawals.",
        "emoji": "\ud83d\udd12",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "consistency"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 6,
        "left_choice": "Panic and dump all risk assets",
        "right_choice": "Follow predefined contingency plan",
        "left_lesson": "Fun fact: The 1933 bank holiday was followed by reopening exams for institutions.",
        "right_lesson": "Fun fact: Crisis protocols reduce emotional decision errors.",
        "card_band_color": "steel_blue",
        "value_min": 2.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.25, "inflation": -0.15, "greed": -0.2, "volatility": 0.5, "fundamentals": -0.15},
    },
    {
        "card_id": "GDP_V_008",
        "type": "event",
        "title": "Currency Devaluation Abroad",
        "body": "A major trading partner devalues its currency by {value}%, shifting competitiveness quickly.",
        "emoji": "\ud83d\udcb1",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "asset_allocation"],
        "linked_traits": ["diversification_bias", "overconfidence"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Ignore FX risk entirely",
        "right_choice": "Rebalance international exposure",
        "left_lesson": "Fun fact: Competitive devaluations were common during the interwar period.",
        "right_lesson": "Fun fact: Currency shifts can dominate equity returns in stressed regimes.",
        "card_band_color": "purple",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 0.9,
        "weights": {"sentiment": -0.1, "inflation": 0.05, "greed": -0.05, "volatility": 0.35, "fundamentals": -0.1},
    },
    {
        "card_id": "GDP_V_009",
        "type": "event",
        "title": "Sovereign Debt Stress",
        "body": "A European country signals debt repayment risk, pushing bond spreads up {value} bps.",
        "emoji": "\ud83d\udcc3",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "bonds"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Chase yield despite stress",
        "right_choice": "Prioritize credit quality",
        "left_lesson": "Fun fact: Sovereign and banking stress reinforced each other in 1930s Europe.",
        "right_lesson": "Fun fact: Credit quality discipline matters most during regime breaks.",
        "card_band_color": "amber",
        "value_min": 100.0,
        "value_max": 700.0,
        "value_step": 100.0,
        "alpha": 1.05,
        "weights": {"sentiment": -0.2, "inflation": -0.05, "greed": -0.1, "volatility": 0.45, "fundamentals": -0.3},
    },
    {
        "card_id": "GDP_V_010",
        "type": "event",
        "title": "Policy Tightening Too Soon",
        "body": "Officials tighten financial conditions and markets retrace {value}% after an early recovery.",
        "emoji": "\ud83d\udee0\ufe0f",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "market_timing"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Buy every dip immediately",
        "right_choice": "Wait for policy clarity",
        "left_lesson": "Fun fact: The 1937-38 downturn hit after policy tightening during a fragile recovery.",
        "right_lesson": "Fun fact: Macro policy pivots can reset valuations faster than narratives.",
        "card_band_color": "red",
        "value_min": 8.0,
        "value_max": 25.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.25, "inflation": -0.05, "greed": 0.0, "volatility": 0.5, "fundamentals": -0.2},
    },

    {
        "card_id": "GDP_A_001",
        "type": "action",
        "title": "Cut Margin Exposure",
        "body": "You can cut leverage now and lock in losses, or hold and hope prices recover before another drop.",
        "emoji": "\ud83e\uddef",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "risk_return"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.25,
        "cooldown": 5,
        "left_choice": "Hold leverage and pray",
        "right_choice": "Deleverage now",
        "left_lesson": "Fun fact: In deep drawdowns, leverage is often the difference between surviving and failing.",
        "right_lesson": "Fun fact: Risk control is a return strategy over long horizons.",
        "card_band_color": "red",
        "alpha": 1.25,
        "weights": {"sentiment": -0.25, "inflation": 0.0, "greed": 0.25, "volatility": 0.65, "fundamentals": -0.1},
    },
    {
        "card_id": "GDP_A_002",
        "type": "action",
        "title": "Build Emergency Liquidity",
        "body": "Raise cash buffers for {value} months of expenses before making new risky bets.",
        "emoji": "\ud83d\udcb5",
        "stage_min": 1,
        "stage_max": 3,
        "topics": ["great_depression", "saving_vs_investing"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Stay fully invested",
        "right_choice": "Build liquidity first",
        "left_lesson": "Fun fact: Liquidity shortages forced many investors to sell at cycle lows.",
        "right_lesson": "Fun fact: Cash reserves create optionality when markets panic.",
        "card_band_color": "green",
        "value_min": 3.0,
        "value_max": 9.0,
        "value_step": 1.0,
        "alpha": 0.8,
        "weights": {"sentiment": 0.05, "inflation": -0.05, "greed": -0.2, "volatility": -0.2, "fundamentals": 0.1},
    },
    {
        "card_id": "GDP_A_003",
        "type": "action",
        "title": "Rebalance Away from Mania",
        "body": "Trim overheated names and move into diversified holdings despite social pressure.",
        "emoji": "\ud83d\udee1\ufe0f",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "rebalancing"],
        "linked_traits": ["fomo_sensitivity", "diversification_bias"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Ride the hottest names",
        "right_choice": "Rebalance discipline",
        "left_lesson": "Fun fact: Concentrated speculative positions were crushed in 1929-1932.",
        "right_lesson": "Fun fact: Rebalancing sells expensive risk and buys neglected value.",
        "card_band_color": "steel_blue",
        "alpha": 0.95,
        "weights": {"sentiment": -0.05, "inflation": 0.0, "greed": -0.3, "volatility": -0.1, "fundamentals": 0.2},
    },
    {
        "card_id": "GDP_A_004",
        "type": "action",
        "title": "Refinance High-Cost Debt",
        "body": "Restructure expensive debt now, even if it means temporary spending cuts.",
        "emoji": "\ud83d\udcdc",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "opportunity_cost"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Delay debt cleanup",
        "right_choice": "Fix debt structure now",
        "left_lesson": "Fun fact: Debt-deflation made balance sheet repair central to survival.",
        "right_lesson": "Fun fact: Lower fixed obligations increase resilience in downturns.",
        "card_band_color": "amber",
        "alpha": 0.85,
        "weights": {"sentiment": 0.0, "inflation": -0.1, "greed": -0.1, "volatility": -0.05, "fundamentals": 0.25},
    },
    {
        "card_id": "GDP_A_005",
        "type": "action",
        "title": "Dollar-Cost Average Through Fear",
        "body": "Commit to fixed monthly investing for {value} months despite headlines.",
        "emoji": "\ud83d\uddd3\ufe0f",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "dca"],
        "linked_traits": ["patience", "panic_selling"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Wait for perfect bottom",
        "right_choice": "Automate contributions",
        "left_lesson": "Fun fact: Waiting for certainty often misses the strongest rebound periods.",
        "right_lesson": "Fun fact: Mechanical investing can reduce behavior-driven timing errors.",
        "card_band_color": "green",
        "value_min": 6.0,
        "value_max": 24.0,
        "value_step": 3.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": -0.15, "volatility": -0.1, "fundamentals": 0.2},
    },
    {
        "card_id": "GDP_A_006",
        "type": "action",
        "title": "Avoid Rumor Trading",
        "body": "A newspaper rumor promises quick recovery. You can chase it or stick to verified data.",
        "emoji": "\ud83d\udcf0",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "overtrading"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.5,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Trade on rumor",
        "right_choice": "Wait for confirmation",
        "left_lesson": "Fun fact: Rumor-driven spikes were common in crisis-era tape reading.",
        "right_lesson": "Fun fact: Verification discipline improves decision quality under stress.",
        "card_band_color": "purple",
        "alpha": 0.8,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": 0.2, "volatility": 0.2, "fundamentals": -0.1},
    },
    {
        "card_id": "GDP_A_007",
        "type": "action",
        "title": "Hold a Diversified Core",
        "body": "Keep broad exposure even while parts of the market collapse unevenly.",
        "emoji": "\ud83e\udef6",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "diversification"],
        "linked_traits": ["diversification_bias", "loss_aversion"],
        "difficulty": 0.45,
        "diagnostic_power": 0.7,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Concentrate in one safe sector",
        "right_choice": "Maintain broad exposure",
        "left_lesson": "Fun fact: Sector leadership changed repeatedly during and after the Depression.",
        "right_lesson": "Fun fact: Diversification reduces single-theme failure risk.",
        "card_band_color": "steel_blue",
        "alpha": 0.8,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.1, "volatility": -0.15, "fundamentals": 0.15},
    },
    {
        "card_id": "GDP_A_008",
        "type": "action",
        "title": "Focus on Cash-Flow Assets",
        "body": "Rotate toward businesses with durable cash flows rather than speculative narratives.",
        "emoji": "\ud83d\udcb8",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "stocks"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Chase turnaround stories",
        "right_choice": "Buy cash-flow durability",
        "left_lesson": "Fun fact: Quality balance sheets historically outlast deep downturns.",
        "right_lesson": "Fun fact: Survivors with cash generation often lead later recoveries.",
        "card_band_color": "green",
        "alpha": 1.0,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": -0.2, "volatility": -0.1, "fundamentals": 0.3},
    },
    {
        "card_id": "GDP_A_009",
        "type": "action",
        "title": "Stagger Bond Maturities",
        "body": "Build a bond ladder to reduce reinvestment and liquidity timing risk.",
        "emoji": "\ud83d\udcd1",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "bonds"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Single maturity only",
        "right_choice": "Use maturity ladder",
        "left_lesson": "Fun fact: Laddering can smooth cash flow needs in unstable rate regimes.",
        "right_lesson": "Fun fact: Structure often matters more than yield headline.",
        "card_band_color": "amber",
        "alpha": 0.85,
        "weights": {"sentiment": 0.05, "inflation": -0.05, "greed": -0.1, "volatility": -0.2, "fundamentals": 0.15},
    },
    {
        "card_id": "GDP_A_010",
        "type": "action",
        "title": "Write an Investment Rulebook",
        "body": "Before the next panic, define your rebalancing, risk, and exit rules in writing.",
        "emoji": "\ud83d\udcd8",
        "stage_min": 1,
        "stage_max": 5,
        "topics": ["great_depression", "consistency"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.4,
        "diagnostic_power": 0.75,
        "base_priority": 1.0,
        "cooldown": 7,
        "left_choice": "Rely on instinct",
        "right_choice": "Use rulebook discipline",
        "left_lesson": "Fun fact: Crisis decisions made without precommitment are often emotional and inconsistent.",
        "right_lesson": "Fun fact: Written playbooks improve repeatability and reduce panic actions.",
        "card_band_color": "steel_blue",
        "alpha": 0.7,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.1, "volatility": -0.15, "fundamentals": 0.15},
    },

    {
        "card_id": "GDP_X_001",
        "type": "event",
        "title": "Vienna Banking Shock",
        "body": "A major Austrian bank failure triggers fear across European markets.",
        "emoji": "\ud83c\udde6\ud83c\uddf9",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "volatility"],
        "linked_traits": ["diversification_bias", "loss_aversion"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Ignore global banking links",
        "right_choice": "Reduce cross-border exposure risk",
        "left_lesson": "Fun fact: Credit stress in one center can spread through confidence channels fast.",
        "right_lesson": "Fun fact: Contagion management is a core macro investing skill.",
        "card_band_color": "purple",
        "alpha": 0.95,
        "weights": {"sentiment": -0.2, "inflation": -0.05, "greed": -0.1, "volatility": 0.45, "fundamentals": -0.2},
    },
    {
        "card_id": "GDP_X_002",
        "type": "event",
        "title": "German Credit Freeze",
        "body": "Credit conditions tighten sharply and trade finance dries up.",
        "emoji": "\ud83c\udde9\ud83c\uddea",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "bonds"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Reach for risky credit",
        "right_choice": "Favor high-quality liquidity",
        "left_lesson": "Fun fact: Liquidity risk often appears before default risk in crisis transitions.",
        "right_lesson": "Fun fact: Quality and optionality become expensive for a reason.",
        "card_band_color": "amber",
        "alpha": 1.0,
        "weights": {"sentiment": -0.25, "inflation": -0.05, "greed": -0.05, "volatility": 0.5, "fundamentals": -0.25},
    },
    {
        "card_id": "GDP_X_003",
        "type": "education",
        "title": "Canada and Commodity Demand",
        "body": "Commodity-linked economies were hit as global demand and prices collapsed.",
        "emoji": "\ud83c\udde8\ud83c\udde6",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "asset_allocation"],
        "linked_traits": ["diversification_bias", "patience"],
        "difficulty": 0.4,
        "diagnostic_power": 0.7,
        "base_priority": 1.0,
        "cooldown": 7,
        "left_choice": "Commodities are always hedge",
        "right_choice": "Demand cycles drive outcomes",
        "left_lesson": "Fun fact: Commodity exporters faced deep stress when industrial demand fell.",
        "right_lesson": "Fun fact: Asset class labels do not replace cycle analysis.",
        "card_band_color": "steel_blue",
        "alpha": 0.75,
        "weights": {"sentiment": -0.1, "inflation": -0.1, "greed": -0.05, "volatility": 0.2, "fundamentals": -0.15},
    },
    {
        "card_id": "GDP_X_004",
        "type": "education",
        "title": "Latin American Debt Strain",
        "body": "Falling export revenues made external debt harder to service across several countries.",
        "emoji": "\ud83c\udf0e",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "opportunity_cost"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Ignore external debt loads",
        "right_choice": "Monitor debt-service capacity",
        "left_lesson": "Fun fact: External financing stops can trigger prolonged domestic contractions.",
        "right_lesson": "Fun fact: Balance-of-payments risk matters for international allocations.",
        "card_band_color": "purple",
        "alpha": 0.9,
        "weights": {"sentiment": -0.15, "inflation": -0.05, "greed": -0.05, "volatility": 0.3, "fundamentals": -0.25},
    },
    {
        "card_id": "GDP_X_005",
        "type": "education",
        "title": "Japan and Silk Collapse",
        "body": "Demand shocks in global textiles hurt export income and domestic stability.",
        "emoji": "\ud83c\uddef\ud83c\uddf5",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["great_depression", "market_growth"],
        "linked_traits": ["diversification_bias", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.7,
        "base_priority": 1.0,
        "cooldown": 7,
        "left_choice": "Sector demand never shifts",
        "right_choice": "Export dependence is a risk",
        "left_lesson": "Fun fact: Concentration in one export chain can magnify macro shocks.",
        "right_lesson": "Fun fact: Demand geography can be as important as production efficiency.",
        "card_band_color": "amber",
        "alpha": 0.8,
        "weights": {"sentiment": -0.1, "inflation": -0.05, "greed": -0.05, "volatility": 0.2, "fundamentals": -0.15},
    },

    {
        "card_id": "GDP_Z_001",
        "type": "action",
        "title": "Test Your Bear Market Plan",
        "body": "Run a stress test assuming another {value}% drawdown before recovery.",
        "emoji": "\ud83e\uddea",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "volatility"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Skip stress testing",
        "right_choice": "Adjust before crisis hits",
        "left_lesson": "Fun fact: Many failures come from liquidity mismatch, not wrong long-term thesis.",
        "right_lesson": "Fun fact: Scenario planning improves survival odds in nonlinear downturns.",
        "card_band_color": "steel_blue",
        "value_min": 20.0,
        "value_max": 50.0,
        "value_step": 5.0,
        "alpha": 0.95,
        "weights": {"sentiment": -0.1, "inflation": 0.0, "greed": -0.1, "volatility": 0.25, "fundamentals": 0.1},
    },
    {
        "card_id": "GDP_Z_002",
        "type": "event",
        "title": "Headline: Recovery Rally",
        "body": "Markets jump {value}% in a week after policy rumors. Trend or trap?",
        "emoji": "\ud83d\udce2",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["great_depression", "market_timing"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Chase immediately",
        "right_choice": "Scale in gradually",
        "left_lesson": "Fun fact: Bear markets can contain sharp countertrend rallies.",
        "right_lesson": "Fun fact: Position sizing discipline reduces regret in uncertain turns.",
        "card_band_color": "green",
        "value_min": 8.0,
        "value_max": 25.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": 0.3, "inflation": 0.0, "greed": 0.3, "volatility": 0.35, "fundamentals": 0.05},
    },
    {
        "card_id": "GDP_Z_003",
        "type": "action",
        "title": "Preserve Optionality",
        "body": "Keep dry powder rather than fully committing capital in one week.",
        "emoji": "\ud83c\udfaf",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["great_depression", "opportunity_cost"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Go all-in now",
        "right_choice": "Keep optionality",
        "left_lesson": "Fun fact: Optionality has value when volatility is high and outcomes are wide.",
        "right_lesson": "Fun fact: Staged entry helps when information quality is poor.",
        "card_band_color": "amber",
        "alpha": 0.8,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.1, "volatility": -0.05, "fundamentals": 0.1},
    },
    {
        "card_id": "GDP_Z_004",
        "type": "education",
        "title": "FDIC and Trust",
        "body": "Deposit insurance changed household behavior by reducing run incentives.",
        "emoji": "\ud83d\udee1\ufe0f",
        "stage_min": 1,
        "stage_max": 4,
        "topics": ["great_depression", "consistency"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.35,
        "diagnostic_power": 0.7,
        "base_priority": 1.0,
        "cooldown": 7,
        "left_choice": "Institutions never shape behavior",
        "right_choice": "Rules can stabilize systems",
        "left_lesson": "Fun fact: After insurance reforms, US bank runs dropped materially.",
        "right_lesson": "Fun fact: Good market design can reduce panic externalities.",
        "card_band_color": "green",
        "alpha": 0.7,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": -0.05, "volatility": -0.15, "fundamentals": 0.2},
    },
    {
        "card_id": "GDP_Z_005",
        "type": "education",
        "title": "Lessons for Modern Investors",
        "body": "The Depression shows that leverage, concentration, and panic can be fatal. Process beats prediction.",
        "emoji": "\ud83e\udded",
        "stage_min": 1,
        "stage_max": 5,
        "topics": ["great_depression", "consistency"],
        "linked_traits": ["patience", "diversification_bias"],
        "difficulty": 0.3,
        "diagnostic_power": 0.8,
        "base_priority": 1.0,
        "cooldown": 8,
        "left_choice": "History is irrelevant",
        "right_choice": "Use history as risk guide",
        "left_lesson": "Fun fact: The biggest investing mistakes repeat across generations with new narratives.",
        "right_lesson": "Fun fact: A disciplined framework can outperform brilliant forecasts over time.",
        "card_band_color": "steel_blue",
        "alpha": 0.75,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": -0.15, "volatility": -0.1, "fundamentals": 0.2},
    },
]
