"""COVID and post-COVID era themed deck cards (shop deck)."""

COVID_ERA_CARDS = [
    {
        "card_id": "CVD_E_001",
        "type": "education",
        "title": "Global Shutdown Shock",
        "body": "In early 2020, lockdowns froze travel, retail, and services almost overnight. Liquidity and risk management became immediate priorities.",
        "emoji": "🦠",
        "stage_min": 1,
        "stage_max": 3,
        "topics": ["covid", "volatility"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.35,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "Crises are always short",
        "right_choice": "Stress test before certainty",
        "left_lesson": "Fun fact: Multiple major equity indices fell into bear market territory in weeks.",
        "right_lesson": "Fun fact: Liquidity planning often matters before return optimization in sudden shocks.",
        "card_band_color": "red",
        "alpha": 0.9,
        "weights": {"sentiment": -0.45, "inflation": -0.1, "greed": -0.25, "volatility": 0.8, "fundamentals": -0.3},
    },
    {
        "card_id": "CVD_E_002",
        "type": "education",
        "title": "Circuit Breakers",
        "body": "Trading halts are designed to pause panic selling. They reduce speed, not uncertainty.",
        "emoji": "⛔",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["covid", "market_timing"],
        "linked_traits": ["panic_selling", "overconfidence"],
        "difficulty": 0.4,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 7,
        "left_choice": "Halts remove risk",
        "right_choice": "Halts buy decision time",
        "left_lesson": "Fun fact: US market-wide circuit breakers triggered repeatedly during March 2020.",
        "right_lesson": "Fun fact: Market structure tools can slow cascades, but they cannot fix fundamentals.",
        "card_band_color": "steel_blue",
        "alpha": 0.8,
        "weights": {"sentiment": -0.2, "inflation": 0.0, "greed": -0.1, "volatility": 0.45, "fundamentals": -0.1},
    },
    {
        "card_id": "CVD_E_003",
        "type": "education",
        "title": "Fiscal Stimulus Wave",
        "body": "Governments injected cash through checks, unemployment support, and business aid to stabilize demand.",
        "emoji": "💸",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "market_growth"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 7,
        "left_choice": "Policy has little effect",
        "right_choice": "Policy can change regimes",
        "left_lesson": "Fun fact: Fiscal transfers supported household balance sheets despite recession.",
        "right_lesson": "Fun fact: Large coordinated policy can accelerate recovery expectations.",
        "card_band_color": "green",
        "alpha": 0.85,
        "weights": {"sentiment": 0.25, "inflation": 0.2, "greed": 0.1, "volatility": -0.05, "fundamentals": 0.3},
    },
    {
        "card_id": "CVD_E_004",
        "type": "education",
        "title": "Central Bank Backstop",
        "body": "Emergency rate cuts and asset purchases helped restore funding markets and confidence.",
        "emoji": "🏦",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "bonds"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 7,
        "left_choice": "Ignore liquidity policy",
        "right_choice": "Track funding conditions",
        "left_lesson": "Fun fact: Credit spreads narrowed after aggressive central bank interventions.",
        "right_lesson": "Fun fact: Liquidity support can stop forced selling loops.",
        "card_band_color": "amber",
        "alpha": 0.9,
        "weights": {"sentiment": 0.2, "inflation": 0.15, "greed": 0.05, "volatility": -0.15, "fundamentals": 0.25},
    },
    {
        "card_id": "CVD_E_005",
        "type": "education",
        "title": "Work-From-Home Shift",
        "body": "Remote work accelerated software, cloud, and collaboration demand while hurting office-dependent sectors.",
        "emoji": "💻",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["covid", "stocks"],
        "linked_traits": ["diversification_bias", "fomo_sensitivity"],
        "difficulty": 0.4,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 7,
        "left_choice": "One trend wins forever",
        "right_choice": "Regimes rotate over time",
        "left_lesson": "Fun fact: Pandemic winners can underperform once conditions normalize.",
        "right_lesson": "Fun fact: Trend investing works best with disciplined rebalancing.",
        "card_band_color": "purple",
        "alpha": 0.8,
        "weights": {"sentiment": 0.2, "inflation": 0.05, "greed": 0.25, "volatility": 0.2, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_E_006",
        "type": "education",
        "title": "Supply Chain Fragility",
        "body": "Factory closures and logistics bottlenecks reduced supply, setting up later price pressure.",
        "emoji": "🚢",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "inflation"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "Supply shocks are brief",
        "right_choice": "Bottlenecks can persist",
        "left_lesson": "Fun fact: Shipping and input shortages lasted longer than many forecasts expected.",
        "right_lesson": "Fun fact: Inflation can emerge from supply constraints even before demand fully normalizes.",
        "card_band_color": "red",
        "alpha": 0.9,
        "weights": {"sentiment": -0.05, "inflation": 0.55, "greed": 0.0, "volatility": 0.3, "fundamentals": -0.1},
    },
    {
        "card_id": "CVD_E_007",
        "type": "education",
        "title": "Retail Trading Surge",
        "body": "Lockdowns and easy apps brought millions of new traders into markets, increasing momentum behavior.",
        "emoji": "📱",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["covid", "overtrading"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Crowd activity is always smart",
        "right_choice": "Volume is not valuation",
        "left_lesson": "Fun fact: High social attention often coincides with higher realized volatility.",
        "right_lesson": "Fun fact: Participation booms can improve liquidity but also amplify swings.",
        "card_band_color": "purple",
        "alpha": 0.85,
        "weights": {"sentiment": 0.25, "inflation": 0.0, "greed": 0.45, "volatility": 0.45, "fundamentals": 0.0},
    },
    {
        "card_id": "CVD_E_008",
        "type": "education",
        "title": "Vaccine Reopening",
        "body": "Reopening expectations rotated leadership toward travel, energy, and cyclical sectors.",
        "emoji": "💉",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "market_growth"],
        "linked_traits": ["risk_appetite", "diversification_bias"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 6,
        "left_choice": "Leaders never rotate",
        "right_choice": "Recovery rotates winners",
        "left_lesson": "Fun fact: Reopening periods often reward laggard cyclicals over prior defensives.",
        "right_lesson": "Fun fact: Sector rotation is a common feature of early-cycle rebounds.",
        "card_band_color": "green",
        "alpha": 0.9,
        "weights": {"sentiment": 0.35, "inflation": 0.15, "greed": 0.2, "volatility": 0.05, "fundamentals": 0.3},
    },
    {
        "card_id": "CVD_E_009",
        "type": "education",
        "title": "Post-COVID Economic Boom",
        "body": "Pent-up demand plus reopening produced a sharp growth rebound in many economies.",
        "emoji": "📈",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "market_growth"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 6,
        "left_choice": "Booms are fake signals",
        "right_choice": "Recoveries can be real",
        "left_lesson": "Fun fact: GDP growth rebounded strongly in multiple regions after deep contractions.",
        "right_lesson": "Fun fact: Early-cycle booms can coexist with high uncertainty.",
        "card_band_color": "green",
        "alpha": 0.9,
        "weights": {"sentiment": 0.4, "inflation": 0.2, "greed": 0.2, "volatility": -0.05, "fundamentals": 0.35},
    },
    {
        "card_id": "CVD_E_010",
        "type": "education",
        "title": "Inflation After Reopening",
        "body": "Demand rebounded faster than supply, creating broad inflation pressure during the post-COVID period.",
        "emoji": "🔥",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "inflation"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Inflation is always temporary",
        "right_choice": "Watch persistence carefully",
        "left_lesson": "Fun fact: Inflation persistence can surprise when labor and supply constraints overlap.",
        "right_lesson": "Fun fact: Regime shifts often require different portfolio mixes.",
        "card_band_color": "red",
        "alpha": 1.0,
        "weights": {"sentiment": -0.05, "inflation": 0.75, "greed": 0.05, "volatility": 0.3, "fundamentals": 0.0},
    },
    {
        "card_id": "CVD_E_011",
        "type": "education",
        "title": "Rate Hike Cycle",
        "body": "Central banks tightened policy to fight inflation, repricing both stocks and bonds.",
        "emoji": "📉",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "bonds"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Ignore rate sensitivity",
        "right_choice": "Reprice duration risk",
        "left_lesson": "Fun fact: Long-duration assets tend to be most sensitive to fast rate moves.",
        "right_lesson": "Fun fact: Policy tightening can end one boom narrative and start another regime.",
        "card_band_color": "amber",
        "alpha": 1.0,
        "weights": {"sentiment": -0.2, "inflation": -0.2, "greed": -0.1, "volatility": 0.45, "fundamentals": -0.05},
    },
    {
        "card_id": "CVD_E_012",
        "type": "education",
        "title": "AI and Productivity Optimism",
        "body": "Post-COVID digitization and AI narratives fueled a new wave of growth optimism.",
        "emoji": "🤖",
        "stage_min": 4,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "stocks"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Narratives are enough",
        "right_choice": "Narratives need earnings",
        "left_lesson": "Fun fact: Narrative-driven rallies can outrun fundamentals in the short term.",
        "right_lesson": "Fun fact: Sustainable bull phases eventually require cash flow delivery.",
        "card_band_color": "steel_blue",
        "alpha": 0.9,
        "weights": {"sentiment": 0.3, "inflation": 0.0, "greed": 0.35, "volatility": 0.25, "fundamentals": 0.15},
    },

    {
        "card_id": "CVD_V_001",
        "type": "event",
        "title": "Emergency Lockdown",
        "body": "Your region enters a {value}-week lockdown and service-sector revenues collapse.",
        "emoji": "🚨",
        "stage_min": 1,
        "stage_max": 3,
        "topics": ["covid", "volatility"],
        "linked_traits": ["loss_aversion", "panic_selling"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Sell everything now",
        "right_choice": "Rebalance by risk budget",
        "left_lesson": "Fun fact: Panic liquidations often happen near local volatility peaks.",
        "right_lesson": "Fun fact: Predefined risk budgets reduce emotional drawdown decisions.",
        "card_band_color": "red",
        "value_min": 2.0,
        "value_max": 12.0,
        "value_step": 2.0,
        "alpha": 1.15,
        "weights": {"sentiment": -0.55, "inflation": -0.05, "greed": -0.25, "volatility": 0.85, "fundamentals": -0.35},
    },
    {
        "card_id": "CVD_V_002",
        "type": "event",
        "title": "Supply Chain Delay",
        "body": "Lead times rise by {value}% and manufacturers warn of missed deliveries.",
        "emoji": "📦",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "inflation"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Assume no pricing impact",
        "right_choice": "Adjust for cost pressure",
        "left_lesson": "Fun fact: Delays and shortages can widen margin volatility across sectors.",
        "right_lesson": "Fun fact: Input constraints can move inflation before demand data does.",
        "card_band_color": "amber",
        "value_min": 10.0,
        "value_max": 60.0,
        "value_step": 10.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.1, "inflation": 0.6, "greed": 0.0, "volatility": 0.35, "fundamentals": -0.1},
    },
    {
        "card_id": "CVD_V_003",
        "type": "event",
        "title": "Stimulus Check Arrival",
        "body": "Household disposable cash rises by {value}% this quarter after fiscal transfers.",
        "emoji": "🧾",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["covid", "market_growth"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Ignore demand boost",
        "right_choice": "Expect cyclical rebound",
        "left_lesson": "Fun fact: Transfers can quickly affect retail demand and earnings expectations.",
        "right_lesson": "Fun fact: Policy impulse can matter as much as valuation in recoveries.",
        "card_band_color": "green",
        "value_min": 2.0,
        "value_max": 15.0,
        "value_step": 1.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.3, "inflation": 0.15, "greed": 0.15, "volatility": -0.05, "fundamentals": 0.25},
    },
    {
        "card_id": "CVD_V_004",
        "type": "event",
        "title": "Vaccine Efficacy Surprise",
        "body": "Trial data beats expectations and reopening-sensitive stocks jump {value}%.",
        "emoji": "🧪",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "stocks"],
        "linked_traits": ["fomo_sensitivity", "risk_appetite"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Chase with full size",
        "right_choice": "Scale in by plan",
        "left_lesson": "Fun fact: Good news gaps can reverse if position sizing ignores volatility.",
        "right_lesson": "Fun fact: Staged entries reduce regret in high-velocity regime shifts.",
        "card_band_color": "green",
        "value_min": 8.0,
        "value_max": 35.0,
        "value_step": 1.0,
        "alpha": 1.05,
        "weights": {"sentiment": 0.5, "inflation": 0.1, "greed": 0.3, "volatility": 0.15, "fundamentals": 0.35},
    },
    {
        "card_id": "CVD_V_005",
        "type": "event",
        "title": "Reopening Travel Surge",
        "body": "Passenger demand rebounds {value}% year-over-year as restrictions ease.",
        "emoji": "✈️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "market_growth"],
        "linked_traits": ["risk_appetite", "diversification_bias"],
        "difficulty": 0.5,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Treat it as noise",
        "right_choice": "Account for demand snapback",
        "left_lesson": "Fun fact: Reopening phases often produce sharp base-effect growth rates.",
        "right_lesson": "Fun fact: Service recovery can materially lift employment and earnings.",
        "card_band_color": "steel_blue",
        "value_min": 20.0,
        "value_max": 120.0,
        "value_step": 10.0,
        "alpha": 1.0,
        "weights": {"sentiment": 0.35, "inflation": 0.1, "greed": 0.2, "volatility": 0.0, "fundamentals": 0.3},
    },
    {
        "card_id": "CVD_V_006",
        "type": "event",
        "title": "Shipping Cost Spike",
        "body": "Freight costs jump {value}% and import-heavy businesses warn on margins.",
        "emoji": "🚚",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "inflation"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Ignore margin risk",
        "right_choice": "Reassess cost-sensitive sectors",
        "left_lesson": "Fun fact: Transport costs can flow into consumer prices with a lag.",
        "right_lesson": "Fun fact: Input shocks often create winners and losers across industries.",
        "card_band_color": "red",
        "value_min": 20.0,
        "value_max": 200.0,
        "value_step": 20.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.05, "inflation": 0.65, "greed": 0.0, "volatility": 0.3, "fundamentals": -0.05},
    },
    {
        "card_id": "CVD_V_007",
        "type": "event",
        "title": "Variant Headlines",
        "body": "A new variant triggers a {value}% risk-off move in reopening-sensitive sectors.",
        "emoji": "🧬",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "volatility"],
        "linked_traits": ["panic_selling", "fomo_sensitivity"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Trade headlines instantly",
        "right_choice": "Wait for data confirmation",
        "left_lesson": "Fun fact: Headline-first trading can overreact before hard data arrives.",
        "right_lesson": "Fun fact: Confirmation filters reduce false-signal turnover.",
        "card_band_color": "purple",
        "value_min": 5.0,
        "value_max": 22.0,
        "value_step": 1.0,
        "alpha": 1.05,
        "weights": {"sentiment": -0.3, "inflation": 0.0, "greed": -0.1, "volatility": 0.55, "fundamentals": -0.1},
    },
    {
        "card_id": "CVD_V_008",
        "type": "event",
        "title": "Employment Rebound",
        "body": "Payroll growth surprises by {value} jobs, lifting confidence in recovery durability.",
        "emoji": "🧰",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "market_growth"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Assume one print is trend",
        "right_choice": "Track trend over months",
        "left_lesson": "Fun fact: Single data releases are noisy and frequently revised.",
        "right_lesson": "Fun fact: Multi-month confirmation improves macro signal quality.",
        "card_band_color": "green",
        "value_min": 50000.0,
        "value_max": 900000.0,
        "value_step": 50000.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.3, "inflation": 0.1, "greed": 0.15, "volatility": -0.05, "fundamentals": 0.35},
    },
    {
        "card_id": "CVD_V_009",
        "type": "event",
        "title": "Rate Hike Surprise",
        "body": "Policy rate expectations reprice by {value} bps after strong inflation prints.",
        "emoji": "🏛️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "bonds"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Ignore duration exposure",
        "right_choice": "Trim duration risk",
        "left_lesson": "Fun fact: Fast yield repricing can pressure both growth stocks and long bonds.",
        "right_lesson": "Fun fact: Duration management is a core lever in tightening cycles.",
        "card_band_color": "amber",
        "value_min": 25.0,
        "value_max": 150.0,
        "value_step": 25.0,
        "alpha": 1.1,
        "weights": {"sentiment": -0.25, "inflation": -0.15, "greed": -0.05, "volatility": 0.45, "fundamentals": 0.0},
    },
    {
        "card_id": "CVD_V_010",
        "type": "event",
        "title": "Consumer Spending Boom",
        "body": "Discretionary spending rises {value}% as households deploy accumulated savings.",
        "emoji": "🛍️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "market_growth"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Treat as one-off noise",
        "right_choice": "Model demand normalization",
        "left_lesson": "Fun fact: Pent-up demand can sustain spending beyond initial reopening months.",
        "right_lesson": "Fun fact: Booms fade eventually, but timing the fade is hard.",
        "card_band_color": "green",
        "value_min": 2.0,
        "value_max": 18.0,
        "value_step": 1.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.35, "inflation": 0.2, "greed": 0.2, "volatility": 0.0, "fundamentals": 0.3},
    },
    {
        "card_id": "CVD_V_011",
        "type": "event",
        "title": "Corporate Margin Squeeze",
        "body": "Input costs rise and margins compress by {value}% despite strong top-line demand.",
        "emoji": "🏭",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "stocks"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Ignore margins entirely",
        "right_choice": "Focus on pricing power",
        "left_lesson": "Fun fact: Revenue growth without margin support can still disappoint equity valuations.",
        "right_lesson": "Fun fact: Pricing power separates resilient firms in inflationary upswings.",
        "card_band_color": "red",
        "value_min": 2.0,
        "value_max": 18.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.1, "inflation": 0.25, "greed": -0.05, "volatility": 0.3, "fundamentals": 0.0},
    },
    {
        "card_id": "CVD_V_012",
        "type": "event",
        "title": "Energy Price Spike",
        "body": "Energy costs jump {value}% and inflation expectations re-accelerate.",
        "emoji": "⛽",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "inflation"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Assume no macro spillover",
        "right_choice": "Reassess inflation path",
        "left_lesson": "Fun fact: Energy shocks can quickly alter central bank expectations.",
        "right_lesson": "Fun fact: Inflation-sensitive allocations can hedge part of the shock.",
        "card_band_color": "amber",
        "value_min": 10.0,
        "value_max": 80.0,
        "value_step": 5.0,
        "alpha": 1.05,
        "weights": {"sentiment": -0.1, "inflation": 0.7, "greed": 0.0, "volatility": 0.35, "fundamentals": -0.05},
    },
    {
        "card_id": "CVD_V_013",
        "type": "event",
        "title": "Tech Earnings Beat",
        "body": "A mega-cap tech basket beats estimates by {value}%, sparking risk-on momentum.",
        "emoji": "🛰️",
        "stage_min": 4,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "stocks"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Chase after gap-up",
        "right_choice": "Wait for setup quality",
        "left_lesson": "Fun fact: Gap-up chasing tends to have weaker risk-adjusted outcomes.",
        "right_lesson": "Fun fact: Entry discipline improves expectancy even in strong trends.",
        "card_band_color": "steel_blue",
        "value_min": 3.0,
        "value_max": 25.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": 0.35, "inflation": 0.0, "greed": 0.4, "volatility": 0.2, "fundamentals": 0.2},
    },
    {
        "card_id": "CVD_V_014",
        "type": "event",
        "title": "Soft Landing Narrative",
        "body": "Markets price a soft-landing scenario with a {value}% rally in cyclical assets.",
        "emoji": "🌤️",
        "stage_min": 4,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "market_growth"],
        "linked_traits": ["overconfidence", "risk_appetite"],
        "difficulty": 0.6,
        "diagnostic_power": 0.85,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Assume no downside",
        "right_choice": "Ride trend with risk controls",
        "left_lesson": "Fun fact: Consensus narratives can flip quickly when data surprises.",
        "right_lesson": "Fun fact: Risk controls let you participate without full narrative dependence.",
        "card_band_color": "green",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 1.0,
        "alpha": 1.05,
        "weights": {"sentiment": 0.45, "inflation": -0.05, "greed": 0.3, "volatility": 0.15, "fundamentals": 0.2},
    },

    {
        "card_id": "CVD_A_001",
        "type": "action",
        "title": "Build Crisis Cash Buffer",
        "body": "Set aside {value} months of expenses before adding more cyclical risk.",
        "emoji": "💰",
        "stage_min": 1,
        "stage_max": 3,
        "topics": ["covid", "saving_vs_investing"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.4,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Stay fully exposed",
        "right_choice": "Increase liquidity safety",
        "left_lesson": "Fun fact: Insufficient cash buffers forced many investors into bad-timing sales.",
        "right_lesson": "Fun fact: Liquidity buys decision time during volatility spikes.",
        "card_band_color": "green",
        "value_min": 3.0,
        "value_max": 12.0,
        "value_step": 1.0,
        "alpha": 0.85,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.2, "volatility": -0.2, "fundamentals": 0.15},
    },
    {
        "card_id": "CVD_A_002",
        "type": "action",
        "title": "Pause Overtrading",
        "body": "Limit yourself to {value} trades per week during headline-heavy periods.",
        "emoji": "🧘",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "overtrading"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Trade every signal",
        "right_choice": "Use turnover limits",
        "left_lesson": "Fun fact: More trades can increase noise exposure without improving returns.",
        "right_lesson": "Fun fact: Turnover controls are behavior tools, not just cost tools.",
        "card_band_color": "steel_blue",
        "value_min": 1.0,
        "value_max": 8.0,
        "value_step": 1.0,
        "alpha": 0.8,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.25, "volatility": -0.1, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_003",
        "type": "action",
        "title": "Average In During Panic",
        "body": "Deploy capital in {value} tranches instead of one all-in order.",
        "emoji": "🗓️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "dca"],
        "linked_traits": ["patience", "panic_selling"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.15,
        "cooldown": 6,
        "left_choice": "All-in at once",
        "right_choice": "Use staged deployment",
        "left_lesson": "Fun fact: Single-entry timing risk is high in event-driven volatility.",
        "right_lesson": "Fun fact: Tranching can reduce emotional and timing error variance.",
        "card_band_color": "amber",
        "value_min": 2.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": -0.1, "volatility": -0.05, "fundamentals": 0.15},
    },
    {
        "card_id": "CVD_A_004",
        "type": "action",
        "title": "Reopen Rotation Basket",
        "body": "Allocate {value}% to a diversified reopening basket instead of one single theme.",
        "emoji": "🔄",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "asset_allocation"],
        "linked_traits": ["diversification_bias", "risk_appetite"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Concentrate in one stock",
        "right_choice": "Use basket exposure",
        "left_lesson": "Fun fact: Theme concentration can underperform even when the theme is right.",
        "right_lesson": "Fun fact: Baskets capture broad trend while reducing single-name tail risk.",
        "card_band_color": "green",
        "value_min": 10.0,
        "value_max": 45.0,
        "value_step": 5.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.2, "inflation": 0.1, "greed": 0.1, "volatility": -0.05, "fundamentals": 0.2},
    },
    {
        "card_id": "CVD_A_005",
        "type": "action",
        "title": "Hedge Inflation Risk",
        "body": "Shift {value}% into inflation-aware assets to cushion purchasing-power loss.",
        "emoji": "🛡️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "inflation"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Keep same allocation",
        "right_choice": "Add inflation hedges",
        "left_lesson": "Fun fact: Real return erosion compounds quickly when inflation stays elevated.",
        "right_lesson": "Fun fact: Allocation shifts can reduce inflation shock sensitivity.",
        "card_band_color": "red",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.0, "inflation": -0.25, "greed": -0.05, "volatility": -0.1, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_006",
        "type": "action",
        "title": "Trim Duration Exposure",
        "body": "Reduce long-duration fixed income by {value}% as rate risk rises.",
        "emoji": "📏",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "bonds"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Hold duration unchanged",
        "right_choice": "Shorten duration profile",
        "left_lesson": "Fun fact: Duration can dominate bond total return in tightening cycles.",
        "right_lesson": "Fun fact: Rate-risk management is as important as credit selection.",
        "card_band_color": "amber",
        "value_min": 10.0,
        "value_max": 50.0,
        "value_step": 5.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.0, "inflation": -0.1, "greed": -0.05, "volatility": -0.05, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_007",
        "type": "action",
        "title": "Rebalance Pandemic Winners",
        "body": "Trim holdings that outperformed by {value}% above target weight and recycle risk.",
        "emoji": "⚖️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "rebalancing"],
        "linked_traits": ["overconfidence", "diversification_bias"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Let winners run forever",
        "right_choice": "Return to target mix",
        "left_lesson": "Fun fact: Winners can become concentration risk after regime shifts.",
        "right_lesson": "Fun fact: Rebalancing monetizes mean reversion without predicting tops.",
        "card_band_color": "steel_blue",
        "value_min": 5.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.2, "volatility": -0.1, "fundamentals": 0.15},
    },
    {
        "card_id": "CVD_A_008",
        "type": "action",
        "title": "Limit Theme Exposure",
        "body": "Cap any single post-COVID theme at {value}% of portfolio value.",
        "emoji": "📐",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "diversification"],
        "linked_traits": ["overconfidence", "diversification_bias"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "No limits on themes",
        "right_choice": "Use concentration limits",
        "left_lesson": "Fun fact: Thematic portfolios can silently become one-factor bets.",
        "right_lesson": "Fun fact: Position caps reduce downside from narrative reversals.",
        "card_band_color": "purple",
        "value_min": 10.0,
        "value_max": 35.0,
        "value_step": 5.0,
        "alpha": 0.85,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.15, "volatility": -0.1, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_009",
        "type": "action",
        "title": "Keep a Rulebook",
        "body": "Write and follow a {value}-point trading checklist before taking any event-driven position.",
        "emoji": "📘",
        "stage_min": 1,
        "stage_max": 5,
        "topics": ["covid", "consistency"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.4,
        "diagnostic_power": 0.75,
        "base_priority": 1.0,
        "cooldown": 7,
        "left_choice": "Trade by instinct",
        "right_choice": "Use checklist discipline",
        "left_lesson": "Fun fact: Checklists reduce reaction errors in high-noise environments.",
        "right_lesson": "Fun fact: Process quality compounds like returns over repeated decisions.",
        "card_band_color": "steel_blue",
        "value_min": 3.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 0.75,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.1, "volatility": -0.15, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_010",
        "type": "action",
        "title": "Set Volatility Budget",
        "body": "Target portfolio volatility below {value}% annualized by adjusting leverage and concentration.",
        "emoji": "🎛️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "volatility"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.15,
        "cooldown": 5,
        "left_choice": "Ignore vol budgeting",
        "right_choice": "Control risk explicitly",
        "left_lesson": "Fun fact: Unmanaged volatility can force deleveraging at poor prices.",
        "right_lesson": "Fun fact: Vol budgets improve survivability through regime shifts.",
        "card_band_color": "red",
        "value_min": 8.0,
        "value_max": 30.0,
        "value_step": 2.0,
        "alpha": 1.0,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.1, "volatility": -0.35, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_011",
        "type": "action",
        "title": "Capture Reopening Upside",
        "body": "Increase cyclical allocation by {value}% but pair it with stop-loss governance.",
        "emoji": "🏙️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "stocks"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Ignore trend opportunity",
        "right_choice": "Participate with guardrails",
        "left_lesson": "Fun fact: Refusing all risk can underperform during expansion phases.",
        "right_lesson": "Fun fact: Guardrails let you join momentum without abandoning discipline.",
        "card_band_color": "green",
        "value_min": 5.0,
        "value_max": 25.0,
        "value_step": 5.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.25, "inflation": 0.1, "greed": 0.1, "volatility": 0.05, "fundamentals": 0.2},
    },
    {
        "card_id": "CVD_A_012",
        "type": "action",
        "title": "Rebuild Bond Ladder",
        "body": "Spread fixed income maturities over {value} years to reduce timing risk.",
        "emoji": "🧱",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "bonds"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.75,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "Cluster maturities",
        "right_choice": "Use ladder structure",
        "left_lesson": "Fun fact: Clustering can increase reinvestment risk in volatile rate periods.",
        "right_lesson": "Fun fact: Laddering smooths cash-flow and repricing risk.",
        "card_band_color": "amber",
        "value_min": 2.0,
        "value_max": 8.0,
        "value_step": 1.0,
        "alpha": 0.85,
        "weights": {"sentiment": 0.05, "inflation": -0.05, "greed": -0.1, "volatility": -0.15, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_013",
        "type": "action",
        "title": "Filter Narrative Trades",
        "body": "Require {value} independent data points before buying narrative-driven rallies.",
        "emoji": "🔍",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "market_timing"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Buy on headlines alone",
        "right_choice": "Demand confirmation",
        "left_lesson": "Fun fact: Narrative-only entries are vulnerable to quick sentiment reversals.",
        "right_lesson": "Fun fact: Multi-signal confirmation improves trade selectivity.",
        "card_band_color": "purple",
        "value_min": 2.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.15, "volatility": -0.05, "fundamentals": 0.1},
    },
    {
        "card_id": "CVD_A_014",
        "type": "action",
        "title": "Lock In Process Gains",
        "body": "After the boom, keep a disciplined allocation review every {value} months.",
        "emoji": "✅",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["covid", "post_covid_boom", "consistency"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.0,
        "cooldown": 7,
        "left_choice": "Stop reviews after gains",
        "right_choice": "Keep disciplined cadence",
        "left_lesson": "Fun fact: Strong returns can increase complacency risk.",
        "right_lesson": "Fun fact: Review cadence protects long-term behavior quality.",
        "card_band_color": "steel_blue",
        "value_min": 1.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 0.8,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": -0.1, "volatility": -0.1, "fundamentals": 0.15},
    },
]
