"""Seed cards aligned to the 5-stage financial literacy journey.

Card ID format: {TYPE}_{STAGE}_{NUM}  e.g. EDU_1_001, EVT_3_002, ACT_5_001
Event and action cards include value_min/max/step for dynamic value generation.
The body text uses {value} as a placeholder the game engine replaces at runtime.

alpha: simulation weight — how much this card's outcome impacts capital / persona.
  Education cards  ~0.3       (knowledge, no direct market impact)
  Action cards     0.4–1.5    (scaled by financial consequence)
  Event cards      0.5–1.8    (scaled by real-world severity; rate cuts > dips > noise)

weights: multi-dimensional impact on the simulated market state.
  sentiment    — market mood / confidence  (-1 bearish … +1 bullish)
  inflation    — inflationary pressure     (-1 deflationary … +1 inflationary)
  greed        — speculative excess        (-1 fear … +1 greed)
  volatility   — market turbulence         (-1 calm … +1 volatile)
  fundamentals — underlying economic health (-1 weak … +1 strong)
"""

from app.seeds.cards_great_depression import GREAT_DEPRESSION_CARDS
from app.seeds.cards_covid import COVID_ERA_CARDS

SEED_CARDS = [
    # ══════════════════════════════════════════════════════════════════════════
    # STAGE 1 — Foundations: Understanding Money
    # Goal: Shift mindset from saving to investing
    # Topics: inflation, opportunity_cost, saving_vs_investing, risk_return
    # ══════════════════════════════════════════════════════════════════════════
    {
        "card_id": "EDU_1_001",
        "type": "education",
        "title": "What Is Inflation?",
        "body": "Every year, prices rise and your money buys less. At **3% inflation**, $100 today is worth just **$74 in 10 years**. Storing money in cash means quietly losing wealth.",
        "emoji": "📉",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["inflation"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.15,
        "diagnostic_power": 0.65,
        "base_priority": 1.3,
        "cooldown": 8,
        "left_choice": "Savings account is safe enough",
        "right_choice": "I need to beat inflation",
        "left_lesson": "A typical savings account pays **0.5%** while inflation runs **3%**. That's a guaranteed **-2.5% real return** every year — slow financial erosion.",
        "right_lesson": "Beating inflation requires investing in assets that grow faster than prices. Stocks historically return **7–10% annually** — well above inflation.",
        "card_band_color": "amber",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.0,
            "inflation": 0.3,
            "greed": 0.0,
            "volatility": 0.05,
            "fundamentals": 0.1,
        },
    },
    {
        "card_id": "EDU_1_002",
        "type": "education",
        "title": "The Opportunity Cost of Cash",
        "body": "Every choice you make has a hidden cost: **the next-best thing you gave up**. Keeping $10,000 in cash for 10 years has a massive hidden price tag.",
        "emoji": "💡",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["opportunity_cost"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.2,
        "diagnostic_power": 0.6,
        "base_priority": 1.2,
        "cooldown": 7,
        "left_choice": "Cash feels secure",
        "right_choice": "There is always a better option",
        "left_lesson": "Feeling secure is valuable. But at **0.5% savings** vs **7% index fund return**, you give up **$9,600 over 10 years** on just $10,000.",
        "right_lesson": "Opportunity cost isn't about regret — it's a **decision framework**. Always ask: *what am I giving up by choosing this?*",
        "card_band_color": "steel_blue",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.05,
            "inflation": 0.0,
            "greed": 0.0,
            "volatility": 0.0,
            "fundamentals": 0.15,
        },
    },
    {
        "card_id": "EDU_1_003",
        "type": "education",
        "title": "Saving vs Investing",
        "body": "**Saving** means storing money safely. **Investing** means putting money to work in assets that can grow. Both are necessary — but they serve very different goals.",
        "emoji": "⚖️",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["saving_vs_investing"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.2,
        "diagnostic_power": 0.7,
        "base_priority": 1.3,
        "cooldown": 8,
        "left_choice": "Save everything — risk nothing",
        "right_choice": "Invest what I can afford to grow",
        "left_lesson": "Pure saving protects short-term needs but **guarantees long-term erosion**. 100% cash is not a neutral position — it's a losing one over decades.",
        "right_lesson": "The ideal setup: **3–6 months of expenses** in savings, everything above that invested. Safety and growth can coexist with clear goals.",
        "card_band_color": "green",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": 0.0,
            "volatility": -0.05,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "EDU_1_004",
        "type": "education",
        "title": "Risk vs Return Basics",
        "body": "Higher potential returns come with **higher risk**. A savings account guarantees **0.5%**. Stocks can return **10%** — or lose **40% in a year**. There is no free lunch.",
        "emoji": "🎯",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["risk_return"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.25,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 8,
        "left_choice": "I'll take no risk at all",
        "right_choice": "I accept some risk for real returns",
        "left_lesson": "Zero risk means **guaranteed inflation loss**. 'Safe' choices still carry risk — just a different, quieter kind.",
        "right_lesson": "Understanding your **risk tolerance** is the starting point. Not all risk is equal: time horizon and goal clarity make risk manageable.",
        "card_band_color": "amber",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.05,
            "inflation": 0.0,
            "greed": 0.05,
            "volatility": 0.1,
            "fundamentals": 0.1,
        },
    },
    {
        "card_id": "EVT_1_001",
        "type": "event",
        "title": "Inflation Spike",
        "body": "Inflation just hit **{value}%** — higher than expected. Your cash savings are **losing real value** every month. What do you do?",
        "emoji": "🔥",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["inflation"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.3,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Stay in cash — wait it out",
        "right_choice": "Move cash to inflation-beating assets",
        "left_lesson": "Waiting out inflation in cash means **guaranteed purchasing power loss**. At 8% inflation, $10,000 loses **$800 in real value** per year.",
        "right_lesson": "**TIPS, equities, and real estate** historically outpace inflation. Moving even a portion of idle cash to these is a sound response.",
        "card_band_color": "red",
        "value_min": 4.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {
            "sentiment": -0.3,
            "inflation": 0.8,
            "greed": 0.0,
            "volatility": 0.3,
            "fundamentals": -0.2,
        },
    },
    {
        "card_id": "EVT_1_002",
        "type": "event",
        "title": "Unexpected Expense",
        "body": "An emergency wipes out **{value} months of your savings**. You have no buffer left. How do you rebuild without derailing your finances?",
        "emoji": "🏥",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["saving_vs_investing"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.25,
        "diagnostic_power": 0.6,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Keep spending normally",
        "right_choice": "Cut spending until rebuilt",
        "left_lesson": "Not rebuilding an emergency fund means the next unexpected cost goes on **credit card debt** — a far more expensive problem.",
        "right_lesson": "**Automating a fixed amount** to a savings account every month is the most effective way to rebuild. Small and consistent beats large and sporadic.",
        "card_band_color": "amber",
        "value_min": 1.0,
        "value_max": 4.0,
        "value_step": 1.0,
        "alpha": 1.2,
        "weights": {
            "sentiment": -0.2,
            "inflation": 0.1,
            "greed": -0.1,
            "volatility": 0.2,
            "fundamentals": -0.3,
        },
    },
    {
        "card_id": "ACT_1_001",
        "type": "action",
        "title": "Build Your Emergency Fund",
        "body": "Financial advisors recommend **{value} months of expenses** as a cash buffer. You currently have zero saved. This is the **first step** before any investing.",
        "emoji": "🏦",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["saving_vs_investing"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.2,
        "diagnostic_power": 0.65,
        "base_priority": 1.3,
        "cooldown": 8,
        "left_choice": "Skip it — start investing directly",
        "right_choice": "Build the fund first",
        "left_lesson": "Investing before you have an emergency fund means the first major expense forces you to **sell investments at potentially the worst time**.",
        "right_lesson": "An emergency fund isn't optional — it's what lets your investments **compound without interruption**. Build it before you invest.",
        "card_band_color": "green",
        "value_min": 3.0,
        "value_max": 12.0,
        "value_step": 3.0,
        "alpha": 0.6,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": -0.1,
            "volatility": -0.15,
            "fundamentals": 0.3,
        },
    },
    {
        "card_id": "ACT_1_002",
        "type": "action",
        "title": "Move to High-Yield Savings",
        "body": "Your bank pays **0.5%** on savings. A high-yield account pays **{value}%**. Moving costs nothing and takes 30 minutes. The math is obvious — but most people don't act.",
        "emoji": "💸",
        "stage_min": 1,
        "stage_max": 1,
        "topics": ["opportunity_cost"],
        "linked_traits": ["patience"],
        "difficulty": 0.15,
        "diagnostic_power": 0.55,
        "base_priority": 1.1,
        "cooldown": 8,
        "left_choice": "Too much hassle to switch",
        "right_choice": "Move cash to better yield",
        "left_lesson": "On $20,000 in savings, the difference between **0.5% and 5%** is **$900 per year** — for doing nothing extra. Inertia is expensive.",
        "right_lesson": "**High-yield savings accounts (HYSAs)** offer near-zero risk with rates that track the Fed funds rate. It's the lowest-effort financial upgrade available.",
        "card_band_color": "green",
        "value_min": 3.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 0.4,
        "weights": {
            "sentiment": 0.05,
            "inflation": -0.1,
            "greed": 0.0,
            "volatility": -0.05,
            "fundamentals": 0.2,
        },
    },
    # ══════════════════════════════════════════════════════════════════════════
    # STAGE 2 — How Investing Works
    # Goal: Remove fear and build intuition
    # Topics: stocks, bonds, etfs, market_growth
    # ══════════════════════════════════════════════════════════════════════════
    {
        "card_id": "EDU_2_001",
        "type": "education",
        "title": "What Are Stocks?",
        "body": "A stock is a **small ownership stake** in a company. If the company grows and earns more profit, your stake becomes more valuable. You become a **fractional owner of the economy**.",
        "emoji": "📈",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["stocks"],
        "linked_traits": ["risk_appetite", "overconfidence"],
        "difficulty": 0.2,
        "diagnostic_power": 0.6,
        "base_priority": 1.3,
        "cooldown": 7,
        "left_choice": "Stocks feel like gambling",
        "right_choice": "Stocks are ownership, not speculation",
        "left_lesson": "Gambling is **zero-sum**: someone wins what another loses. Stocks are **positive-sum**: companies create real value that grows your stake over time.",
        "right_lesson": "Owning Apple stock means you own a tiny piece of **every iPhone sold**. As the company profits, so do you — through price appreciation and dividends.",
        "card_band_color": "steel_blue",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.15,
            "inflation": 0.0,
            "greed": 0.05,
            "volatility": 0.05,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "EDU_2_002",
        "type": "education",
        "title": "What Are Bonds?",
        "body": "A bond is a **loan you give** to a company or government. They pay you back with interest over a set period. **Safer than stocks** but lower returns — a trade-off by design.",
        "emoji": "🏛️",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["bonds"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.25,
        "diagnostic_power": 0.6,
        "base_priority": 1.2,
        "cooldown": 7,
        "left_choice": "Bonds seem boring",
        "right_choice": "Bonds have a clear role in portfolios",
        "left_lesson": "Boring assets serve a purpose: during the **2008 crash**, government bonds *rose* in value while stocks fell **50%**. Boring saved portfolios.",
        "right_lesson": "Bonds provide **predictable cash flow** and reduce overall portfolio volatility. In retirement especially, that stability becomes priceless.",
        "card_band_color": "steel_blue",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.0,
            "inflation": -0.1,
            "greed": -0.1,
            "volatility": -0.15,
            "fundamentals": 0.15,
        },
    },
    {
        "card_id": "EDU_2_003",
        "type": "education",
        "title": "What Are ETFs?",
        "body": "An ETF holds **many assets at once**. Buying one ETF share can expose you to **500 companies**. Instant diversification, very low cost, and no stock-picking required.",
        "emoji": "📦",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["etfs"],
        "linked_traits": ["patience", "diversification_bias"],
        "difficulty": 0.25,
        "diagnostic_power": 0.65,
        "base_priority": 1.3,
        "cooldown": 7,
        "left_choice": "I'd rather pick individual stocks",
        "right_choice": "ETFs are the smarter default",
        "left_lesson": "Individual stock picking requires skill, time, and information. **80%+ of professional stock pickers** underperform index ETFs over 15 years.",
        "right_lesson": "Vanguard's S&P 500 ETF charges **0.03%/year** and tracks 500 of the largest US companies. Most investors are better served by this than any stock.",
        "card_band_color": "green",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": -0.1,
            "volatility": -0.1,
            "fundamentals": 0.25,
        },
    },
    {
        "card_id": "EDU_2_004",
        "type": "education",
        "title": "Why Markets Grow Over Time",
        "body": "Stock markets rise long-term because **economies grow**, companies innovate, and populations drive demand. Short-term crashes are **noise**; long-term growth is the **signal**.",
        "emoji": "🌱",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["market_growth"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.3,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 7,
        "left_choice": "Past growth guarantees nothing",
        "right_choice": "Long-term growth is structurally sound",
        "left_lesson": "Past performance isn't guaranteed. But the forces behind market growth — **productivity, innovation, population** — are structural, not cyclical.",
        "right_lesson": "The S&P 500 has delivered **positive 10-year returns in every decade since 1930**, including two world wars, oil shocks, and multiple financial crises.",
        "card_band_color": "green",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.2,
            "inflation": 0.0,
            "greed": 0.0,
            "volatility": -0.05,
            "fundamentals": 0.3,
        },
    },
    {
        "card_id": "EVT_2_001",
        "type": "event",
        "title": "Market Dip",
        "body": "The market just dropped **{value}%** in a week. Financial media is calling it a crisis. You've just started investing. What do you do?",
        "emoji": "📉",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["stocks"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.35,
        "diagnostic_power": 0.75,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Sell — wait for it to stabilize",
        "right_choice": "Hold — short dips are normal",
        "left_lesson": "Selling a dip **locks in losses** and requires a perfect re-entry decision. Most investors who sell miss the subsequent recovery entirely.",
        "right_lesson": "Short-term dips are the **normal cost of long-term stock returns**. Investors who held through every dip since 1950 still earned ~10% annually.",
        "card_band_color": "red",
        "value_min": 5.0,
        "value_max": 20.0,
        "value_step": 5.0,
        "alpha": 1.0,
        "weights": {
            "sentiment": -0.5,
            "inflation": 0.0,
            "greed": -0.3,
            "volatility": 0.6,
            "fundamentals": -0.1,
        },
    },
    {
        "card_id": "EVT_2_002",
        "type": "event",
        "title": "Bond Yields Rise",
        "body": "Interest rates rise and bond yields are now **{value}%**. Existing bond prices fall. New bonds you buy will earn more. Is this **bad news or an opportunity**?",
        "emoji": "🏛️",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["bonds"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.4,
        "diagnostic_power": 0.65,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "Sell bonds — prices are falling",
        "right_choice": "Hold or buy more at higher yield",
        "left_lesson": "Selling bonds when prices fall **locks in the loss** and misses the future higher yield. Existing bonds recover at maturity regardless of interim price.",
        "right_lesson": "Rising rates hurt bond holders short term but **benefit bond buyers long term**. New bonds at higher yields generate more income going forward.",
        "card_band_color": "amber",
        "value_min": 3.0,
        "value_max": 7.0,
        "value_step": 1.0,
        "alpha": 1.4,
        "weights": {
            "sentiment": -0.1,
            "inflation": 0.4,
            "greed": 0.0,
            "volatility": 0.3,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "ACT_2_001",
        "type": "action",
        "title": "Buy Your First ETF",
        "body": "You have **${value}** ready to invest. You've decided on a broad market ETF. This is the moment — your **first real investment**. Commit or keep waiting?",
        "emoji": "🚀",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["etfs"],
        "linked_traits": ["patience", "fomo_sensitivity"],
        "difficulty": 0.25,
        "diagnostic_power": 0.65,
        "base_priority": 1.3,
        "cooldown": 7,
        "left_choice": "Wait — more research first",
        "right_choice": "Invest now and learn as you go",
        "left_lesson": "**Analysis paralysis** is one of the most expensive behaviors in personal finance. Waiting to 'know more' often means never starting.",
        "right_lesson": "The best investment is the one you **actually make**. Starting with $100 teaches more about markets than any book. *Doing is learning.*",
        "card_band_color": "green",
        "value_min": 100.0,
        "value_max": 1000.0,
        "value_step": 100.0,
        "alpha": 0.8,
        "weights": {
            "sentiment": 0.2,
            "inflation": 0.0,
            "greed": 0.1,
            "volatility": 0.0,
            "fundamentals": 0.3,
        },
    },
    {
        "card_id": "ACT_2_002",
        "type": "action",
        "title": "Set Your First Allocation",
        "body": "You're setting your first portfolio split: **{value}% equities**, the rest in bonds. Does this match your actual **risk tolerance** and time horizon?",
        "emoji": "⚖️",
        "stage_min": 2,
        "stage_max": 2,
        "topics": ["stocks"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.3,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 7,
        "left_choice": "Stay conservative with bonds",
        "right_choice": "Go heavier on stocks — I'm young",
        "left_lesson": "Conservative allocation protects against volatility but **sacrifices long-term growth**. At 25, a bond-heavy portfolio can cost hundreds of thousands by 65.",
        "right_lesson": "A common rule: **subtract your age from 110** to get your stock allocation. At 30 that's **80% stocks** — appropriate for long time horizons.",
        "card_band_color": "steel_blue",
        "value_min": 40.0,
        "value_max": 95.0,
        "value_step": 10.0,
        "alpha": 1.0,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": 0.1,
            "volatility": 0.1,
            "fundamentals": 0.25,
        },
    },
    # ══════════════════════════════════════════════════════════════════════════
    # STAGE 3 — Risk and Time
    # Goal: Build long-term thinking
    # Topics: volatility, compounding, time_horizon, market_timing
    # ══════════════════════════════════════════════════════════════════════════
    {
        "card_id": "EDU_3_001",
        "type": "education",
        "title": "Volatility Is Not Loss",
        "body": "A stock dropping **20%** feels like losing money — but it's only a loss if you sell. Temporary price swings are **volatility**. Selling at the bottom turns volatility into **permanent loss**.",
        "emoji": "📊",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["volatility"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.35,
        "diagnostic_power": 0.8,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Paper losses still feel real",
        "right_choice": "I only truly lose when I sell",
        "left_lesson": "The psychological pain of watching a portfolio drop is real, but it's **not a financial loss yet**. Reacting to feelings creates actual losses.",
        "right_lesson": "Amazon fell **90%** between 1999–2001. Investors who held recovered and went on to **100x returns**. Volatility and loss are fundamentally different things.",
        "card_band_color": "amber",
        "alpha": 0.3,
        "weights": {
            "sentiment": -0.1,
            "inflation": 0.0,
            "greed": -0.1,
            "volatility": 0.3,
            "fundamentals": 0.1,
        },
    },
    {
        "card_id": "EDU_3_002",
        "type": "education",
        "title": "The Power of Compounding",
        "body": "**$10,000** at **7%** grows to **$76,000 in 30 years** — without adding a single dollar. Returns earn returns, which earn more returns. **Time is the engine.**",
        "emoji": "✨",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["compounding"],
        "linked_traits": ["patience"],
        "difficulty": 0.3,
        "diagnostic_power": 0.7,
        "base_priority": 1.3,
        "cooldown": 7,
        "left_choice": "Small returns barely matter",
        "right_choice": "Compounding creates extraordinary wealth",
        "left_lesson": "Small percentages become enormous over time. Even **1% extra annual return** on $100,000 over 30 years is worth an extra **$74,000**.",
        "right_lesson": "The key insight: compounding requires **time**. Starting at **25 vs 35** can double the outcome by 65. Every year you wait costs more than the last.",
        "card_band_color": "green",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.15,
            "inflation": 0.0,
            "greed": 0.0,
            "volatility": -0.05,
            "fundamentals": 0.35,
        },
    },
    {
        "card_id": "EDU_3_003",
        "type": "education",
        "title": "Your Time Horizon Matters",
        "body": "If you need money in **2 years**, you can't afford much volatility. If you won't touch it for **30 years**, short-term crashes are largely irrelevant. **Time horizon drives everything.**",
        "emoji": "⏳",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["time_horizon"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.35,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Same investments for all goals",
        "right_choice": "Match investments to my timeline",
        "left_lesson": "Using a short-term money allocation for long-term goals — or vice versa — is one of the **most common and costly** investment mistakes.",
        "right_lesson": "**Emergency fund:** cash. **Goal in 2 years:** bonds. **Retirement in 30 years:** mostly stocks. Matching assets to timelines is risk management.",
        "card_band_color": "steel_blue",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.05,
            "inflation": 0.0,
            "greed": 0.0,
            "volatility": 0.0,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "EDU_3_004",
        "type": "education",
        "title": "Why Timing the Market Fails",
        "body": "Missing the **10 best days** in the S&P 500 over 20 years **cuts your returns in half**. Those best days often follow panic selloffs. Sellers miss the recovery.",
        "emoji": "🎲",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["market_timing"],
        "linked_traits": ["patience", "overconfidence", "fomo_sensitivity"],
        "difficulty": 0.45,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "I can recognize market tops",
        "right_choice": "Stay invested — timing is impossible",
        "left_lesson": "Professional fund managers with **full-time research teams** fail to time the market consistently. Retail investors succeed at timing even less often.",
        "right_lesson": "**Time in the market beats timing the market.** A $10,000 investment held 30 years outperforms 99% of tactical trading strategies, net of taxes and fees.",
        "card_band_color": "amber",
        "alpha": 0.4,
        "weights": {
            "sentiment": 0.0,
            "inflation": 0.0,
            "greed": 0.15,
            "volatility": 0.2,
            "fundamentals": 0.1,
        },
    },
    {
        "card_id": "EVT_3_001",
        "type": "event",
        "title": "Sudden Market Drop",
        "body": "Your portfolio just dropped **{value}%** this week. You've been investing for 6 months. The news is grim and your instinct is to **protect what's left**.",
        "emoji": "🔻",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["volatility"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Sell now — protect the rest",
        "right_choice": "Do nothing — stay the course",
        "left_lesson": "Selling after a large drop **guarantees that loss**. It also requires a perfect re-entry decision. Most who sell miss the recovery entirely.",
        "right_lesson": "**Every bear market in history** has been followed by a recovery to new highs. Holding through a large drop is the price of long-term returns.",
        "card_band_color": "red",
        "value_min": 10.0,
        "value_max": 35.0,
        "value_step": 5.0,
        "alpha": 1.5,
        "weights": {
            "sentiment": -0.7,
            "inflation": 0.1,
            "greed": -0.4,
            "volatility": 0.8,
            "fundamentals": -0.3,
        },
    },
    {
        "card_id": "EVT_3_002",
        "type": "event",
        "title": "Recovery Rally",
        "body": "After months of decline, markets just surged **{value}% in three weeks**. You sold at the bottom. Do you buy back in now or wait for another dip?",
        "emoji": "🚀",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["market_timing"],
        "linked_traits": ["fomo_sensitivity", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Wait — another dip is coming",
        "right_choice": "Reinvest now — stop waiting",
        "left_lesson": "The *'wait for a better entry'* mindset has **cost investors trillions**. Recoveries often accelerate rather than pause for hesitant investors.",
        "right_lesson": "Returning to the market — even after missing a rally — **produces better long-term results** than remaining in cash indefinitely.",
        "card_band_color": "amber",
        "value_min": 10.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 1.2,
        "weights": {
            "sentiment": 0.5,
            "inflation": 0.0,
            "greed": 0.4,
            "volatility": -0.2,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "ACT_3_001",
        "type": "action",
        "title": "Sell or Stay Invested?",
        "body": "Your portfolio is down **{value}%**. Your original plan said *'hold through downturns.'* Today it's emotionally hard to stick to that plan. What do you do?",
        "emoji": "🤔",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["volatility"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Sell — this time feels different",
        "right_choice": "Follow the plan — do nothing",
        "left_lesson": "*'This time is different'* is the **most expensive phrase in investing**. Every serious crash felt unprecedented. Plans exist for exactly this moment.",
        "right_lesson": "**Pre-committing to holding rules** before a crash is the most effective way to avoid panic selling. The plan you follow matters more than the plan itself.",
        "card_band_color": "red",
        "value_min": 10.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 1.4,
        "weights": {
            "sentiment": -0.4,
            "inflation": 0.0,
            "greed": -0.3,
            "volatility": 0.5,
            "fundamentals": -0.1,
        },
    },
    {
        "card_id": "ACT_3_002",
        "type": "action",
        "title": "Extend Your Investment Horizon",
        "body": "You're considering delaying a large purchase to leave your investments untouched for **{value} more years**. Does the math justify the sacrifice?",
        "emoji": "📅",
        "stage_min": 3,
        "stage_max": 3,
        "topics": ["compounding"],
        "linked_traits": ["patience"],
        "difficulty": 0.35,
        "diagnostic_power": 0.65,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "I need the money on schedule",
        "right_choice": "Extend — let compounding work",
        "left_lesson": "Some financial goals can't be postponed — and shouldn't be. The key is **matching your investment timeline to your actual goal**, not the market.",
        "right_lesson": "Even **2 extra years** at 7% on $50,000 adds over **$7,000**. Adding time to a compounding investment dramatically changes the outcome.",
        "card_band_color": "green",
        "value_min": 2.0,
        "value_max": 10.0,
        "value_step": 2.0,
        "alpha": 0.6,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": 0.0,
            "volatility": -0.1,
            "fundamentals": 0.3,
        },
    },
    # ══════════════════════════════════════════════════════════════════════════
    # STAGE 4 — Building a Portfolio
    # Goal: Translate knowledge into structure
    # Topics: diversification, asset_allocation, rebalancing, dca
    # ══════════════════════════════════════════════════════════════════════════
    {
        "card_id": "EDU_4_001",
        "type": "education",
        "title": "What Is Diversification?",
        "body": "Diversification means **spreading investments** so no single loss can ruin your portfolio. If one stock drops 50%, it matters less when it's **2% of your portfolio** than when it's **50%**.",
        "emoji": "🧩",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["diversification"],
        "linked_traits": ["diversification_bias", "overconfidence"],
        "difficulty": 0.4,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Concentrate in my best ideas",
        "right_choice": "Spread risk across many assets",
        "left_lesson": "Concentration works — until it doesn't. **Enron, Lehman Brothers, and WorldCom** were all 'sure things' before they went to zero.",
        "right_lesson": "Diversification doesn't eliminate risk — it **reduces the impact of any single failure**. A globally diversified ETF holds **4,000+ companies**.",
        "card_band_color": "steel_blue",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.05,
            "inflation": 0.0,
            "greed": -0.15,
            "volatility": -0.2,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "EDU_4_002",
        "type": "education",
        "title": "Asset Allocation 101",
        "body": "Asset allocation is how you divide your portfolio between **stocks, bonds, and cash**. It's the single most important investment decision — responsible for **~90% of your returns**.",
        "emoji": "🗂️",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["asset_allocation"],
        "linked_traits": ["risk_appetite", "diversification_bias"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "I'll just pick the best assets",
        "right_choice": "Allocation matters more than selection",
        "left_lesson": "Research shows asset allocation explains **~90% of portfolio performance variation**. Asset selection (which stocks) explains less than **5%**.",
        "right_lesson": "A clear allocation — e.g. **80% global stocks, 15% bonds, 5% cash** — gives you a decision rule for every market condition. Structure beats intuition.",
        "card_band_color": "steel_blue",
        "alpha": 0.4,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": -0.1,
            "volatility": -0.1,
            "fundamentals": 0.3,
        },
    },
    {
        "card_id": "EDU_4_003",
        "type": "education",
        "title": "When and How to Rebalance",
        "body": "Rebalancing means **selling what has grown** beyond your target allocation and **buying what has fallen** below. It forces you to sell high and buy low — automatically.",
        "emoji": "🔧",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["rebalancing"],
        "linked_traits": ["patience", "diversification_bias"],
        "difficulty": 0.45,
        "diagnostic_power": 0.7,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Let winners run — don't rebalance",
        "right_choice": "Rebalance to control risk",
        "left_lesson": "Without rebalancing, a **60/40 portfolio** can drift to **80/20** during a bull market — exposing you to far more risk than you signed up for.",
        "right_lesson": "**Annual or threshold-based rebalancing** (e.g. when any asset drifts >5%) consistently improves risk-adjusted returns over doing nothing.",
        "card_band_color": "amber",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.0,
            "inflation": 0.0,
            "greed": -0.15,
            "volatility": -0.15,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "EDU_4_004",
        "type": "education",
        "title": "Dollar-Cost Averaging",
        "body": "**DCA** means investing a **fixed amount regularly**, regardless of price. You buy more shares when prices are low, fewer when high — removing the need to time the market.",
        "emoji": "🔄",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["dca"],
        "linked_traits": ["patience", "fomo_sensitivity"],
        "difficulty": 0.35,
        "diagnostic_power": 0.7,
        "base_priority": 1.2,
        "cooldown": 6,
        "left_choice": "Wait for the perfect entry price",
        "right_choice": "Invest consistently — ignore timing",
        "left_lesson": "**Perfect entry timing is impossible** even for professionals. Waiting for 'the right time' has a documented history of costing retail investors dearly.",
        "right_lesson": "DCA investors who contributed monthly through **2008–2009** recovered faster than lump-sum investors who timed out. **Consistency compounds.**",
        "card_band_color": "green",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": -0.1,
            "volatility": -0.1,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "EVT_4_001",
        "type": "event",
        "title": "Portfolio Drifts Off Target",
        "body": "Your target was **70% stocks, 30% bonds**. Strong markets pushed stocks to **{value}%** of your portfolio. Your actual risk exposure is now **much higher than planned**.",
        "emoji": "⚠️",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["rebalancing"],
        "linked_traits": ["patience", "diversification_bias"],
        "difficulty": 0.5,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Leave it — stocks are performing",
        "right_choice": "Rebalance back to 70/30",
        "left_lesson": "Allowing drift means you hold **far more equity risk than planned**. When the crash comes, the loss will be larger than your policy ever intended.",
        "right_lesson": "Rebalancing back to your target **locks in equity gains** and reduces downside exposure. It's systematic risk management, not market timing.",
        "card_band_color": "amber",
        "value_min": 75.0,
        "value_max": 90.0,
        "value_step": 5.0,
        "alpha": 0.8,
        "weights": {
            "sentiment": 0.2,
            "inflation": 0.0,
            "greed": 0.3,
            "volatility": 0.2,
            "fundamentals": 0.1,
        },
    },
    {
        "card_id": "EVT_4_002",
        "type": "event",
        "title": "Market Correction Hits",
        "body": "A broad market correction sends your portfolio down **{value}%**. Your monthly DCA contribution is scheduled. Do you **pause or trust the process**?",
        "emoji": "📉",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["dca"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.75,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Pause — wait until it stabilizes",
        "right_choice": "Continue DCA — buying at discount",
        "left_lesson": "Pausing DCA in corrections means **missing the cheapest shares** of the cycle. Those shares bought at discount drive outsized future returns.",
        "right_lesson": "A correction means your monthly contribution **buys more shares than last month**. DCA turns corrections into systematic opportunities.",
        "card_band_color": "red",
        "value_min": 10.0,
        "value_max": 25.0,
        "value_step": 5.0,
        "alpha": 1.3,
        "weights": {
            "sentiment": -0.5,
            "inflation": 0.05,
            "greed": -0.3,
            "volatility": 0.6,
            "fundamentals": -0.15,
        },
    },
    {
        "card_id": "ACT_4_001",
        "type": "action",
        "title": "Rebalance Your Portfolio",
        "body": "Your portfolio is worth **${value}** and has drifted significantly from your target allocation. Rebalancing now triggers **taxes and transaction costs**. Do it anyway?",
        "emoji": "⚖️",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["rebalancing"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.7,
        "base_priority": 1.0,
        "cooldown": 5,
        "left_choice": "Avoid taxes — let it ride",
        "right_choice": "Rebalance — stick to the plan",
        "left_lesson": "Tax drag from rebalancing is real, but **smaller than the risk** of an unbalanced portfolio during a market crash.",
        "right_lesson": "**Tax-loss harvesting** and rebalancing inside tax-advantaged accounts (**401k, IRA**) can eliminate the tax concern entirely. Structure matters.",
        "card_band_color": "steel_blue",
        "value_min": 5000.0,
        "value_max": 50000.0,
        "value_step": 5000.0,
        "alpha": 0.9,
        "weights": {
            "sentiment": 0.0,
            "inflation": 0.0,
            "greed": -0.2,
            "volatility": -0.15,
            "fundamentals": 0.25,
        },
    },
    {
        "card_id": "ACT_4_002",
        "type": "action",
        "title": "Start a DCA Plan",
        "body": "You decide to commit **${value}/month** to your investment account automatically. This is the **most consequential financial habit** you can build.",
        "emoji": "⚙️",
        "stage_min": 4,
        "stage_max": 4,
        "topics": ["dca"],
        "linked_traits": ["patience"],
        "difficulty": 0.3,
        "diagnostic_power": 0.65,
        "base_priority": 1.2,
        "cooldown": 7,
        "left_choice": "I'll invest manually when I feel ready",
        "right_choice": "Automate it — remove the decision",
        "left_lesson": "Manual investing depends on **willpower and mood**. In market downturns — exactly when you should invest — manual investors often freeze.",
        "right_lesson": "Automated investing **removes psychology from the equation**. $200/month at 7% for 30 years grows to **$242,000**. The habit beats the amount.",
        "card_band_color": "green",
        "value_min": 50.0,
        "value_max": 500.0,
        "value_step": 50.0,
        "alpha": 0.7,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": -0.05,
            "volatility": -0.1,
            "fundamentals": 0.3,
        },
    },
    # ══════════════════════════════════════════════════════════════════════════
    # STAGE 5 — Behavioral Investing
    # Goal: Avoid common mistakes
    # Topics: panic_selling, fomo, overtrading, consistency
    # ══════════════════════════════════════════════════════════════════════════
    {
        "card_id": "EDU_5_001",
        "type": "education",
        "title": "The Danger of Panic Selling",
        "body": "Panic selling **locks in losses**, guarantees you miss the recovery, and requires a **perfect re-entry decision** you'll never make. It feels rational and almost always isn't.",
        "emoji": "😰",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["panic_selling"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.9,
        "base_priority": 1.3,
        "cooldown": 5,
        "left_choice": "Sometimes panic is the right call",
        "right_choice": "Panic selling is almost always wrong",
        "left_lesson": "Selling is rational when your **financial situation changes fundamentally** — not when markets are moving. Those are very different triggers.",
        "right_lesson": "Dalbar's 20-year study shows the average equity investor earned **4.7%** vs the S&P's **9.5%** — almost entirely due to panic selling at market lows.",
        "card_band_color": "red",
        "alpha": 0.4,
        "weights": {
            "sentiment": -0.4,
            "inflation": 0.0,
            "greed": -0.3,
            "volatility": 0.4,
            "fundamentals": -0.1,
        },
    },
    {
        "card_id": "EDU_5_002",
        "type": "education",
        "title": "FOMO and What It Costs You",
        "body": "**Fear of missing out** drives investors to chase recent winners — buying *after* gains are already made. By the time FOMO kicks in, **most of the return has already happened**.",
        "emoji": "😤",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["fomo"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.5,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "I can spot real opportunities",
        "right_choice": "FOMO is a bias, not an edge",
        "left_lesson": "FOMO feels like insight but it's actually **lagging information**. Assets that 'everyone is buying' are already priced for that enthusiasm.",
        "right_lesson": "Systematic diversified investing provides exposure to **the next big thing before it's obvious**. FOMO-driven investing gets the last 20% and the full downside.",
        "card_band_color": "purple",
        "alpha": 0.4,
        "weights": {
            "sentiment": 0.3,
            "inflation": 0.0,
            "greed": 0.6,
            "volatility": 0.2,
            "fundamentals": -0.2,
        },
    },
    {
        "card_id": "EDU_5_003",
        "type": "education",
        "title": "The Hidden Cost of Overtrading",
        "body": "Every trade costs **fees, spreads, and potentially taxes**. Active traders who trade 10x more than passive investors average **3.7% lower annual returns** — not from bad picks, but friction.",
        "emoji": "🔁",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["overtrading"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "More trades = more opportunities",
        "right_choice": "Trade less, keep more",
        "left_lesson": "Each trade costs not just the fee, but the **opportunity cost of capital in transit** and **tax drag from gains**. Friction compounds against you.",
        "right_lesson": "Studies show that investor accounts that are **forgotten or inactive** often outperform actively managed ones. Doing less, consistently, beats doing more.",
        "card_band_color": "amber",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.0,
            "inflation": 0.0,
            "greed": 0.3,
            "volatility": 0.15,
            "fundamentals": -0.15,
        },
    },
    {
        "card_id": "EDU_5_004",
        "type": "education",
        "title": "Staying Consistent Through Noise",
        "body": "Markets generate constant **noise** — daily price moves, news cycles, pundit predictions. Reacting to noise rather than **signal** is the defining mistake of most retail investors.",
        "emoji": "📻",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["consistency"],
        "linked_traits": ["patience", "fomo_sensitivity", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.85,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "Stay informed — react to news",
        "right_choice": "Filter noise — trust the process",
        "left_lesson": "Financial media is designed to **provoke reaction**. An investor who checks prices daily makes **4x more decisions** — and 4x more mistakes.",
        "right_lesson": "Setting a **quarterly review schedule** and automating contributions turns volatility from a threat into irrelevance. Structure is your protection from noise.",
        "card_band_color": "steel_blue",
        "alpha": 0.3,
        "weights": {
            "sentiment": 0.0,
            "inflation": 0.0,
            "greed": -0.1,
            "volatility": -0.2,
            "fundamentals": 0.2,
        },
    },
    {
        "card_id": "EVT_5_001",
        "type": "event",
        "title": "Market Crashes Hard",
        "body": "The market dropped **{value}%** in a month. Your portfolio is down significantly. Social media is full of predictions of further collapse. The **urge to sell is intense**.",
        "emoji": "🔻",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["panic_selling"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.65,
        "diagnostic_power": 0.9,
        "base_priority": 1.3,
        "cooldown": 4,
        "left_choice": "Sell — this one feels different",
        "right_choice": "Hold — trust the plan",
        "left_lesson": "Every crash *'feels different.'* The **2020 COVID crash** felt like permanent collapse — it recovered to all-time highs in **6 months**.",
        "right_lesson": "Investors who held through the **2008–2009 -55% crash** earned back their losses by 2013 and went on to **400%+ total returns** by 2024.",
        "card_band_color": "red",
        "value_min": 20.0,
        "value_max": 50.0,
        "value_step": 10.0,
        "alpha": 1.8,
        "weights": {
            "sentiment": -0.9,
            "inflation": 0.2,
            "greed": -0.6,
            "volatility": 0.9,
            "fundamentals": -0.5,
        },
    },
    {
        "card_id": "EVT_5_002",
        "type": "event",
        "title": "Viral Stock Tip",
        "body": "A stock is up **{value}%** today after a **viral social media post**. Everyone is talking about it. The momentum feels real and you don't want to miss it.",
        "emoji": "📱",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["fomo"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.55,
        "diagnostic_power": 0.85,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Buy in — momentum is real",
        "right_choice": "Skip it — FOMO is a trap",
        "left_lesson": "Retail investors who buy after a large same-day spike are the **exit liquidity** for early movers. The pattern is well-documented and rarely ends well.",
        "right_lesson": "Viral stocks often **retrace their entire move within weeks**. Your existing diversified allocation already beats chasing individual names over time.",
        "card_band_color": "purple",
        "value_min": 30.0,
        "value_max": 120.0,
        "value_step": 10.0,
        "alpha": 0.5,
        "weights": {
            "sentiment": 0.4,
            "inflation": 0.0,
            "greed": 0.8,
            "volatility": 0.5,
            "fundamentals": -0.4,
        },
    },
    {
        "card_id": "ACT_5_001",
        "type": "action",
        "title": "Override the Urge to Sell",
        "body": "Your portfolio is down **{value}%**. Every instinct says sell. But your **written investment plan** says hold. You have to choose between **emotion and your own rules**.",
        "emoji": "🧠",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["panic_selling"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.65,
        "diagnostic_power": 0.9,
        "base_priority": 1.3,
        "cooldown": 4,
        "left_choice": "Override the plan — sell now",
        "right_choice": "Follow the plan — override the feeling",
        "left_lesson": "*'This time is different'* has been said at **every major market bottom in history**. The plan you wrote when calm exists to protect you when you're not.",
        "right_lesson": "**Pre-committing to rules** before downturns is the most evidence-backed technique in behavioral finance. Your plan is smarter than your current emotion.",
        "card_band_color": "red",
        "value_min": 15.0,
        "value_max": 35.0,
        "value_step": 5.0,
        "alpha": 1.5,
        "weights": {
            "sentiment": -0.6,
            "inflation": 0.0,
            "greed": -0.4,
            "volatility": 0.7,
            "fundamentals": -0.2,
        },
    },
    {
        "card_id": "ACT_5_002",
        "type": "action",
        "title": "Commit to the Plan",
        "body": "You commit to **not changing your portfolio allocation** for **{value} months** regardless of market moves. This constraint is itself a **powerful financial decision**.",
        "emoji": "📋",
        "stage_min": 5,
        "stage_max": 5,
        "topics": ["consistency"],
        "linked_traits": ["patience", "loss_aversion"],
        "difficulty": 0.55,
        "diagnostic_power": 0.8,
        "base_priority": 1.2,
        "cooldown": 5,
        "left_choice": "I need flexibility to react",
        "right_choice": "Commit to the constraint",
        "left_lesson": "Investors who maintain the option to react often **exercise it at the worst times**. Flexibility becomes a liability when driven by emotion.",
        "right_lesson": "Studies show investors with **self-imposed trading freezes** outperform those with full flexibility. Removing the option to panic is more valuable than it sounds.",
        "card_band_color": "steel_blue",
        "value_min": 3.0,
        "value_max": 24.0,
        "value_step": 3.0,
        "alpha": 0.6,
        "weights": {
            "sentiment": 0.1,
            "inflation": 0.0,
            "greed": -0.2,
            "volatility": -0.25,
            "fundamentals": 0.3,
        },
    },
]

SEED_CARDS.extend(GREAT_DEPRESSION_CARDS)
SEED_CARDS.extend(COVID_ERA_CARDS)
