"""Financial statements themed deck cards (shop deck)."""

FINANCIAL_STATEMENTS_CARDS = [
    {
        "card_id": "FST_E_001",
        "type": "education",
        "title": "Income Statement Basics",
        "body": "The income statement shows revenue, expenses, and profit for a period. It explains whether growth is translating into earnings.",
        "emoji": "🧾",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["financial_statements", "income_statement"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.38,
        "diagnostic_power": 0.76,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Revenue alone tells enough",
        "right_choice": "Profit quality matters too",
        "left_lesson": "Fun fact: Fast revenue growth with weak margins often leads to disappointing long-run returns.",
        "right_lesson": "Fun fact: Sustainable earnings typically require both pricing power and cost discipline.",
        "card_band_color": "steel_blue",
        "alpha": 0.85,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": -0.05, "volatility": 0.05, "fundamentals": 0.35},
    },
    {
        "card_id": "FST_E_002",
        "type": "education",
        "title": "Gross Margin Signal",
        "body": "Gross margin measures how much profit remains after direct production costs. Rising margin can indicate pricing power or efficiency.",
        "emoji": "📈",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "margins"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.4,
        "diagnostic_power": 0.78,
        "base_priority": 1.08,
        "cooldown": 6,
        "left_choice": "Ignore margin trend",
        "right_choice": "Track margin direction",
        "left_lesson": "Fun fact: Margin compression often appears before earnings misses become obvious.",
        "right_lesson": "Fun fact: A stable or rising gross margin can support valuation multiples through cycles.",
        "card_band_color": "green",
        "alpha": 0.88,
        "weights": {"sentiment": 0.08, "inflation": -0.05, "greed": 0.0, "volatility": -0.02, "fundamentals": 0.32},
    },
    {
        "card_id": "FST_E_003",
        "type": "education",
        "title": "Operating Margin Discipline",
        "body": "Operating margin includes overhead like sales and administration. It reveals whether scale is improving efficiency.",
        "emoji": "⚙️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "operating_margin"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.42,
        "diagnostic_power": 0.8,
        "base_priority": 1.06,
        "cooldown": 6,
        "left_choice": "Scale always boosts margin",
        "right_choice": "Watch operating leverage",
        "left_lesson": "Fun fact: Some firms grow revenue but add costs faster, shrinking operating margin.",
        "right_lesson": "Fun fact: Strong operating leverage often separates durable compounders from temporary winners.",
        "card_band_color": "steel_blue",
        "alpha": 0.9,
        "weights": {"sentiment": 0.05, "inflation": 0.0, "greed": -0.03, "volatility": 0.02, "fundamentals": 0.34},
    },
    {
        "card_id": "FST_E_004",
        "type": "education",
        "title": "EBITDA vs Cash Flow",
        "body": "EBITDA excludes interest, taxes, and some non-cash costs, but cash flow shows actual cash generation. They are not interchangeable.",
        "emoji": "💧",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "cash_flow"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.5,
        "diagnostic_power": 0.82,
        "base_priority": 1.12,
        "cooldown": 7,
        "left_choice": "EBITDA is enough",
        "right_choice": "Follow free cash flow",
        "left_lesson": "Fun fact: Companies can report solid EBITDA while burning cash for years.",
        "right_lesson": "Fun fact: Free cash flow supports debt service, buybacks, and dividends without external funding.",
        "card_band_color": "amber",
        "alpha": 0.95,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.08, "volatility": 0.06, "fundamentals": 0.38},
    },
    {
        "card_id": "FST_E_005",
        "type": "education",
        "title": "Balance Sheet Strength",
        "body": "A balance sheet lists assets, liabilities, and equity at a point in time. It shows financial resilience when conditions worsen.",
        "emoji": "🏛️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "balance_sheet"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.4,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Growth matters more",
        "right_choice": "Solvency matters too",
        "left_lesson": "Fun fact: Highly leveraged firms often underperform in tightening cycles.",
        "right_lesson": "Fun fact: Cash-rich balance sheets can turn downturns into acquisition opportunities.",
        "card_band_color": "green",
        "alpha": 0.9,
        "weights": {"sentiment": 0.06, "inflation": -0.05, "greed": -0.05, "volatility": -0.04, "fundamentals": 0.36},
    },
    {
        "card_id": "FST_E_006",
        "type": "education",
        "title": "Current Ratio Check",
        "body": "Current ratio compares short-term assets to short-term liabilities. It helps estimate near-term liquidity pressure.",
        "emoji": "🧮",
        "stage_min": 2,
        "stage_max": 4,
        "topics": ["financial_statements", "liquidity"],
        "linked_traits": ["loss_aversion", "overconfidence"],
        "difficulty": 0.36,
        "diagnostic_power": 0.74,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Liquidity is secondary",
        "right_choice": "Short-term coverage matters",
        "left_lesson": "Fun fact: Liquidity squeezes can force equity dilution even before insolvency.",
        "right_lesson": "Fun fact: Working capital management can materially reduce financing risk.",
        "card_band_color": "steel_blue",
        "alpha": 0.83,
        "weights": {"sentiment": -0.02, "inflation": 0.0, "greed": -0.08, "volatility": 0.08, "fundamentals": 0.28},
    },
    {
        "card_id": "FST_E_007",
        "type": "education",
        "title": "Debt to Equity Context",
        "body": "Debt-to-equity varies by sector. Comparing leverage across peers is more useful than using one universal threshold.",
        "emoji": "⚖️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "leverage"],
        "linked_traits": ["risk_appetite", "loss_aversion"],
        "difficulty": 0.46,
        "diagnostic_power": 0.79,
        "base_priority": 1.07,
        "cooldown": 6,
        "left_choice": "All leverage is bad",
        "right_choice": "Context by industry",
        "left_lesson": "Fun fact: Utilities often carry higher debt sustainably due to stable cash flows.",
        "right_lesson": "Fun fact: Cyclical businesses usually need lower leverage buffers through downturns.",
        "card_band_color": "amber",
        "alpha": 0.9,
        "weights": {"sentiment": 0.0, "inflation": -0.03, "greed": 0.02, "volatility": 0.05, "fundamentals": 0.31},
    },
    {
        "card_id": "FST_E_008",
        "type": "education",
        "title": "Interest Coverage",
        "body": "Interest coverage compares operating profit to interest expense. Low coverage leaves little room for earnings volatility.",
        "emoji": "📉",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "interest_coverage"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.48,
        "diagnostic_power": 0.81,
        "base_priority": 1.09,
        "cooldown": 6,
        "left_choice": "Refinancing will fix it",
        "right_choice": "Coverage buffer is key",
        "left_lesson": "Fun fact: Rising rates can quickly pressure weak coverage profiles.",
        "right_lesson": "Fun fact: Healthy coverage often supports more resilient credit spreads.",
        "card_band_color": "red",
        "alpha": 0.96,
        "weights": {"sentiment": -0.08, "inflation": -0.05, "greed": -0.05, "volatility": 0.1, "fundamentals": 0.3},
    },
    {
        "card_id": "FST_E_009",
        "type": "education",
        "title": "Return on Equity",
        "body": "ROE measures profit generated per unit of shareholder equity. High ROE is strongest when leverage is controlled.",
        "emoji": "🎯",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "roe"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.45,
        "diagnostic_power": 0.77,
        "base_priority": 1.05,
        "cooldown": 6,
        "left_choice": "ROE alone decides",
        "right_choice": "ROE plus leverage check",
        "left_lesson": "Fun fact: Financial leverage can artificially inflate ROE without improving business quality.",
        "right_lesson": "Fun fact: Durable high ROE with moderate debt is often a quality hallmark.",
        "card_band_color": "green",
        "alpha": 0.88,
        "weights": {"sentiment": 0.08, "inflation": 0.0, "greed": 0.05, "volatility": -0.02, "fundamentals": 0.3},
    },
    {
        "card_id": "FST_E_010",
        "type": "education",
        "title": "Return on Invested Capital",
        "body": "ROIC evaluates profits against all capital used in the business. It helps compare firms with different debt levels.",
        "emoji": "📊",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "roic"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.5,
        "diagnostic_power": 0.83,
        "base_priority": 1.1,
        "cooldown": 7,
        "left_choice": "EPS trend is enough",
        "right_choice": "ROIC shows efficiency",
        "left_lesson": "Fun fact: EPS can rise through buybacks even when capital efficiency is flat.",
        "right_lesson": "Fun fact: Persistent ROIC above cost of capital supports long-term compounding.",
        "card_band_color": "steel_blue",
        "alpha": 0.94,
        "weights": {"sentiment": 0.06, "inflation": 0.0, "greed": 0.0, "volatility": -0.03, "fundamentals": 0.37},
    },
    {
        "card_id": "FST_E_011",
        "type": "education",
        "title": "Earnings Quality Red Flags",
        "body": "Large one-off gains, aggressive adjustments, or weak cash conversion can signal low earnings quality.",
        "emoji": "🚩",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "earnings_quality"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.52,
        "diagnostic_power": 0.84,
        "base_priority": 1.12,
        "cooldown": 7,
        "left_choice": "Adjusted EPS is fine",
        "right_choice": "Check recurring earnings",
        "left_lesson": "Fun fact: Repeated ""one-time"" adjustments often become a recurring pattern.",
        "right_lesson": "Fun fact: High-quality earnings usually reconcile with operating cash flow over time.",
        "card_band_color": "red",
        "alpha": 1.0,
        "weights": {"sentiment": -0.05, "inflation": 0.0, "greed": -0.1, "volatility": 0.12, "fundamentals": 0.34},
    },
    {
        "card_id": "FST_E_012",
        "type": "education",
        "title": "Capex and Maintenance",
        "body": "Capital expenditure can fund growth or simply maintain operations. Free cash flow depends on that difference.",
        "emoji": "🏗️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "capex"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.47,
        "diagnostic_power": 0.8,
        "base_priority": 1.06,
        "cooldown": 6,
        "left_choice": "Capex always creates value",
        "right_choice": "Separate growth vs upkeep",
        "left_lesson": "Fun fact: High capex intensity can suppress owner earnings for long stretches.",
        "right_lesson": "Fun fact: Asset-light models often convert a higher share of profit into cash.",
        "card_band_color": "amber",
        "alpha": 0.92,
        "weights": {"sentiment": 0.03, "inflation": 0.05, "greed": 0.0, "volatility": 0.04, "fundamentals": 0.31},
    },
    {
        "card_id": "FST_E_013",
        "type": "education",
        "title": "Working Capital Turns",
        "body": "Inventory, receivables, and payables shape cash timing. Faster working-capital turns improve resilience.",
        "emoji": "🔄",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "working_capital"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.44,
        "diagnostic_power": 0.76,
        "base_priority": 1.04,
        "cooldown": 6,
        "left_choice": "Only EPS matters",
        "right_choice": "Cash cycle matters too",
        "left_lesson": "Fun fact: Inventory buildup can foreshadow weaker demand and write-down risk.",
        "right_lesson": "Fun fact: Efficient cash conversion can fund growth with less external debt.",
        "card_band_color": "steel_blue",
        "alpha": 0.87,
        "weights": {"sentiment": 0.02, "inflation": 0.0, "greed": -0.02, "volatility": 0.03, "fundamentals": 0.29},
    },
    {
        "card_id": "FST_E_014",
        "type": "education",
        "title": "Guidance vs Results",
        "body": "Forward guidance sets expectations, but repeated misses can damage management credibility and valuation.",
        "emoji": "🗓️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "guidance"],
        "linked_traits": ["fomo_sensitivity", "overconfidence"],
        "difficulty": 0.4,
        "diagnostic_power": 0.75,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Trust optimistic guidance",
        "right_choice": "Compare promises to delivery",
        "left_lesson": "Fun fact: Revisions often move valuations more than absolute earnings levels.",
        "right_lesson": "Fun fact: Credible guidance lowers uncertainty and can reduce equity risk premium.",
        "card_band_color": "purple",
        "alpha": 0.86,
        "weights": {"sentiment": 0.12, "inflation": 0.0, "greed": 0.1, "volatility": 0.04, "fundamentals": 0.22},
    },
    {
        "card_id": "FST_V_001",
        "type": "event",
        "title": "Revenue Miss",
        "body": "Quarterly revenue comes in {value}% below consensus while management keeps full-year targets unchanged.",
        "emoji": "📉",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "income_statement"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.5,
        "diagnostic_power": 0.84,
        "base_priority": 1.14,
        "cooldown": 5,
        "left_choice": "Dismiss as noise",
        "right_choice": "Reassess assumptions",
        "left_lesson": "Fun fact: Revenue misses can signal demand softness before margins react.",
        "right_lesson": "Fun fact: Early estimate revision often improves decision quality versus waiting for confirmation.",
        "card_band_color": "red",
        "value_min": 2.0,
        "value_max": 12.0,
        "value_step": 1.0,
        "alpha": 1.05,
        "weights": {"sentiment": -0.25, "inflation": 0.0, "greed": -0.12, "volatility": 0.32, "fundamentals": -0.18},
    },
    {
        "card_id": "FST_V_002",
        "type": "event",
        "title": "Gross Margin Compression",
        "body": "Input costs rise and gross margin contracts by {value} basis points compared with last year.",
        "emoji": "🧯",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "margins"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.52,
        "diagnostic_power": 0.82,
        "base_priority": 1.12,
        "cooldown": 5,
        "left_choice": "Margin will rebound quickly",
        "right_choice": "Model a slower recovery",
        "left_lesson": "Fun fact: Margin pressure often persists when contracts reset with delay.",
        "right_lesson": "Fun fact: Conservative margin assumptions reduce downside surprise risk.",
        "card_band_color": "amber",
        "value_min": 50.0,
        "value_max": 500.0,
        "value_step": 50.0,
        "alpha": 1.04,
        "weights": {"sentiment": -0.15, "inflation": 0.12, "greed": -0.05, "volatility": 0.25, "fundamentals": -0.15},
    },
    {
        "card_id": "FST_V_003",
        "type": "event",
        "title": "Operating Expense Spike",
        "body": "Operating expenses jump {value}% after a rapid hiring cycle and integration costs.",
        "emoji": "💼",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "operating_margin"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.48,
        "diagnostic_power": 0.8,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Ignore temporary cost surge",
        "right_choice": "Stress-test op margin",
        "left_lesson": "Fun fact: Cost discipline breakdown can last several quarters after rapid expansion.",
        "right_lesson": "Fun fact: Scenario analysis around opex helps avoid multiple compression shocks.",
        "card_band_color": "red",
        "value_min": 5.0,
        "value_max": 25.0,
        "value_step": 5.0,
        "alpha": 1.02,
        "weights": {"sentiment": -0.16, "inflation": 0.05, "greed": -0.06, "volatility": 0.28, "fundamentals": -0.16},
    },
    {
        "card_id": "FST_V_004",
        "type": "event",
        "title": "Cash Flow Beat",
        "body": "Free cash flow surprises on the upside by {value}% from better receivables collection.",
        "emoji": "💸",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "cash_flow"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.46,
        "diagnostic_power": 0.79,
        "base_priority": 1.08,
        "cooldown": 5,
        "left_choice": "Treat as one-off",
        "right_choice": "Update cash outlook",
        "left_lesson": "Fun fact: Cash conversion improvements can mark a durable quality shift.",
        "right_lesson": "Fun fact: Cash flow beats often support deleveraging and buyback capacity.",
        "card_band_color": "green",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 1.0,
        "weights": {"sentiment": 0.18, "inflation": -0.02, "greed": 0.08, "volatility": -0.05, "fundamentals": 0.22},
    },
    {
        "card_id": "FST_V_005",
        "type": "event",
        "title": "Inventory Build",
        "body": "Inventory days rise by {value} days while management cites planned stocking ahead of demand.",
        "emoji": "📦",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "working_capital"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.49,
        "diagnostic_power": 0.8,
        "base_priority": 1.09,
        "cooldown": 5,
        "left_choice": "Assume demand is strong",
        "right_choice": "Watch sell-through closely",
        "left_lesson": "Fun fact: Excess inventory often leads to discounts and margin erosion later.",
        "right_lesson": "Fun fact: Inventory quality can be as important as inventory size in cyclicals.",
        "card_band_color": "amber",
        "value_min": 5.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 1.03,
        "weights": {"sentiment": -0.08, "inflation": 0.03, "greed": 0.02, "volatility": 0.18, "fundamentals": -0.12},
    },
    {
        "card_id": "FST_V_006",
        "type": "event",
        "title": "Receivables Stretch",
        "body": "Days sales outstanding extends by {value} days as customers delay payments.",
        "emoji": "🧾",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "liquidity"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.51,
        "diagnostic_power": 0.81,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Ignore collection drift",
        "right_choice": "Revisit credit risk",
        "left_lesson": "Fun fact: Slower collections can precede both cash stress and bad-debt charges.",
        "right_lesson": "Fun fact: Tightening customer terms early can protect downside in weak cycles.",
        "card_band_color": "red",
        "value_min": 3.0,
        "value_max": 30.0,
        "value_step": 3.0,
        "alpha": 1.06,
        "weights": {"sentiment": -0.14, "inflation": 0.0, "greed": -0.04, "volatility": 0.2, "fundamentals": -0.14},
    },
    {
        "card_id": "FST_V_007",
        "type": "event",
        "title": "Debt Repricing",
        "body": "A refinancing updates average borrowing cost to {value}%, reducing future net income guidance.",
        "emoji": "🏦",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "leverage"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.54,
        "diagnostic_power": 0.83,
        "base_priority": 1.12,
        "cooldown": 5,
        "left_choice": "Rate move is minor",
        "right_choice": "Adjust earnings model",
        "left_lesson": "Fun fact: Higher interest expense can erase operating improvements in leveraged firms.",
        "right_lesson": "Fun fact: Refinancing schedules are critical during tightening cycles.",
        "card_band_color": "red",
        "value_min": 3.0,
        "value_max": 12.0,
        "value_step": 1.0,
        "alpha": 1.08,
        "weights": {"sentiment": -0.18, "inflation": -0.08, "greed": -0.04, "volatility": 0.24, "fundamentals": -0.15},
    },
    {
        "card_id": "FST_V_008",
        "type": "event",
        "title": "Credit Rating Downgrade",
        "body": "A one-notch downgrade lifts credit spreads and raises expected annual financing cost by {value} bps.",
        "emoji": "📉",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "interest_coverage"],
        "linked_traits": ["loss_aversion", "overconfidence"],
        "difficulty": 0.55,
        "diagnostic_power": 0.84,
        "base_priority": 1.13,
        "cooldown": 5,
        "left_choice": "Downgrade is cosmetic",
        "right_choice": "Expect higher hurdle rates",
        "left_lesson": "Fun fact: Ratings changes can affect collateral terms and liquidity access.",
        "right_lesson": "Fun fact: Rising financing spreads can compress equity valuation multiples.",
        "card_band_color": "amber",
        "value_min": 25.0,
        "value_max": 200.0,
        "value_step": 25.0,
        "alpha": 1.08,
        "weights": {"sentiment": -0.16, "inflation": -0.05, "greed": -0.05, "volatility": 0.26, "fundamentals": -0.16},
    },
    {
        "card_id": "FST_V_009",
        "type": "event",
        "title": "Share Count Expansion",
        "body": "The company issues equity and diluted share count rises {value}% to strengthen liquidity.",
        "emoji": "🪙",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "capital_structure"],
        "linked_traits": ["fomo_sensitivity", "loss_aversion"],
        "difficulty": 0.47,
        "diagnostic_power": 0.78,
        "base_priority": 1.05,
        "cooldown": 5,
        "left_choice": "Ignore dilution effect",
        "right_choice": "Recalculate per-share value",
        "left_lesson": "Fun fact: Dilution can offset headline profit growth on a per-share basis.",
        "right_lesson": "Fun fact: Capital raises are healthiest when paired with clear return-on-capital plans.",
        "card_band_color": "purple",
        "value_min": 2.0,
        "value_max": 20.0,
        "value_step": 2.0,
        "alpha": 0.98,
        "weights": {"sentiment": -0.05, "inflation": 0.0, "greed": 0.1, "volatility": 0.14, "fundamentals": -0.1},
    },
    {
        "card_id": "FST_V_010",
        "type": "event",
        "title": "One-Time Gain Distortion",
        "body": "Reported EPS beats by {value}% due to an asset sale gain unrelated to core operations.",
        "emoji": "🎭",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "earnings_quality"],
        "linked_traits": ["overconfidence", "fomo_sensitivity"],
        "difficulty": 0.5,
        "diagnostic_power": 0.82,
        "base_priority": 1.09,
        "cooldown": 5,
        "left_choice": "Buy the headline beat",
        "right_choice": "Strip one-offs first",
        "left_lesson": "Fun fact: Headline EPS reactions can reverse when analysts normalize earnings.",
        "right_lesson": "Fun fact: Core earnings trends usually drive medium-term price direction.",
        "card_band_color": "amber",
        "value_min": 5.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 1.01,
        "weights": {"sentiment": 0.1, "inflation": 0.0, "greed": 0.15, "volatility": 0.16, "fundamentals": -0.08},
    },
    {
        "card_id": "FST_V_011",
        "type": "event",
        "title": "Capex Guidance Increase",
        "body": "Management raises next-year capex budget by {value}% to expand capacity and automation.",
        "emoji": "🏗️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "capex"],
        "linked_traits": ["risk_appetite", "patience"],
        "difficulty": 0.49,
        "diagnostic_power": 0.79,
        "base_priority": 1.06,
        "cooldown": 5,
        "left_choice": "Treat as value-destructive",
        "right_choice": "Assess expected returns",
        "left_lesson": "Fun fact: Capex can destroy value when returns stay below cost of capital.",
        "right_lesson": "Fun fact: High-return capacity investments can support multiyear margin expansion.",
        "card_band_color": "steel_blue",
        "value_min": 5.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 1.0,
        "weights": {"sentiment": 0.05, "inflation": 0.06, "greed": 0.05, "volatility": 0.08, "fundamentals": 0.12},
    },
    {
        "card_id": "FST_V_012",
        "type": "event",
        "title": "Guidance Cut",
        "body": "Full-year EPS guidance is reduced by {value}% after weaker order visibility.",
        "emoji": "✂️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "guidance"],
        "linked_traits": ["loss_aversion", "fomo_sensitivity"],
        "difficulty": 0.5,
        "diagnostic_power": 0.83,
        "base_priority": 1.13,
        "cooldown": 5,
        "left_choice": "Hold prior assumptions",
        "right_choice": "Reset fair value range",
        "left_lesson": "Fun fact: Negative estimate revisions often drive momentum on the downside.",
        "right_lesson": "Fun fact: Updating assumptions quickly reduces anchoring bias.",
        "card_band_color": "red",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 1.08,
        "weights": {"sentiment": -0.22, "inflation": 0.0, "greed": -0.08, "volatility": 0.29, "fundamentals": -0.2},
    },
    {
        "card_id": "FST_V_013",
        "type": "event",
        "title": "Buyback Pause",
        "body": "The board pauses repurchases to preserve cash after leverage moves above internal limits.",
        "emoji": "⏸️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "capital_structure"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.47,
        "diagnostic_power": 0.77,
        "base_priority": 1.04,
        "cooldown": 5,
        "left_choice": "Pause is bearish only",
        "right_choice": "Deleveraging can be prudent",
        "left_lesson": "Fun fact: Buyback support can vanish quickly when balance-sheet pressure rises.",
        "right_lesson": "Fun fact: Capital allocation flexibility matters more than buyback consistency.",
        "card_band_color": "amber",
        "alpha": 0.99,
        "weights": {"sentiment": -0.06, "inflation": 0.0, "greed": -0.02, "volatility": 0.12, "fundamentals": 0.03},
    },
    {
        "card_id": "FST_A_001",
        "type": "action",
        "title": "Build a Statement Checklist",
        "body": "Create a pre-trade checklist with at least {value} core metrics from income statement, balance sheet, and cash flow.",
        "emoji": "✅",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "process"],
        "linked_traits": ["patience", "overconfidence"],
        "difficulty": 0.38,
        "diagnostic_power": 0.76,
        "base_priority": 1.07,
        "cooldown": 6,
        "left_choice": "Trade on headlines",
        "right_choice": "Use a fixed checklist",
        "left_lesson": "Fun fact: Unstructured analysis increases recency and confirmation bias.",
        "right_lesson": "Fun fact: Checklists improve consistency in both medicine and investing decisions.",
        "card_band_color": "green",
        "value_min": 5.0,
        "value_max": 12.0,
        "value_step": 1.0,
        "alpha": 0.9,
        "weights": {"sentiment": 0.03, "inflation": 0.0, "greed": -0.12, "volatility": -0.08, "fundamentals": 0.2},
    },
    {
        "card_id": "FST_A_002",
        "type": "action",
        "title": "Trim on Weak Cash Conversion",
        "body": "If operating cash flow stays below net income for {value} straight quarters, reduce position size.",
        "emoji": "✂️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "cash_flow"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.5,
        "diagnostic_power": 0.82,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Hold despite weak conversion",
        "right_choice": "Reduce risk systematically",
        "left_lesson": "Fun fact: Weak cash conversion can precede earnings restatements or guidance cuts.",
        "right_lesson": "Fun fact: Rule-based trims can reduce drawdown without overtrading.",
        "card_band_color": "amber",
        "value_min": 2.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 1.0,
        "weights": {"sentiment": -0.05, "inflation": 0.0, "greed": -0.08, "volatility": -0.02, "fundamentals": 0.16},
    },
    {
        "card_id": "FST_A_003",
        "type": "action",
        "title": "Set Minimum Interest Coverage",
        "body": "Only add leveraged names with interest coverage above {value}x under your base-case model.",
        "emoji": "🛡️",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "interest_coverage"],
        "linked_traits": ["loss_aversion", "risk_appetite"],
        "difficulty": 0.49,
        "diagnostic_power": 0.8,
        "base_priority": 1.06,
        "cooldown": 5,
        "left_choice": "Waive coverage requirement",
        "right_choice": "Keep hard risk limits",
        "left_lesson": "Fun fact: Weak coverage names are more exposed to refinancing shocks.",
        "right_lesson": "Fun fact: Minimum quality filters can improve long-run downside control.",
        "card_band_color": "green",
        "value_min": 2.0,
        "value_max": 8.0,
        "value_step": 1.0,
        "alpha": 0.95,
        "weights": {"sentiment": 0.02, "inflation": -0.02, "greed": -0.1, "volatility": -0.1, "fundamentals": 0.22},
    },
    {
        "card_id": "FST_A_004",
        "type": "action",
        "title": "Demand Margin of Safety",
        "body": "Require at least a {value}% discount to your conservative fair value estimate before initiating.",
        "emoji": "📐",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "valuation"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.44,
        "diagnostic_power": 0.78,
        "base_priority": 1.04,
        "cooldown": 6,
        "left_choice": "Buy at any price",
        "right_choice": "Wait for valuation buffer",
        "left_lesson": "Fun fact: Entry price has a strong influence on medium-term outcomes.",
        "right_lesson": "Fun fact: A valuation buffer helps absorb forecast and macro errors.",
        "card_band_color": "steel_blue",
        "value_min": 10.0,
        "value_max": 40.0,
        "value_step": 5.0,
        "alpha": 0.92,
        "weights": {"sentiment": -0.02, "inflation": 0.0, "greed": -0.12, "volatility": -0.08, "fundamentals": 0.18},
    },
    {
        "card_id": "FST_A_005",
        "type": "action",
        "title": "Cap Single-Name Exposure",
        "body": "Limit any one statement-driven idea to {value}% of total portfolio value to control idiosyncratic risk.",
        "emoji": "📏",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "risk_management"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.4,
        "diagnostic_power": 0.75,
        "base_priority": 1.02,
        "cooldown": 6,
        "left_choice": "Concentrate top conviction",
        "right_choice": "Use hard position caps",
        "left_lesson": "Fun fact: Concentration magnifies both analysis edge and analysis errors.",
        "right_lesson": "Fun fact: Position-sizing rules are core to professional risk frameworks.",
        "card_band_color": "green",
        "value_min": 5.0,
        "value_max": 20.0,
        "value_step": 5.0,
        "alpha": 0.88,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.1, "volatility": -0.12, "fundamentals": 0.16},
    },
    {
        "card_id": "FST_A_006",
        "type": "action",
        "title": "Model Three Scenarios",
        "body": "Build bear, base, and bull statement forecasts with revenue bands of +/- {value}% around consensus.",
        "emoji": "🧠",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "scenario_analysis"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.52,
        "diagnostic_power": 0.83,
        "base_priority": 1.1,
        "cooldown": 6,
        "left_choice": "Use one-point estimate",
        "right_choice": "Use probability ranges",
        "left_lesson": "Fun fact: Single-point forecasts hide asymmetric risk.",
        "right_lesson": "Fun fact: Scenario ranges improve decision quality under uncertainty.",
        "card_band_color": "steel_blue",
        "value_min": 5.0,
        "value_max": 25.0,
        "value_step": 5.0,
        "alpha": 0.98,
        "weights": {"sentiment": 0.01, "inflation": 0.0, "greed": -0.06, "volatility": -0.06, "fundamentals": 0.2},
    },
    {
        "card_id": "FST_A_007",
        "type": "action",
        "title": "Prioritize Free Cash Flow Yield",
        "body": "Add exposure only when free-cash-flow yield exceeds {value}% and balance-sheet risk is stable.",
        "emoji": "💵",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "cash_flow"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.5,
        "diagnostic_power": 0.81,
        "base_priority": 1.07,
        "cooldown": 6,
        "left_choice": "Chase narrative growth",
        "right_choice": "Demand cash yield",
        "left_lesson": "Fun fact: Narrative-heavy names can de-rate quickly when liquidity tightens.",
        "right_lesson": "Fun fact: FCF yield discipline can improve risk-adjusted returns in mature sectors.",
        "card_band_color": "green",
        "value_min": 3.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 0.96,
        "weights": {"sentiment": 0.04, "inflation": -0.02, "greed": -0.08, "volatility": -0.06, "fundamentals": 0.23},
    },
    {
        "card_id": "FST_A_008",
        "type": "action",
        "title": "Use Post-Earnings Cooldown",
        "body": "Wait {value} trading days after earnings before resizing, unless thesis-breaking data appears.",
        "emoji": "⏳",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "behavior"],
        "linked_traits": ["fomo_sensitivity", "patience"],
        "difficulty": 0.42,
        "diagnostic_power": 0.74,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "Trade reaction immediately",
        "right_choice": "Let volatility settle",
        "left_lesson": "Fun fact: Post-earnings moves can overshoot before fundamentals are fully processed.",
        "right_lesson": "Fun fact: Cooling periods reduce impulsive decisions driven by headline volatility.",
        "card_band_color": "amber",
        "value_min": 1.0,
        "value_max": 10.0,
        "value_step": 1.0,
        "alpha": 0.87,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.09, "volatility": -0.1, "fundamentals": 0.12},
    },
    {
        "card_id": "FST_A_009",
        "type": "action",
        "title": "Monitor Covenant Headroom",
        "body": "Set alerts when covenant headroom drops below {value}% under your downside case.",
        "emoji": "🚨",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "leverage"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.53,
        "diagnostic_power": 0.83,
        "base_priority": 1.1,
        "cooldown": 5,
        "left_choice": "Ignore covenant details",
        "right_choice": "Track covenant buffers",
        "left_lesson": "Fun fact: Covenant breaches can trigger costly renegotiations or forced asset sales.",
        "right_lesson": "Fun fact: Early covenant monitoring improves optionality before stress peaks.",
        "card_band_color": "red",
        "value_min": 5.0,
        "value_max": 30.0,
        "value_step": 5.0,
        "alpha": 1.02,
        "weights": {"sentiment": -0.04, "inflation": 0.0, "greed": -0.06, "volatility": -0.03, "fundamentals": 0.2},
    },
    {
        "card_id": "FST_A_010",
        "type": "action",
        "title": "Penalize Repeated Guidance Misses",
        "body": "Reduce target multiple by {value}% after two consecutive guidance misses.",
        "emoji": "📉",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "guidance"],
        "linked_traits": ["overconfidence", "loss_aversion"],
        "difficulty": 0.46,
        "diagnostic_power": 0.79,
        "base_priority": 1.03,
        "cooldown": 6,
        "left_choice": "Keep same multiple",
        "right_choice": "Apply credibility discount",
        "left_lesson": "Fun fact: Management credibility is a valuation input, not just a narrative detail.",
        "right_lesson": "Fun fact: Systematic penalties reduce anchoring to stale bull cases.",
        "card_band_color": "amber",
        "value_min": 5.0,
        "value_max": 25.0,
        "value_step": 5.0,
        "alpha": 0.9,
        "weights": {"sentiment": -0.03, "inflation": 0.0, "greed": -0.04, "volatility": -0.04, "fundamentals": 0.15},
    },
    {
        "card_id": "FST_A_011",
        "type": "action",
        "title": "Reward Improving ROIC",
        "body": "Increase conviction one step when ROIC improves for {value} consecutive periods with stable leverage.",
        "emoji": "📈",
        "stage_min": 3,
        "stage_max": 5,
        "topics": ["financial_statements", "roic"],
        "linked_traits": ["patience", "risk_appetite"],
        "difficulty": 0.48,
        "diagnostic_power": 0.78,
        "base_priority": 1.04,
        "cooldown": 6,
        "left_choice": "Ignore ROIC trend",
        "right_choice": "Scale with efficiency",
        "left_lesson": "Fun fact: Capital efficiency trends often lead multi-year rerating stories.",
        "right_lesson": "Fun fact: ROIC improvement with stable leverage is harder to fake.",
        "card_band_color": "green",
        "value_min": 2.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 0.91,
        "weights": {"sentiment": 0.08, "inflation": 0.0, "greed": 0.02, "volatility": -0.04, "fundamentals": 0.19},
    },
    {
        "card_id": "FST_A_012",
        "type": "action",
        "title": "Require Cash Buffer",
        "body": "Favor issuers with cash covering at least {value} months of operating expenses.",
        "emoji": "🏦",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "balance_sheet"],
        "linked_traits": ["loss_aversion", "patience"],
        "difficulty": 0.43,
        "diagnostic_power": 0.75,
        "base_priority": 1.01,
        "cooldown": 6,
        "left_choice": "Cash buffer unnecessary",
        "right_choice": "Prefer liquidity cushion",
        "left_lesson": "Fun fact: Cash cushions reduce forced financing risk in downturns.",
        "right_lesson": "Fun fact: Liquidity buffers improve strategic flexibility and negotiation power.",
        "card_band_color": "green",
        "value_min": 3.0,
        "value_max": 18.0,
        "value_step": 3.0,
        "alpha": 0.89,
        "weights": {"sentiment": 0.04, "inflation": -0.02, "greed": -0.06, "volatility": -0.08, "fundamentals": 0.18},
    },
    {
        "card_id": "FST_A_013",
        "type": "action",
        "title": "Quarterly Thesis Audit",
        "body": "Schedule a full thesis audit every {value} months using updated statements and peer comparisons.",
        "emoji": "🗂️",
        "stage_min": 2,
        "stage_max": 5,
        "topics": ["financial_statements", "process"],
        "linked_traits": ["overconfidence", "patience"],
        "difficulty": 0.4,
        "diagnostic_power": 0.74,
        "base_priority": 1.0,
        "cooldown": 6,
        "left_choice": "Review only when price drops",
        "right_choice": "Use fixed review cadence",
        "left_lesson": "Fun fact: Event-driven reviews can reinforce emotional rather than analytical decisions.",
        "right_lesson": "Fun fact: A fixed cadence improves objectivity and comparability across periods.",
        "card_band_color": "steel_blue",
        "value_min": 1.0,
        "value_max": 6.0,
        "value_step": 1.0,
        "alpha": 0.86,
        "weights": {"sentiment": 0.0, "inflation": 0.0, "greed": -0.07, "volatility": -0.07, "fundamentals": 0.16},
    },
]
